"""Initial native domain model scaffold generated by servicegen."""

from dataclasses import dataclass, field
from datetime import datetime

from model.models.order_item import OrderItem


# E-commerce order submitted by a customer. Fields: ID string, CustomerID string, Items []OrderItem, CreatedAt time.Time.
@dataclass(slots=True)
class Order:
    id: str
    customer_id: str = ""
    items: list[OrderItem] = field(default_factory=list)
    total_amount: float = 0.0
    created_at: datetime | None = None
    trace_id: str = ""
