"""Initial native domain model scaffold generated by servicegen."""

from dataclasses import dataclass, field
from datetime import datetime

from model.models.order_item_result import OrderItemResult


# Processing result of an order. Fields: OrderID string, Status string (CONFIRMED — all items reserved; PARTIALLY_CONFIRMED — some items out of stock; TIMED_OUT — order timed out), ConfirmedItems []OrderItemResult, TotalAmount float64, ProcessedAt time.Time.
@dataclass(slots=True)
class OrderState:
    order_id: str
    status: str
    confirmed_items: list[OrderItemResult] = field(default_factory=list)
    total_amount: float = 0.0
    processed_at: datetime | None = None
