"""Initial native domain model scaffold generated by servicegen."""

from dataclasses import dataclass


@dataclass(slots=True)
class UnknownType:
    """Generated domain type. Add schema fields to the service specification."""

    pass
