"""Code generated by servicegen. DO NOT EDIT."""

from __future__ import annotations

import asyncio
import aiohttp
from aiohttp import web
from collections.abc import Awaitable, Callable
from dataclasses import dataclass, field
from threading import Lock
from typing import Any
import grpc
from pyservicelib_gorundebug.runtime.context.context import Context
from pyservicelib_gorundebug.runtime.environment import ServiceEnvironment
from pyservicelib_gorundebug.runtime.config.config import ServiceConfig
from .grpc_service_generated import GrpcHandlers, GrpcServer
from ..functions import (
    ProcessOrderItemSource,
    make_process_order_item_source,
    GetInventoryItemData,
    make_get_inventory_item_data,
    GetInventoryItemError,
    make_get_inventory_item_error,
)


@dataclass
class ServiceMakers:
    process_order_item_source: Callable[[Context, ServiceEnvironment], Awaitable[ProcessOrderItemSource]] = make_process_order_item_source
    get_inventory_item_data: Callable[[Context, ServiceEnvironment], Awaitable[GetInventoryItemData]] = make_get_inventory_item_data
    get_inventory_item_error: Callable[[Context, ServiceEnvironment], Awaitable[GetInventoryItemError]] = make_get_inventory_item_error
    # Infrastructure makers receive their own configuration. Business makers do not.
    http_application: Callable[[Context, ServiceEnvironment, ServiceConfig], Awaitable[web.Application]] = (
        lambda _ctx, _environment, _config: _make_http_application()
    )
    grpc_server: Callable[[Context, ServiceEnvironment, ServiceConfig, GrpcHandlers], Awaitable[GrpcServer]] = (
        lambda _ctx, _environment, config, handlers: _make_grpc_server(config, handlers)
    )


    _initialized: bool = field(default=False, init=False)

    async def init_makers(self, ctx: Context, custom_init: Callable[[Context], Awaitable[None]]) -> None:
        if not self._initialized:
            await custom_init(ctx)
            self._initialized = True

    async def init_infrastructure(self, ctx: Context, service: Any) -> None:
        group = _MakerGroup(ctx)
        calls = [
            *service._servers.maker_calls(group, service),
            *service._connectors.maker_calls(group, service),
            *service._clients.maker_calls(group, service),
        ]
        results = await asyncio.gather(*(call for _, call in calls), return_exceptions=True)
        group.context.cancel()
        group.raise_first_error()
        infrastructure: dict[str, list[Any]] = {}
        for (name, _), result in zip(calls, results):
            infrastructure.setdefault(name, []).append(result)
        service._servers.bind(infrastructure, service)
        service._connectors.bind(infrastructure, service)
        service._clients.bind(infrastructure)


async def _make_http_application() -> web.Application:
    return web.Application()
async def _make_grpc_server(
    config: ServiceConfig, handlers: GrpcHandlers
) -> GrpcServer:
    return GrpcServer(config.grpc_host, config.grpc_port, handlers)

class _MakerGroup:
    def __init__(self, parent: Context) -> None:
        self.context = parent.child()
        self._lock = Lock()
        self._first_error: BaseException | None = None

    async def invoke(
        self,
        maker: Callable[[Context, ServiceEnvironment, Any], Awaitable[Any]],
        environment: ServiceEnvironment,
        config: Any,
    ) -> Any:
        return await self.invoke_call(
            lambda: maker(self.context, environment, config)
        )

    async def invoke_call(self, maker: Callable[[], Awaitable[Any]]) -> Any:
        try:
            return await maker()
        except BaseException as error:
            with self._lock:
                if self._first_error is None:
                    self._first_error = error
                    self.context.cancel()
            raise

    def raise_first_error(self) -> None:
        if self._first_error is not None:
            raise self._first_error