"""Code generated by servicegen. DO NOT EDIT."""

from __future__ import annotations

from typing import Any
from pyservicelib_gorundebug.runtime.serde import DataclassJsonSerde, Serializer
from inventory_service.models.inventory_failure_generated import (
    InventoryFailure,
)
from model.models.order_item import (
    OrderItem,
)
from model.models.order_item_result import (
    OrderItemResult,
)


class ServiceSerdes:
    @staticmethod
    def get_serde( type_name: str) -> Serializer | None:
        if type_name == "OrderItem":
            return DataclassJsonSerde("OrderItem", OrderItem)
        if type_name == "OrderItemResult":
            return DataclassJsonSerde("OrderItemResult", OrderItemResult)
        return None


    @staticmethod
    def register(environment: Any) -> None:
        environment.register_serde("OrderItem", DataclassJsonSerde("OrderItem", OrderItem))
        environment.register_serde("OrderItemResult", DataclassJsonSerde("OrderItemResult", OrderItemResult))