"""Code generated by servicegen. DO NOT EDIT."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from datetime import timedelta
from typing import Any, Optional
import grpc

from pyservicelib_gorundebug.runtime.context.context import Context
from pyservicelib_gorundebug.runtime.serviceapp import (
    ServiceApp,
    run_shutdown_operations,
)
from pyservicelib_gorundebug.runtime.serde import DataclassJsonSerde, Serializer
from pyservicelib_gorundebug import transformation
from pyservicelib_gorundebug.datasource.grpc import grpcds as grpc_source
from .grpc_service_generated import GrpcHandlers, GrpcServer

from ..config import Config
from pyservicelib_gorundebug.runtime.environment import ServiceEnvironment
from pyservicelib_gorundebug.runtime.config.endpoint_types import GrpcEndpointConfig
from pyservicelib_gorundebug.runtime.config.stream_types import ProcessStreamConfig
from model.models.order_item import (
    OrderItem,
)
from model.models.order_item_result import (
    OrderItemResult,
)
from ..functions import (
    GetInventoryItemData,
    make_get_inventory_item_data,
    ProcessOrderItem,
    make_process_order_item,
)


@dataclass(slots=True)
class ServiceStreams:
    process_inventory_item: Any = None
    get_inventory_item_data: Any = None
    get_inventory_item_error: Any = None
    merge_inventory_result: Any = None

@dataclass(slots=True)
class ServiceMakers:
    get_inventory_item_data: Callable[[Context, ServiceEnvironment, ProcessStreamConfig], GetInventoryItemData] = (
        lambda ctx, environment, config: make_get_inventory_item_data(
            ctx, environment, config
        )
    )
    process_order_item: Callable[[Context, ServiceEnvironment, GrpcEndpointConfig], ProcessOrderItem] = (
        lambda ctx, environment, config: make_process_order_item(
            ctx, environment, config
        )
    )


@dataclass(slots=True)
class ServiceFunctions:
    get_inventory_item_data: GetInventoryItemData
    process_order_item: ProcessOrderItem


class GeneratedService(ServiceApp):
    """Generated lifecycle and graph bootstrap for Inventory Service."""

    def __init__(self) -> None:
        super().__init__()
        self._makers = ServiceMakers()
        self._functions: ServiceFunctions | None = None
        self._service_streams = ServiceStreams()
        self._transport_consumers: list[Any] = []
        self._grpc_channels: list[grpc.aio.Channel] = []

    @property
    def makers(self) -> ServiceMakers:
        return self._makers

    @property
    def functions(self) -> ServiceFunctions:
        if self._functions is None:
            raise RuntimeError("service functions are not initialized")
        return self._functions

    def get_serde(self, type_name: str) -> Optional[Serializer]:
        if type_name == "OrderItem":
            return DataclassJsonSerde("OrderItem", OrderItem)
        if type_name == "OrderItemResult":
            return DataclassJsonSerde("OrderItemResult", OrderItemResult)
        return None

    async def initialize_functions(self, ctx: Context) -> None:
        """Apply user maker overrides, construct functions, then configure them."""

        await self.custom_makers_init(ctx)
        cfg = self.config
        if not isinstance(cfg, Config):
            raise TypeError(
                "Inventory Service requires inventory_service.internal.config.Config"
            )
        named = cfg.named
        self._functions = ServiceFunctions(
            get_inventory_item_data=self._makers.get_inventory_item_data(
                ctx, self, named.streams.get_inventory_item_data
            ),
            process_order_item=self._makers.process_order_item(
                ctx, self, named.endpoints.process_order_item
            ),
        )
        await self.custom_functions_init(ctx)

    async def build_stream_graph(self, ctx: Context) -> None:
        """Construct the configured stream graph with Go-compatible semantics."""

        await self.initialize_functions(ctx)
        cfg = self.config
        if not isinstance(cfg, Config):
            raise TypeError(
                "Inventory Service requires inventory_service.internal.config.Config"
            )
        named = cfg.named
        self._service_streams.process_inventory_item = transformation.Input[OrderItem, OrderItemResult, Exception](named.streams.process_inventory_item, self)
        self._service_streams.get_inventory_item_data = transformation.Process[OrderItem, OrderItemResult, OrderItemResult](named.streams.get_inventory_item_data, self._service_streams.process_inventory_item, self.functions.get_inventory_item_data)
        self._service_streams.get_inventory_item_error = self._service_streams.get_inventory_item_data.error_stream
        self._service_streams.merge_inventory_result = transformation.Merge[OrderItemResult](named.streams.merge_inventory_result, self._service_streams.get_inventory_item_data, self._service_streams.get_inventory_item_error)
        self._service_streams.process_inventory_item.set_source(self._service_streams.merge_inventory_result)

    def bind_transports(self) -> None:
        """Bind configured endpoints to the already constructed streams."""

        cfg = self.config
        if not isinstance(cfg, Config):
            raise TypeError(
                "Inventory Service requires inventory_service.internal.config.Config"
            )
        self._transport_consumers = []
        self._grpc_channels = []
        grpc_handlers = GrpcHandlers()
        process_inventory_item_consumer, process_inventory_item_grpc_handler = grpc_source.make_grpc_no_streaming_endpoint_consumer(self._service_streams.process_inventory_item, self.functions.process_order_item)
        self._transport_consumers.append(process_inventory_item_consumer)
        grpc_handlers.process_inventory_item = process_inventory_item_grpc_handler
        self.add_component(GrpcServer(
            self.service_config.grpc_host,
            self.service_config.grpc_port,
            grpc_handlers,
        ))

    async def build_runtime(self, ctx: Context) -> None:
        await self.build_stream_graph(ctx)
        self.bind_transports()

    async def start_service(self, ctx: Context) -> None:
        await self.build_runtime(ctx)
        await self.on_start(ctx)
        await self.start(ctx)

    async def stop_service(self, ctx: Context) -> None:
        ctx = ctx.bounded(
            timedelta(milliseconds=self.service_config.shutdown_timeout)
        )

        async def close_grpc_channels() -> None:
            channels = [
                channel
                for channel in self._grpc_channels
            ]
            self._grpc_channels = []
            for channel in channels:
                await channel.close(grace=None)

        await run_shutdown_operations(
            self.log,
            ctx,
            [
                ("user_on_stop", self.on_stop(ctx)),
                ("service_runtime", self.stop(ctx)),
                ("grpc_channels", close_grpc_channels()),
            ],
        )

    async def custom_makers_init(self, ctx: Context) -> None:
        del ctx

    async def custom_functions_init(self, ctx: Context) -> None:
        del ctx

    async def on_start(self, ctx: Context) -> None:
        del ctx

    async def on_stop(self, ctx: Context) -> None:
        del ctx