services:
  analyticsservice:
    image: analyticsservice-python:latest
    build:
      target: runtime-analyticsservice
    command:
      - --config
      - /workspace/config/config.yaml
      - --overrides
      - /workspace/config/docker_overrides.yaml
    volumes: !reset []
    security_opt: !reset []
    cap_add: !reset []
    ports: !override
      - "${ANALYTICS_SERVICE_HTTP_PORT:-9093}:${ANALYTICS_SERVICE_HTTP_PORT:-9093}"
      - "${ANALYTICS_SERVICE_GRPC_PORT:-9203}:${ANALYTICS_SERVICE_GRPC_PORT:-9203}"
  automationservice:
    image: automationservice-python:latest
    build:
      target: runtime-automationservice
    command:
      - --config
      - /workspace/config/config.yaml
      - --overrides
      - /workspace/config/docker_overrides.yaml
    volumes: !reset []
    security_opt: !reset []
    cap_add: !reset []
    ports: !override
      - "${AUTOMATION_SERVICE_HTTP_PORT:-9094}:${AUTOMATION_SERVICE_HTTP_PORT:-9094}"
      - "${AUTOMATION_SERVICE_GRPC_PORT:-9204}:${AUTOMATION_SERVICE_GRPC_PORT:-9204}"
  inventoryservice:
    image: inventoryservice-python:latest
    build:
      target: runtime-inventoryservice
    command:
      - --config
      - /workspace/config/config.yaml
      - --overrides
      - /workspace/config/docker_overrides.yaml
    volumes: !reset []
    security_opt: !reset []
    cap_add: !reset []
    ports: !override
      - "${INVENTORY_SERVICE_HTTP_PORT:-9092}:${INVENTORY_SERVICE_HTTP_PORT:-9092}"
      - "${INVENTORY_SERVICE_GRPC_PORT:-9202}:${INVENTORY_SERVICE_GRPC_PORT:-9202}"
  orderservice:
    image: orderservice-python:latest
    build:
      target: runtime-orderservice
    command:
      - --config
      - /workspace/config/config.yaml
      - --overrides
      - /workspace/config/docker_overrides.yaml
    volumes: !reset []
    security_opt: !reset []
    cap_add: !reset []
    ports: !override
      - "${ORDER_SERVICE_HTTP_PORT:-9091}:${ORDER_SERVICE_HTTP_PORT:-9091}"
      - "${ORDER_SERVICE_GRPC_PORT:-9201}:${ORDER_SERVICE_GRPC_PORT:-9201}"