# Code generated by servicegen. DO NOT EDIT.
-include .env
export

PROJECT_DIR := $(abspath .)
BIN_DIR := $(PROJECT_DIR)/bin
TOOLS_DIR := $(PROJECT_DIR)/tools
GOPRIVATE := github.com
MODULE_VERSION := v0.0.1
OS := $(shell uname -s)
ARCH := $(shell uname -m)

LANG_BUILD_TARGETS :=
LANG_TEST_TARGETS :=
LANG_LINT_TARGETS :=
LANG_LINT_FIX_TARGETS :=
LANG_FMT_TARGETS :=
LANG_GEN_TARGETS :=
LANG_CLEAN_TARGETS :=
LANG_TOOL_TARGETS :=
LANG_DOCKER_BUILD_TARGETS :=
LANG_INTEGRATION_TARGETS :=
include make.python.generated.mk

ACT_VERSION := v0.2.74
ACT := $(TOOLS_DIR)/act
GH_VERSION := v2.67.0
GH := $(TOOLS_DIR)/gh
GLAB_VERSION := v1.50.0
GLAB := $(TOOLS_DIR)/glab

.DEFAULT_GOAL := all

.PHONY: all init git-init build test lint lint-fix fmt gen clean ci tools \
	run integration-test act docker-build docker-build-local docker-up \
	docker-down docker-restart docker-clean grafana-dashboards merge help \
	git-push git-delete git-push-inventory_service_api git-delete-inventory_service_api git-push-model git-delete-model git-push-order_service_api git-delete-order_service_api git-push-inventoryservice git-delete-inventoryservice git-push-orderservice git-delete-orderservice git-push-project git-delete-project

all: build ## Build all services (default)

init: tools gen fmt ## First-time setup: install tools, generate, and format

git-init: git-push ## Publish repositories and synchronize dependencies

build: $(LANG_BUILD_TARGETS) ## Build all services

test: $(LANG_TEST_TARGETS) ## Run all tests

lint: $(LANG_LINT_TARGETS) ## Run all language linters and type checks

lint-fix: $(LANG_LINT_FIX_TARGETS) ## Auto-fix lint and formatting issues

fmt: $(LANG_FMT_TARGETS) ## Format all source code

gen: $(LANG_GEN_TARGETS) ## Generate protobuf, OpenAPI, and transport code

clean: $(LANG_CLEAN_TARGETS) ## Remove build artifacts

tools: common-tools $(LANG_TOOL_TARGETS) ## Download or verify all required tools

ci: tools build test lint ## Run the full CI pipeline

integration-test: $(LANG_INTEGRATION_TARGETS) ## Run all integration tests

run: docker-up ## Run all services through Docker Compose

docker-build: $(LANG_DOCKER_BUILD_TARGETS) ## Build all service Docker images

docker-build-local: docker-build ## Build Docker images for local development

grafana-dashboards: ## Generate Grafana dashboards for all services
	@cd inventoryservice/grafana && bash generate.generated.sh
	@cd orderservice/grafana && bash generate.generated.sh

docker-up: docker-build grafana-dashboards ## Start all services through Docker Compose
	@docker compose up -d

docker-down: ## Stop all services
	@docker compose down

docker-restart: docker-down docker-up ## Restart all services

docker-clean: docker-down ## Stop services and remove persistent volumes
	@docker compose down --volumes --remove-orphans

act: $(ACT) ## Run GitHub Actions locally through act
	@$(ACT) push -W .github/workflows --env "GITHUB_TOKEN=$$($(GH) auth token)"

merge: ## Merge a generated archive (usage: make merge ARCHIVE=/path/archive.zip)
	@bash scripts/merge.generated.sh "$(ARCHIVE)"

$(ACT):
	@mkdir -p "$(TOOLS_DIR)"
	@echo "Downloading act $(ACT_VERSION)..."
	@curl -sSL "https://github.com/nektos/act/releases/download/$(ACT_VERSION)/act_$(OS)_$(ARCH).tar.gz" | tar -xz -C "$(TOOLS_DIR)" act

$(GH):
	@mkdir -p "$(TOOLS_DIR)"
	@echo "Downloading gh $(GH_VERSION)..."
	@_os=$$(uname -s | sed 's/Darwin/macOS/;s/Linux/linux/'); \
	_arch=$$(uname -m | sed 's/x86_64/amd64/'); \
	_ver=$$(echo "$(GH_VERSION)" | sed 's/v//'); \
	if [ "$$(uname -s)" = "Darwin" ]; then \
	  curl -sSL "https://github.com/cli/cli/releases/download/$(GH_VERSION)/gh_$${_ver}_$${_os}_$${_arch}.zip" -o /tmp/gh.zip; \
	  rm -rf /tmp/gh_extract; \
	  unzip -q /tmp/gh.zip "gh_$${_ver}_$${_os}_$${_arch}/bin/gh" -d /tmp/gh_extract; \
	  mv /tmp/gh_extract/gh_$${_ver}_$${_os}_$${_arch}/bin/gh "$(GH)"; \
	  rm -rf /tmp/gh.zip /tmp/gh_extract; \
	else \
	  curl -sSL "https://github.com/cli/cli/releases/download/$(GH_VERSION)/gh_$${_ver}_$${_os}_$${_arch}.tar.gz" | tar -xz -C /tmp; \
	  mv /tmp/gh_$${_ver}_$${_os}_$${_arch}/bin/gh "$(GH)"; \
	  rm -rf /tmp/gh_$${_ver}_$${_os}_$${_arch}; \
	fi
	@chmod +x "$(GH)"

$(GLAB):
	@mkdir -p "$(TOOLS_DIR)"
	@echo "Downloading glab $(GLAB_VERSION)..."
	@_os=$$(uname -s | tr '[:upper:]' '[:lower:]'); \
	_arch=$$(uname -m | sed 's/amd64/x86_64/'); \
	_ver=$$(echo "$(GLAB_VERSION)" | sed 's/v//'); \
	curl -sSL "https://gitlab.com/gitlab-org/cli/-/releases/$(GLAB_VERSION)/downloads/glab_$${_ver}_$${_os}_$${_arch}.tar.gz" | \
	  tar -xz -C "$(TOOLS_DIR)" --strip-components=1 bin/glab
	@chmod +x "$(GLAB)"

common-tools: $(ACT) $(GH) $(GLAB)

define git-push-dir
	@set -eu; \
	host="$(3)"; \
	repo="$(4)"; \
	if [ "$$host" = "gitlab.com" ]; then \
	  $(GLAB) repo create $$repo --private 2>/dev/null || true; \
	else \
	  $(GH) repo create $$repo --private 2>/dev/null || true; \
	fi; \
	tmp=$$(mktemp -d); \
	trap 'rm -rf "$$tmp"' EXIT INT TERM; \
	stage="$$tmp/stage"; \
	work="$$tmp/repository"; \
	mkdir -p "$$stage"; \
	if [ "$(5)" = "cpp-service" ]; then \
	  ./scripts/package-cpp-service.generated.sh "./$(1)" "$$stage"; \
	elif [ "$(5)" = "python-service" ]; then \
	  ./scripts/package-python-service.generated.sh "./$(1)" "$$stage"; \
	else \
	  cp -r ./$(1)/. "$$stage/"; \
	fi; \
	rm -rf "$$stage/.git"; \
	git clone -q "git@$$host:$$repo.git" "$$work"; \
	git -C "$$work" rm -rq --ignore-unmatch .; \
	cp -r "$$stage/." "$$work/"; \
	git -C "$$work" add -A; \
	if ! git -C "$$work" diff --cached --quiet; then \
	  git -C "$$work" -c user.email="local@dev" -c user.name="local" commit -q -m "release $(2)"; \
	fi; \
	git -C "$$work" tag $(2); \
	git -C "$$work" push --atomic origin HEAD:main refs/tags/$(2)
endef

git-push-inventory_service_api: $(GH) ## Push module inventory_service_api to github.com/gorundebug/pyexample-inventory-service-api
	$(call git-push-dir,inventory_service_api,$(MODULE_VERSION),github.com,gorundebug/pyexample-inventory-service-api)

git-delete-inventory_service_api: $(GH) ## Delete module inventory_service_api from remote
	@$(GH) repo delete gorundebug/pyexample-inventory-service-api --yes 2>/dev/null || true


git-push-model: $(GH) ## Push module model to github.com/gorundebug/pyexample-model
	$(call git-push-dir,model,$(MODULE_VERSION),github.com,gorundebug/pyexample-model)

git-delete-model: $(GH) ## Delete module model from remote
	@$(GH) repo delete gorundebug/pyexample-model --yes 2>/dev/null || true


git-push-order_service_api: $(GH) ## Push module order_service_api to github.com/gorundebug/pyexample-order-service-api
	$(call git-push-dir,order_service_api,$(MODULE_VERSION),github.com,gorundebug/pyexample-order-service-api)

git-delete-order_service_api: $(GH) ## Delete module order_service_api from remote
	@$(GH) repo delete gorundebug/pyexample-order-service-api --yes 2>/dev/null || true


git-push-inventoryservice: $(GH) ## Push service Inventory Service to github.com/gorundebug/pyexample-inventoryservice
	$(call git-push-dir,inventoryservice,$(MODULE_VERSION),github.com,gorundebug/pyexample-inventoryservice,python-service)

git-delete-inventoryservice: $(GH) ## Delete service Inventory Service from remote
	@$(GH) repo delete gorundebug/pyexample-inventoryservice --yes 2>/dev/null || true


git-push-orderservice: $(GH) ## Push service Order Service to github.com/gorundebug/pyexample-orderservice
	$(call git-push-dir,orderservice,$(MODULE_VERSION),github.com,gorundebug/pyexample-orderservice,python-service)

git-delete-orderservice: $(GH) ## Delete service Order Service from remote
	@$(GH) repo delete gorundebug/pyexample-orderservice --yes 2>/dev/null || true


git-push-project: $(GH) ## Push project root to github.com/gorundebug/pyexample
	$(call git-push-dir,.,$(MODULE_VERSION),github.com,gorundebug/pyexample)

git-delete-project: $(GH) ## Delete project repository github.com/gorundebug/pyexample
	@$(GH) repo delete gorundebug/pyexample --yes 2>/dev/null || true


git-push: $(GH) ## Push all modules, services, and project repositories
	@$(GH) auth status >/dev/null 2>&1 || { echo "ERROR: authenticate first with: $(GH) auth login"; exit 1; }

	@$(MAKE) git-push-inventory_service_api git-push-model git-push-order_service_api git-push-inventoryservice git-push-orderservice git-push-project

git-delete: $(GH) ## Delete all generated remote repositories
	@$(MAKE) git-delete-inventory_service_api git-delete-model git-delete-order_service_api git-delete-inventoryservice git-delete-orderservice git-delete-project

help: ## Show this help
	@grep -hE '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-32s %s\n", $$1, $$2}'