# Code generated by servicegen. DO NOT EDIT.

PYTHON_SERVICES := inventoryservice orderservice

LANG_BUILD_TARGETS += python-build
LANG_TEST_TARGETS += python-test
LANG_LINT_TARGETS += python-lint
LANG_LINT_FIX_TARGETS += python-format
LANG_FMT_TARGETS += python-format
LANG_GEN_TARGETS += python-gen
LANG_CLEAN_TARGETS += python-clean
LANG_TOOL_TARGETS += python-tools
LANG_DOCKER_BUILD_TARGETS += python-docker-build
LANG_INTEGRATION_TARGETS += python-integration-test

.PHONY: python-init python-build python-test python-lint python-format \
	python-gen python-clean python-tools python-docker-build \
	python-integration-test

python-tools: ## Install the Python workspace and development tools with uv
	@./scripts/python/setup.sh

python-init: python-tools ## Initialize the Python workspace

python-build: python-tools ## Build all Python workspace packages
	@uv build --all-packages

python-test: python-tools ## Run all Python tests
	@./scripts/python/test.sh

python-lint: python-tools ## Run mypy and Ruff checks
	@./scripts/python/typecheck.sh

python-format: python-tools ## Format and auto-fix Python sources
	@./scripts/python/format.generated.sh

python-gen: python-tools ## Generate Python protobuf and OpenAPI code
	@./scripts/python/generate.sh

python-docker-build: ## Build Python service Docker images
	@docker compose build $(PYTHON_SERVICES)

python-integration-test: ## Run Python integration tests
	@./scripts/python/integration-test.sh

python-clean: ## Remove Python build, cache, and virtualenv artifacts
	@rm -rf .venv dist
	@find . -type d \( -name __pycache__ -o -name .mypy_cache -o -name .pytest_cache -o -name .ruff_cache \) -prune -exec rm -rf {} +
	@find . -type d \( -name dist -o -name build \) -prune -exec rm -rf {} +
