"""Code generated by servicegen. DO NOT EDIT."""


import os
from dataclasses import dataclass
from typing import Any, Final

from pyservicelib_gorundebug.api.models.data_connector_implementation import (
    DataConnectorImplementation,
)
from pyservicelib_gorundebug.api.models.call_semantics import CallSemantics
from pyservicelib_gorundebug.api.models.data_connector_type import (
    DataConnectorType,
)
from pyservicelib_gorundebug.api.models.data_type import DataType
from pyservicelib_gorundebug.api.models.environment import Environment
from pyservicelib_gorundebug.api.models.grpc_method_type import GrpcMethodType
from pyservicelib_gorundebug.api.models.http_method_type import HTTPMethodType
from pyservicelib_gorundebug.api.models.join_storage_type import JoinStorageType
from pyservicelib_gorundebug.api.models.join_type import JoinType
from pyservicelib_gorundebug.api.models.kafka_sasl_mechanism import KafkaSaslMechanism
from pyservicelib_gorundebug.api.models.kafka_security_protocol import KafkaSecurityProtocol
from pyservicelib_gorundebug.api.models.log_level import LogLevel
from pyservicelib_gorundebug.api.models.process_pattern import ProcessPattern
from pyservicelib_gorundebug.api.models.programming_language import (
    ProgrammingLanguage,
)
from pyservicelib_gorundebug.api.models.transformation_type import (
    TransformationType,
)
from pyservicelib_gorundebug.api.models.type_definition_format import (
    TypeDefinitionFormat,
)
from pyservicelib_gorundebug.runtime.config.config import (
    DataConnectorConfig,
    EndpointConfig,
    LinkConfig,
    ModuleConfig,
    PoolConfig,
    ProjectSettings,
    ServiceAppConfig,
    ServiceConfig,
    StreamConfig,
    TypeConfig,
)
from pyservicelib_gorundebug.runtime.config.dataconnector_types import (
    CustomDataConnectorConfig,
    GrpcDataConnectorConfig,
    HttpDataConnectorConfig,
    KafkaDataConnectorConfig,
)
from pyservicelib_gorundebug.runtime.config.endpoint_types import (
    CustomEndpointConfig,
    GrpcEndpointConfig,
    HttpEndpointConfig,
    KafkaEndpointConfig,
)

from pyservicelib_gorundebug.runtime.config.stream_types import (
    InputStreamConfig,
    ProcessStreamConfig,
)


_DEFAULT_CONFIG: dict[str, Any] = {
    "settings": ProjectSettings(moduleVersion="v0.2.5", name="Example", repoPath="github.com/gorundebug/pyexample", ),
    "services": { "analyticsService": ServiceConfig(color="#05ABF7", defaultCallSemantics=CallSemantics(2), defaultGrpcTimeout=0, environment=Environment(""), golangVersion="1.25.4", grpcHost="0.0.0.0", grpcPort=9203, httpHost="0.0.0.0", httpPort=9093, id=1, kubernetesWorkloadType="Deployment", livenessHandler="health/live", metricsHandler="metrics", modulePath="github.com/gorundebug/pyexample-analyticsservice", name="Analytics Service", programmingLanguage=ProgrammingLanguage(3), readinessHandler="health/ready", shutdownTimeout=30000, startupHandler="health/startup", statusHandler="status", ), },
    "streams": { "consumeOrderProcessed": StreamConfig(id=1, idEndpoint=2, idService=1, idSource=2, name="Consume Order Processed", pipeline="analytics", type=TransformationType(1), valueType="OrderProcessed", xPos=-1190, yPos=-205, ), "countOrderProcessed": StreamConfig(functionDescription="Count successful and unsuccessful orders independently, then return the event unchanged.\n", functionInitializerGroup="", functionModule="", functionName="CountOrderProcessed", functionPackage="", id=2, idService=1, idSource=1, name="Count Order Processed", pipeline="analytics", type=TransformationType(6), valueType="OrderProcessed", xPos=-1390, yPos=-19, ), },
    "dataConnectors": { "orderEvents": DataConnectorConfig(brokers="redpanda:9092", id=2, implementation="aiokafka", name="Order Events", password="", saslMechanism="SCRAM-SHA-512", securityProtocol="PLAINTEXT", type=DataConnectorType(3), typeScriptImplementation="confluent/kafka-javascript", username="", version="2.8.0", ), },
    "endpoints": { "orderProcessed": EndpointConfig(consumerGroup="analytics-service", createTopic=True, enabled=True, functionDescription="Exchange OrderProcessed events keyed by order ID.\nProducers include the final status, processing time, total and confirmed item counts, and a failure reason for unsuccessful orders.\nConsumers decode the event and mark its Kafka message processed only after the pipeline handles it successfully.\n", functionInitializerGroup="", functionName="OrderProcessedEndpoint", functionPackage="", id=2, idDataConnector=2, name="Order Processed", partitions=1, publicFunction=False, replicationFactor=1, topic="order-processed", ), },
    "pools": { },
    "links": { },
    "modules": { "inventoryServiceApi": ModuleConfig(golangVersion="1.25.4", modulePath="github.com/gorundebug/pyexample-inventory-service-api", name="inventory_service_api", ), "model": ModuleConfig(golangVersion="1.25.4", modulePath="github.com/gorundebug/pyexample-model", name="model", ), "orderServiceApi": ModuleConfig(golangVersion="1.25.4", modulePath="github.com/gorundebug/pyexample-order-service-api", name="order_service_api", ), },
    "types": { "orderProcessed": TypeConfig(definitionFormat=TypeDefinitionFormat(1), description="Final order-processing event. Fields: OrderID string, Status string, ProcessedAt time.Time, TotalItems int, ConfirmedItems int, FailureReason string.", module="model", name="OrderProcessed", package="", publicType=False, transferByValue=False, type=DataType.struct, ), },
}

_ENVIRONMENT_VARIABLES: tuple[tuple[str, tuple[str, ...], str], ...] = (
    ("ANALYTICS_SERVICE_DEFAULT_GRPC_TIMEOUT", ("services", "analyticsService", "defaultGrpcTimeout", ), "int"),
    ("ANALYTICS_SERVICE_ENVIRONMENT", ("services", "analyticsService", "environment", ), "api.Environment"),
    ("ANALYTICS_SERVICE_GRPC_HOST", ("services", "analyticsService", "grpcHost", ), "string"),
    ("ANALYTICS_SERVICE_GRPC_PORT", ("services", "analyticsService", "grpcPort", ), "int"),
    ("ANALYTICS_SERVICE_HTTP_HOST", ("services", "analyticsService", "httpHost", ), "string"),
    ("ANALYTICS_SERVICE_HTTP_PORT", ("services", "analyticsService", "httpPort", ), "int"),
    ("ORDER_EVENTS_BROKERS", ("dataConnectors", "orderEvents", "brokers", ), "string"),
    ("ORDER_EVENTS_PASSWORD", ("dataConnectors", "orderEvents", "password", ), "string"),
    ("ORDER_EVENTS_SASL_MECHANISM", ("dataConnectors", "orderEvents", "saslMechanism", ), "api.KafkaSaslMechanism"),
    ("ORDER_EVENTS_SECURITY_PROTOCOL", ("dataConnectors", "orderEvents", "securityProtocol", ), "api.KafkaSecurityProtocol"),
    ("ORDER_EVENTS_USERNAME", ("dataConnectors", "orderEvents", "username", ), "string"),
    ("ORDER_PROCESSED_ENABLED", ("endpoints", "orderProcessed", "enabled", ), "bool"),
)


class ServiceIds:
    ANALYTICS_SERVICE: Final[int] = 1


class StreamIds:
    CONSUME_ORDER_PROCESSED: Final[int] = 1
    COUNT_ORDER_PROCESSED: Final[int] = 2


class EndpointIds:
    ORDER_PROCESSED: Final[int] = 2


class DataConnectorIds:
    ORDER_EVENTS: Final[int] = 2


@dataclass(frozen=True, slots=True)
class Streams:
    consume_order_processed: InputStreamConfig
    count_order_processed: ProcessStreamConfig


@dataclass(frozen=True, slots=True)
class Endpoints:
    order_processed: KafkaEndpointConfig


@dataclass(frozen=True, slots=True)
class DataConnectors:
    order_events: KafkaDataConnectorConfig


@dataclass(frozen=True, slots=True)
class Services:
    analytics_service: ServiceConfig


@dataclass(frozen=True, slots=True)
class Pools:
    pass


@dataclass(frozen=True, slots=True)
class Modules:
    inventory_service_api: ModuleConfig
    model: ModuleConfig
    order_service_api: ModuleConfig


@dataclass(frozen=True, slots=True)
class NamedConfig:
    streams: Streams
    endpoints: Endpoints
    data_connectors: DataConnectors
    services: Services
    pools: Pools
    modules: Modules


def _environment_value(name: str, kind: str) -> Any | None:
    value = os.environ.get(name)
    if value is None:
        return None
    try:
        if kind == "int":
            return int(value)
        if kind == "float64":
            return float(value)
        if kind == "bool":
            normalized = value.strip().lower()
            if normalized in {"1", "true", "yes", "on"}:
                return True
            if normalized in {"0", "false", "no", "off"}:
                return False
            raise ValueError("expected a boolean")
        if kind == "[]int":
            return [int(item.strip()) for item in value.split(",") if item.strip()]
        if kind == "[]string":
            return [item.strip() for item in value.split(",") if item.strip()]
        return value
    except ValueError as error:
        raise ValueError(f"invalid {name}: {error}") from error


def _set_config_path(config: dict[str, Any], path: tuple[str, ...], value: Any) -> None:
    current = config
    for part in path[:-1]:
        child = current.get(part)
        if not isinstance(child, dict):
            raise TypeError(f"config path '{'.'.join(path)}' is not a mapping")
        current = child
    current[path[-1]] = value


class GeneratedConfig(ServiceAppConfig):
    """Generated typed view over the runtime graph configuration."""

    @classmethod
    def _load_config(cls, obj: dict[str, Any]) -> dict[str, Any]:
        def values(name: str) -> list[dict[str, Any]]:
            section = normalized.get(name, {})
            if isinstance(section, dict):
                return list(section.values())
            if isinstance(section, list):
                return section
            raise TypeError(f"config section '{name}' must be a mapping or list")

        defaults = _dump_default_config(_DEFAULT_CONFIG)
        normalized = _deep_merge(defaults, obj)
        for name, path, kind in _ENVIRONMENT_VARIABLES:
            if (value := _environment_value(name, kind)) is not None:
                _set_config_path(normalized, path, value)
        for name in ("services", "streams", "links", "types", "pools", "modules", "endpoints"):
            normalized[name] = values(name)
        normalized["dataConnectors"] = values("dataConnectors")
        return super()._load_config(normalized)

    @property
    def named(self) -> NamedConfig:
        return NamedConfig(
            streams=Streams(
                consume_order_processed=InputStreamConfig(
                    self.get_stream_config_by_id(StreamIds.CONSUME_ORDER_PROCESSED)
                ),
                count_order_processed=ProcessStreamConfig(
                    self.get_stream_config_by_id(StreamIds.COUNT_ORDER_PROCESSED)
                ),
            ),
            endpoints=Endpoints(
                order_processed=_kafka_endpoint(
                    self.get_endpoint_config_by_id(EndpointIds.ORDER_PROCESSED)
                ),
            ),
            data_connectors=DataConnectors(
                order_events=_kafka_data_connector(
                    self.get_data_connector_by_id(
                        DataConnectorIds.ORDER_EVENTS
                    )
                ),
            ),
            services=Services(
                analytics_service=self.get_service_config_by_id(
                    ServiceIds.ANALYTICS_SERVICE
                ),
            ),
            pools=Pools(
            ),
            modules=Modules(
                inventory_service_api=_require_module(
                    self.runtime_config.modules.get("inventory_service_api"),
                    "inventory_service_api",
                ),
                model=_require_module(
                    self.runtime_config.modules.get("model"),
                    "model",
                ),
                order_service_api=_require_module(
                    self.runtime_config.modules.get("order_service_api"),
                    "order_service_api",
                ),
            ),
        )


def _implementation(config: DataConnectorConfig) -> DataConnectorImplementation:
    if config.implementation is None:
        raise ValueError(f"data connector '{config.name}' has no implementation")
    return DataConnectorImplementation(config.implementation)


def _http_data_connector(config: DataConnectorConfig) -> HttpDataConnectorConfig:
    return HttpDataConnectorConfig(
        id=config.id,
        name=config.name,
        implementation=_implementation(config),
        host=config.host,
        port=config.port,
        module=config.module,
        use_dedicated_listener=config.use_dedicated_listener or False,
        properties=config.properties,
    )


def _grpc_data_connector(config: DataConnectorConfig) -> GrpcDataConnectorConfig:
    return GrpcDataConnectorConfig(
        id=config.id,
        name=config.name,
        implementation=_implementation(config),
        address=config.address,
        module=config.module,
        connections_count=config.connections_count or 1,
        properties=config.properties,
    )


def _kafka_data_connector(config: DataConnectorConfig) -> KafkaDataConnectorConfig:
    return KafkaDataConnectorConfig(
        id=config.id,
        name=config.name,
        implementation=_implementation(config),
        brokers=config.brokers,
        version=config.version,
        dial_timeout=config.dial_timeout or 0.0,
        use_partitioner=config.use_partitioner or False,
        async_=getattr(config, "async_", False) or False,
        security_protocol=config.security_protocol or KafkaSecurityProtocol.PLAINTEXT,
        sasl_mechanism=config.sasl_mechanism or KafkaSaslMechanism.PLAIN,
        username=config.username,
        password=config.password,
        properties=config.properties,
    )


def _custom_data_connector(config: DataConnectorConfig) -> CustomDataConnectorConfig:
    return CustomDataConnectorConfig(
        id=config.id,
        name=config.name,
        implementation=_implementation(config),
        properties=config.properties,
    )


def _http_endpoint(config: EndpointConfig) -> HttpEndpointConfig:
    return HttpEndpointConfig(
        id=config.id,
        name=config.name,
        id_data_connector=config.id_data_connector,
        http_method_type=config.http_method_type,
        path=config.path,
        function_name=config.function_name,
        function_package=config.function_package,
        public_function=config.public_function or False,
        function_description=config.function_description,
        function_initializer_group=config.function_initializer_group,
        function_module=config.function_module,
        properties=config.properties,
    )


def _grpc_endpoint(config: EndpointConfig) -> GrpcEndpointConfig:
    return GrpcEndpointConfig(
        id=config.id,
        name=config.name,
        id_data_connector=config.id_data_connector,
        grpc_method_type=config.grpc_method_type,
        method_name=config.method_name,
        function_name=config.function_name,
        function_package=config.function_package,
        public_function=config.public_function or False,
        function_description=config.function_description,
        function_initializer_group=config.function_initializer_group,
        function_module=config.function_module,
        properties=config.properties,
    )


def _kafka_endpoint(config: EndpointConfig) -> KafkaEndpointConfig:
    return KafkaEndpointConfig(
        id=config.id,
        name=config.name,
        id_data_connector=config.id_data_connector,
        enabled=config.enabled,
        topic=config.topic,
        consumer_group=config.consumer_group,
        create_topic=config.create_topic or False,
        partitions=config.partitions or 0,
        replication_factor=config.replication_factor or 0,
        function_name=config.function_name,
        function_package=config.function_package,
        public_function=config.public_function or False,
        function_description=config.function_description,
        function_initializer_group=config.function_initializer_group,
        function_module=config.function_module,
        properties=config.properties,
    )


def _custom_endpoint(config: EndpointConfig) -> CustomEndpointConfig:
    return CustomEndpointConfig(
        id=config.id,
        name=config.name,
        id_data_connector=config.id_data_connector,
        function_name=config.function_name,
        function_package=config.function_package,
        public_function=config.public_function or False,
        function_description=config.function_description,
        function_initializer_group=config.function_initializer_group,
        function_module=config.function_module,
        properties=config.properties,
    )


def _require_pool(config: PoolConfig | None, name: str) -> PoolConfig:
    if config is None:
        raise KeyError(f"pool '{name}' is missing from service config")
    return config


def _require_module(config: ModuleConfig | None, name: str) -> ModuleConfig:
    if config is None:
        raise KeyError(f"module '{name}' is missing from service config")
    return config


def _deep_merge(
    defaults: dict[str, Any],
    overrides: dict[str, Any],
) -> dict[str, Any]:
    result = dict(defaults)
    for key, override in overrides.items():
        current = result.get(key)
        if isinstance(current, dict) and isinstance(override, dict):
            result[key] = _deep_merge(current, override)
        else:
            result[key] = override
    return result


def _dump_default_config(value: Any) -> Any:
    if hasattr(value, "model_dump"):
        return value.model_dump(by_alias=True, exclude_none=True)
    if isinstance(value, dict):
        return {
            key: _dump_default_config(child)
            for key, child in value.items()
        }
    if isinstance(value, list):
        return [_dump_default_config(child) for child in value]
    return value