"""Code generated by servicegen. DO NOT EDIT."""


import os
from dataclasses import dataclass
from typing import Any, Final, Self

from pyservicelib_gorundebug.api.models.data_connector_implementation import (
    DataConnectorImplementation,
)
from pyservicelib_gorundebug.api.models.call_semantics import CallSemantics
from pyservicelib_gorundebug.api.models.data_connector_type import (
    DataConnectorType,
)
from pyservicelib_gorundebug.api.models.data_type import DataType
from pyservicelib_gorundebug.api.models.environment import Environment
from pyservicelib_gorundebug.api.models.grpc_method_type import GrpcMethodType
from pyservicelib_gorundebug.api.models.http_method_type import HTTPMethodType
from pyservicelib_gorundebug.api.models.join_storage_type import JoinStorageType
from pyservicelib_gorundebug.api.models.join_type import JoinType
from pyservicelib_gorundebug.api.models.kafka_sasl_mechanism import KafkaSaslMechanism
from pyservicelib_gorundebug.api.models.kafka_security_protocol import KafkaSecurityProtocol
from pyservicelib_gorundebug.api.models.log_level import LogLevel
from pyservicelib_gorundebug.api.models.kubernetes_workload_type import (
    KubernetesWorkloadType,
)
from pyservicelib_gorundebug.api.models.process_pattern import ProcessPattern
from pyservicelib_gorundebug.api.models.schedule_missed_run_policy import (
    ScheduleMissedRunPolicy,
)
from pyservicelib_gorundebug.api.models.schedule_overlap_policy import (
    ScheduleOverlapPolicy,
)
from pyservicelib_gorundebug.api.models.programming_language import (
    ProgrammingLanguage,
)
from pyservicelib_gorundebug.api.models.transformation_type import (
    TransformationType,
)
from pyservicelib_gorundebug.api.models.type_definition_format import (
    TypeDefinitionFormat,
)
from pyservicelib_gorundebug.runtime.config.config import (
    DataConnectorConfig,
    EndpointConfig,
    LinkConfig,
    ModuleConfig,
    PoolConfig,
    ProjectSettings,
    ServiceAppConfig,
    ServiceConfig,
    StreamConfig,
    TypeConfig,
)
from pyservicelib_gorundebug.runtime.config.dataconnector_types import (
    CronDataConnectorConfig,
    CustomDataConnectorConfig,
    GrpcDataConnectorConfig,
    HttpDataConnectorConfig,
    KafkaDataConnectorConfig,
    TemporalDataConnectorConfig,
)
from pyservicelib_gorundebug.runtime.config.endpoint_types import (
    CronEndpointConfig,
    CustomEndpointConfig,
    GrpcEndpointConfig,
    HttpEndpointConfig,
    KafkaEndpointConfig,
    TemporalEndpointConfig,
)
from pyservicelib_gorundebug.api.models.temporal_execution_type import (
    TemporalExecutionType,
)

from pyservicelib_gorundebug.runtime.config.stream_types import (
    InputStreamConfig,
    MergeStreamConfig,
    ProcessStreamConfig,
)


_DEFAULT_CONFIG: dict[str, Any] = {
    "settings": ProjectSettings(moduleVersion="v0.2.35", name="Example", repoPath="github.com/gorundebug/pyexample", ),
    "services": { "inventoryService": ServiceConfig(color="#6800FF", defaultCallSemantics=CallSemantics(2), defaultGrpcTimeout=0, environment=Environment(""), golangVersion="1.25.4", grpcHost="0.0.0.0", grpcPort=9202, httpHost="0.0.0.0", httpPort=9092, id=3, kubernetesWorkloadType=KubernetesWorkloadType("Deployment"), livenessHandler="health/live", metricsHandler="metrics", modulePath="github.com/gorundebug/pyexample-inventoryservice", name="Inventory Service", programmingLanguage=ProgrammingLanguage(3), readinessHandler="health/ready", shutdownTimeout=30000, startupHandler="health/startup", statusHandler="status", ), },
    "streams": { "getInventoryItemData": StreamConfig(functionDescription="Reserve the requested quantity without allowing concurrent orders to overdraw stock.\nOn success, return CONFIRMED with the requested quantity available. Otherwise return OUT_OF_STOCK with the current available quantity.\nPreserve the order and item identity, requested quantity, and unit price.\nThe example starts with SKU-001: 100, SKU-002: 50, and SKU-003: 25.\n", functionInitializerGroup="", functionModule="", functionName="GetInventoryItemData", functionPackage="inventoryItem", id=42, idService=3, idSource=45, name="Get Inventory Item Data", pipeline="inventoryItem", type=TransformationType(6), valueType="OrderItemResult", xPos=527, yPos=-562, ), "mergeInventoryResult": StreamConfig(id=44, idService=3, idSource=0, idSources=[42, 43], name="Merge Inventory Result", pipeline="inventoryItem", type=TransformationType(10), xPos=542, yPos=33, ), "processInventoryItem": StreamConfig(id=45, idEndpoint=1, idService=3, idSource=44, name="Process Inventory Item ", pipeline="inventoryItem", type=TransformationType(1), valueType="OrderItem", xPos=250, yPos=-400, ), },
    "dataConnectors": { "inventoryServiceApi": DataConnectorConfig(address="dns:///localhost:9202", connectionsCount=1, id=1, implementation="google/grpc", module="inventory_service_api", name="Inventory Service API", type=DataConnectorType(2), ), },
    "endpoints": { "processOrderItem": EndpointConfig(functionDescription="Reserve inventory for one order item using its order ID, item ID, SKU, and quantity.\nReturn the available quantity, reservation outcome, and status. The caller combines this response with the original identity, requested quantity, and unit price.\nIf the inventory call fails, the caller returns a non-reserved PROCESSING_ERROR result with the failure message.\n", functionInitializerGroup="", functionName="ProcessOrderItem", functionPackage="endpoint", grpcMethodType=GrpcMethodType(1), id=1, idDataConnector=1, methodName="ProcessOrderItem", name="Process Order Item", publicFunction=False, ), },
    "pools": { "inventoryPriorityWorkers": PoolConfig(executorsCount=2, name="Inventory Priority Workers", ), },
    "links": { "getInventoryItemDataToMergeInventoryResult": LinkConfig(callSemantics=CallSemantics(2), var_from=42, to=44, ), "processInventoryItemToGetInventoryItemData": LinkConfig(callSemantics=CallSemantics(2), var_from=45, poolName="Inventory Priority Workers", priority=10, to=42, ), },
    "modules": { "inventoryServiceApi": ModuleConfig(golangVersion="1.25.4", modulePath="github.com/gorundebug/pyexample-inventory-service-api", name="inventory_service_api", ), "model": ModuleConfig(golangVersion="1.25.4", modulePath="github.com/gorundebug/pyexample-model", name="model", ), "orderServiceApi": ModuleConfig(golangVersion="1.25.4", modulePath="github.com/gorundebug/pyexample-order-service-api", name="order_service_api", ), },
    "types": { "orderItem": TypeConfig(definitionFormat=TypeDefinitionFormat(1), description="A single line item within an order. Fields: OrderID string, ItemID string, SKU string, Quantity int.", module="model", name="OrderItem", package="", publicType=False, transferByValue=False, type=DataType.struct, ), "orderItemResult": TypeConfig(definitionFormat=TypeDefinitionFormat(1), description="Inventory reservation result for a single order item. Fields: OrderID string, ItemID string, SKU string, RequestedQty int, AvailableQty int, Reserved bool, Status string (CONFIRMED / OUT_OF_STOCK / PROCESSING_ERROR), UnitPrice float64, Error string.", module="model", name="OrderItemResult", package="", publicType=False, transferByValue=False, type=DataType.struct, ), },
}

_ENVIRONMENT_VARIABLES: tuple[tuple[str, tuple[str, ...], str], ...] = (
    ("INVENTORY_PRIORITY_WORKERS_EXECUTORS_COUNT", ("pools", "inventoryPriorityWorkers", "executorsCount", ), "int"),
    ("INVENTORY_SERVICE_API_ADDRESS", ("dataConnectors", "inventoryServiceApi", "address", ), "string"),
    ("INVENTORY_SERVICE_API_CONNECTIONS_COUNT", ("dataConnectors", "inventoryServiceApi", "connectionsCount", ), "int"),
    ("INVENTORY_SERVICE_DEFAULT_GRPC_TIMEOUT", ("services", "inventoryService", "defaultGrpcTimeout", ), "int"),
    ("INVENTORY_SERVICE_ENVIRONMENT", ("services", "inventoryService", "environment", ), "api.Environment"),
    ("INVENTORY_SERVICE_GRPC_HOST", ("services", "inventoryService", "grpcHost", ), "string"),
    ("INVENTORY_SERVICE_GRPC_PORT", ("services", "inventoryService", "grpcPort", ), "int"),
    ("INVENTORY_SERVICE_HTTP_HOST", ("services", "inventoryService", "httpHost", ), "string"),
    ("INVENTORY_SERVICE_HTTP_PORT", ("services", "inventoryService", "httpPort", ), "int"),
)


class ServiceIds:
    INVENTORY_SERVICE: Final[int] = 3


class StreamIds:
    GET_INVENTORY_ITEM_DATA: Final[int] = 42
    MERGE_INVENTORY_RESULT: Final[int] = 44
    PROCESS_INVENTORY_ITEM: Final[int] = 45


class EndpointIds:
    PROCESS_ORDER_ITEM: Final[int] = 1


class DataConnectorIds:
    INVENTORY_SERVICE_API: Final[int] = 1


@dataclass(frozen=True, slots=True)
class Streams:
    get_inventory_item_data: ProcessStreamConfig
    merge_inventory_result: MergeStreamConfig
    process_inventory_item: InputStreamConfig


@dataclass(frozen=True, slots=True)
class Endpoints:
    process_order_item: GrpcEndpointConfig


@dataclass(frozen=True, slots=True)
class DataConnectors:
    inventory_service_api: GrpcDataConnectorConfig


@dataclass(frozen=True, slots=True)
class Services:
    inventory_service: ServiceConfig


@dataclass(frozen=True, slots=True)
class Pools:
    inventory_priority_workers: PoolConfig


@dataclass(frozen=True, slots=True)
class Modules:
    inventory_service_api: ModuleConfig
    model: ModuleConfig
    order_service_api: ModuleConfig


@dataclass(frozen=True, slots=True)
class NamedConfig:
    streams: Streams
    endpoints: Endpoints
    data_connectors: DataConnectors
    services: Services
    pools: Pools
    modules: Modules


def _environment_value(name: str, kind: str) -> Any | None:
    value = os.environ.get(name)
    if value is None:
        return None
    try:
        if kind == "int":
            return int(value)
        if kind == "float64":
            return float(value)
        if kind == "bool":
            normalized = value.strip().lower()
            if normalized in {"1", "true", "yes", "on"}:
                return True
            if normalized in {"0", "false", "no", "off"}:
                return False
            raise ValueError("expected a boolean")
        if kind == "[]int":
            return [int(item.strip()) for item in value.split(",") if item.strip()]
        if kind == "[]string":
            return [item.strip() for item in value.split(",") if item.strip()]
        return value
    except ValueError as error:
        raise ValueError(f"invalid {name}: {error}") from error


def _set_config_path(config: dict[str, Any], path: tuple[str, ...], value: Any) -> None:
    current = config
    for part in path[:-1]:
        child = current.get(part)
        if not isinstance(child, dict):
            raise TypeError(f"config path '{'.'.join(path)}' is not a mapping")
        current = child
    current[path[-1]] = value


class GeneratedConfig(ServiceAppConfig):
    """Generated typed view over the runtime graph configuration."""

    @classmethod
    def _load_config(cls, obj: dict[str, Any]) -> dict[str, Any]:
        defaults = _dump_default_config(_DEFAULT_CONFIG)
        normalized = _deep_merge(defaults, obj)
        for name, path, kind in _ENVIRONMENT_VARIABLES:
            if (value := _environment_value(name, kind)) is not None:
                _set_config_path(normalized, path, value)
        return super()._load_config(_normalize_sections(normalized))

    @classmethod
    def from_snapshot(cls, obj: dict[str, Any]) -> Self:
        """Restore a fully resolved immutable Workflow configuration.

        Unlike ``from_dict``, this path deliberately applies neither generated
        defaults nor process environment variables. The submitting process has
        already resolved both and serialized the exact snapshot into Temporal
        history; replay must reconstruct that value byte-for-byte.
        """

        cfg = cls.model_validate(super()._load_config(_normalize_sections(obj)))
        cfg.init_runtime_config()
        return cfg

    @property
    def named(self) -> NamedConfig:
        return NamedConfig(
            streams=Streams(
                get_inventory_item_data=ProcessStreamConfig(
                    self.get_stream_config_by_id(StreamIds.GET_INVENTORY_ITEM_DATA)
                ),
                merge_inventory_result=MergeStreamConfig(
                    self.get_stream_config_by_id(StreamIds.MERGE_INVENTORY_RESULT)
                ),
                process_inventory_item=InputStreamConfig(
                    self.get_stream_config_by_id(StreamIds.PROCESS_INVENTORY_ITEM)
                ),
            ),
            endpoints=Endpoints(
                process_order_item=_grpc_endpoint(
                    self.get_endpoint_config_by_id(EndpointIds.PROCESS_ORDER_ITEM)
                ),
            ),
            data_connectors=DataConnectors(
                inventory_service_api=_grpc_data_connector(
                    self.get_data_connector_by_id(
                        DataConnectorIds.INVENTORY_SERVICE_API
                    )
                ),
            ),
            services=Services(
                inventory_service=self.get_service_config_by_id(
                    ServiceIds.INVENTORY_SERVICE
                ),
            ),
            pools=Pools(
                inventory_priority_workers=_require_pool(
                    self.get_pool_by_name("Inventory Priority Workers"),
                    "Inventory Priority Workers",
                ),
            ),
            modules=Modules(
                inventory_service_api=_require_module(
                    self.runtime_config.modules.get("inventory_service_api"),
                    "inventory_service_api",
                ),
                model=_require_module(
                    self.runtime_config.modules.get("model"),
                    "model",
                ),
                order_service_api=_require_module(
                    self.runtime_config.modules.get("order_service_api"),
                    "order_service_api",
                ),
            ),
        )


def _implementation(config: DataConnectorConfig) -> DataConnectorImplementation:
    if config.implementation is None:
        raise ValueError(f"data connector '{config.name}' has no implementation")
    return DataConnectorImplementation(config.implementation)


def _http_data_connector(config: DataConnectorConfig) -> HttpDataConnectorConfig:
    return HttpDataConnectorConfig(
        id=config.id,
        name=config.name,
        implementation=_implementation(config),
        host=config.host,
        port=config.port,
        module=config.module,
        use_dedicated_listener=config.use_dedicated_listener or False,
        properties=config.properties,
    )


def _grpc_data_connector(config: DataConnectorConfig) -> GrpcDataConnectorConfig:
    return GrpcDataConnectorConfig(
        id=config.id,
        name=config.name,
        implementation=_implementation(config),
        address=config.address,
        module=config.module,
        connections_count=config.connections_count or 1,
        properties=config.properties,
    )


def _kafka_data_connector(config: DataConnectorConfig) -> KafkaDataConnectorConfig:
    return KafkaDataConnectorConfig(
        id=config.id,
        name=config.name,
        implementation=_implementation(config),
        brokers=config.brokers,
        version=config.version,
        dial_timeout=config.dial_timeout or 0.0,
        use_partitioner=config.use_partitioner or False,
        async_=getattr(config, "async_", False) or False,
        security_protocol=config.security_protocol or KafkaSecurityProtocol.PLAINTEXT,
        sasl_mechanism=config.sasl_mechanism or KafkaSaslMechanism.PLAIN,
        username=config.username,
        password=config.password,
        properties=config.properties,
    )


def _cron_data_connector(config: DataConnectorConfig) -> CronDataConnectorConfig:
    return CronDataConnectorConfig(
        id=config.id,
        name=config.name,
        implementation=_implementation(config),
        properties=config.properties,
    )


def _temporal_data_connector(
    config: DataConnectorConfig,
) -> TemporalDataConnectorConfig:
    return TemporalDataConnectorConfig(
        id=config.id,
        name=config.name,
        implementation=_implementation(config),
        address=config.address or "",
        namespace=config.namespace or "",
        identity=config.identity or "",
        api_key=getattr(config, "api_key", "") or "",
        tls_enabled=getattr(config, "tls_enabled", False) or False,
        tls_server_name=getattr(config, "tls_server_name", "") or "",
        tls_ca_file=getattr(config, "tls_ca_file", "") or "",
        tls_cert_file=getattr(config, "tls_cert_file", "") or "",
        tls_key_file=getattr(config, "tls_key_file", "") or "",
        max_concurrent_activities=(
            getattr(config, "max_concurrent_activities")
            if getattr(config, "max_concurrent_activities", None) is not None
            else 1
        ),
        max_concurrent_workflows=(
            getattr(config, "max_concurrent_workflows")
            if getattr(config, "max_concurrent_workflows", None) is not None
            else 1
        ),
        properties=config.properties,
    )


def _custom_data_connector(config: DataConnectorConfig) -> CustomDataConnectorConfig:
    return CustomDataConnectorConfig(
        id=config.id,
        name=config.name,
        implementation=_implementation(config),
        properties=config.properties,
    )


def _http_endpoint(config: EndpointConfig) -> HttpEndpointConfig:
    return HttpEndpointConfig(
        id=config.id,
        name=config.name,
        id_data_connector=config.id_data_connector,
        tracing_enabled=config.tracing_enabled or False,
        http_method_type=config.http_method_type,
        path=config.path,
        function_name=config.function_name,
        function_package=config.function_package,
        public_function=config.public_function or False,
        function_description=config.function_description,
        function_initializer_group=config.function_initializer_group,
        function_module=config.function_module,
        properties=config.properties,
    )


def _grpc_endpoint(config: EndpointConfig) -> GrpcEndpointConfig:
    return GrpcEndpointConfig(
        id=config.id,
        name=config.name,
        id_data_connector=config.id_data_connector,
        tracing_enabled=config.tracing_enabled or False,
        grpc_method_type=config.grpc_method_type,
        method_name=config.method_name,
        function_name=config.function_name,
        function_package=config.function_package,
        public_function=config.public_function or False,
        function_description=config.function_description,
        function_initializer_group=config.function_initializer_group,
        function_module=config.function_module,
        properties=config.properties,
    )


def _kafka_endpoint(config: EndpointConfig) -> KafkaEndpointConfig:
    return KafkaEndpointConfig(
        id=config.id,
        name=config.name,
        id_data_connector=config.id_data_connector,
        tracing_enabled=config.tracing_enabled or False,
        enabled=config.enabled or False,
        topic=config.topic,
        consumer_group=config.consumer_group,
        create_topic=config.create_topic or False,
        partitions=config.partitions or 0,
        replication_factor=config.replication_factor or 0,
        function_name=config.function_name,
        function_package=config.function_package,
        public_function=config.public_function or False,
        function_description=config.function_description,
        function_initializer_group=config.function_initializer_group,
        function_module=config.function_module,
        properties=config.properties,
    )


def _cron_endpoint(config: EndpointConfig) -> CronEndpointConfig:
    return CronEndpointConfig(
        id=config.id,
        name=config.name,
        id_data_connector=config.id_data_connector,
        tracing_enabled=config.tracing_enabled or False,
        enabled=config.enabled or False,
        schedule=config.schedule or "",
        timezone=config.timezone or "UTC",
        overlap_policy=config.overlap_policy or ScheduleOverlapPolicy.SKIP,
        missed_run_policy=(
            config.missed_run_policy or ScheduleMissedRunPolicy.SKIP
        ),
        properties=config.properties,
    )


def _temporal_endpoint(config: EndpointConfig) -> TemporalEndpointConfig:
    return TemporalEndpointConfig(
        id=config.id,
        name=config.name,
        id_data_connector=config.id_data_connector,
        temporal_execution_type=_require_temporal_execution_type(config),
        tracing_enabled=config.tracing_enabled or False,
        enabled=config.enabled or False,
        task_queue=config.task_queue or "",
        schedule=config.schedule or "",
        schedule_id=config.schedule_id or "",
        timezone=config.timezone or "UTC",
        overlap_policy=config.overlap_policy or ScheduleOverlapPolicy.SKIP,
        missed_run_policy=(
            config.missed_run_policy or ScheduleMissedRunPolicy.SKIP
        ),
        workflow_execution_timeout=(
            config.workflow_execution_timeout
            if config.workflow_execution_timeout is not None
            else 0
        ),
        activity_start_to_close_timeout=(
            config.activity_start_to_close_timeout
            if config.activity_start_to_close_timeout is not None
            else 0
        ),
        activity_heartbeat_timeout=(
            config.activity_heartbeat_timeout
            if config.activity_heartbeat_timeout is not None
            else 0
        ),
        maximum_attempts=(
            config.maximum_attempts if config.maximum_attempts is not None else 1
        ),
        properties=config.properties,
    )


def _require_temporal_execution_type(
    config: EndpointConfig,
) -> TemporalExecutionType:
    if config.temporal_execution_type is None:
        raise ValueError(
            f"Temporal endpoint {config.name!r} requires temporalExecutionType"
        )
    return config.temporal_execution_type


def _custom_endpoint(config: EndpointConfig) -> CustomEndpointConfig:
    return CustomEndpointConfig(
        id=config.id,
        name=config.name,
        id_data_connector=config.id_data_connector,
        tracing_enabled=config.tracing_enabled or False,
        function_name=config.function_name,
        function_package=config.function_package,
        public_function=config.public_function or False,
        function_description=config.function_description,
        function_initializer_group=config.function_initializer_group,
        function_module=config.function_module,
        properties=config.properties,
    )


def _require_pool(config: PoolConfig | None, name: str) -> PoolConfig:
    if config is None:
        raise KeyError(f"pool '{name}' is missing from service config")
    return config


def _require_module(config: ModuleConfig | None, name: str) -> ModuleConfig:
    if config is None:
        raise KeyError(f"module '{name}' is missing from service config")
    return config


def _deep_merge(
    defaults: dict[str, Any],
    overrides: dict[str, Any],
) -> dict[str, Any]:
    result = dict(defaults)
    for key, override in overrides.items():
        current = result.get(key)
        if isinstance(current, dict) and isinstance(override, dict):
            result[key] = _deep_merge(current, override)
        else:
            result[key] = override
    return result


def _normalize_sections(obj: dict[str, Any]) -> dict[str, Any]:
    normalized = dict(obj)

    def values(name: str) -> list[dict[str, Any]]:
        section = normalized.get(name, {})
        if isinstance(section, dict):
            return list(section.values())
        if isinstance(section, list):
            return list(section)
        raise TypeError(f"config section '{name}' must be a mapping or list")

    for name in (
        "services", "streams", "links", "types", "pools", "modules", "endpoints",
    ):
        normalized[name] = values(name)
    normalized["dataConnectors"] = values("dataConnectors")
    return normalized


def _dump_default_config(value: Any) -> Any:
    if hasattr(value, "model_dump"):
        return value.model_dump(by_alias=True, exclude_none=True)
    if isinstance(value, dict):
        return {
            key: _dump_default_config(child)
            for key, child in value.items()
        }
    if isinstance(value, list):
        return [_dump_default_config(child) for child in value]
    return value