# Code generated by servicegen. DO NOT EDIT.

.DEFAULT_GOAL := build
DOCKER_TARGET := runtime
DOCKER_DEV_TARGET := development
STANDALONE_COMPOSE := $(if $(wildcard docker-compose.yml),docker-compose.yml,docker-compose.generated.yml)
# Recursive expansion is intentional: USE_LOCAL_MODULES may replace the
# individual source contexts below after this list has been declared.
MODULE_CONTEXT_ARGS =
PYSERVICELIB_SOURCE_CONTEXT ?= https://github.com/gorundebug/pyservicelib.git\#v0.2.44
MODULE_CONTEXT_ARGS += --build-context pyservicelib-source="$(PYSERVICELIB_SOURCE_CONTEXT)"
MODEL_PYTHON_SOURCE_CONTEXT ?= https://github.com/gorundebug/pyexample.git\#v0.2.44
MODULE_CONTEXT_ARGS += --build-context module-model_python-source="$(MODEL_PYTHON_SOURCE_CONTEXT)"
DEPENDENCY_DOWNLOAD_ENV := $(or $(wildcard $(abspath ./dependency-download-env.generated.sh)),$(wildcard $(abspath ../dependency-download-env.generated.sh)),/bin/sh)
SHELL := $(DEPENDENCY_DOWNLOAD_ENV)
.SHELLFLAGS := -c
export

DEPENDENCY_DOCKER_TARGETS := docker-build docker-up docker-build-dev docker-up-dev debug
include dependency-proxy.generated.mk

USE_LOCAL_MODULES ?= 0
DEBUG_PORT ?= 2345
export DEBUG_PORT

ifeq ($(strip $(USE_LOCAL_MODULES)),1)
export LOCAL_DEPENDENCIES_DIR := $(abspath ..)
MODEL_PYTHON_SOURCE_CONTEXT := ../model_python
endif

ifneq ($(strip $(DEPENDENCY_PROXY_DIR)),)
ifeq ($(origin PYSERVICELIB_SOURCE_CONTEXT),file)
PYSERVICELIB_SOURCE_CONTEXT := $(DEPENDENCY_GIT_MIRROR_DOCKER_BASE)/github.com/gorundebug/pyservicelib.git\#v0.2.44
endif
ifneq ($(strip $(USE_LOCAL_MODULES)),1)
MODEL_PYTHON_SOURCE_CONTEXT := $(DEPENDENCY_GIT_MIRROR_DOCKER_BASE)/github.com/gorundebug/pyexample.git\#v0.2.44
endif
endif

.PHONY: init build test lint fmt clean docker-build docker-build-dev docker-up docker-up-dev \
	debug docker-down docker-down-dev docker-clean help

init: ## Create the environment and install service dependencies
	@./scripts/fetch-dependencies.generated.sh
	@uv sync --all-extras

build: init ## [host] Build the service wheel
	@uv build

test: init ## [host] Run the service tests
	@uv run pytest tests

lint: init ## Run mypy and Ruff checks
	@uv run mypy --package "automation_service"
	@uv run ruff check --force-exclude --exclude generated \
		--exclude '*generated.py' src tests

fmt: init ## Format and auto-fix Python sources
	@uv run ruff check --fix --force-exclude --exclude generated \
		--exclude '*generated.py' src tests
	@uv run ruff format --force-exclude --exclude generated \
		--exclude '*generated.py' src tests

clean: ## Remove Python build and cache artifacts
	@rm -rf .venv dist build .mypy_cache .pytest_cache .ruff_cache
	@find . -type d -name __pycache__ -prune -exec rm -rf {} +

docker-build: ## [Docker] Build the autonomous copied-source runtime image
	@set -e; \
	args=""; \
	if [ -n "$${GITHUB_TOKEN:-}" ]; then \
	  args="$$args --secret id=github_token,env=GITHUB_TOKEN"; \
	fi; \
	if [ -n "$${GITLAB_TOKEN:-}" ]; then \
	  args="$$args --secret id=gitlab_token,env=GITLAB_TOKEN"; \
	fi; \
	docker build $$args $(DEPENDENCY_PROXY_DOCKER_ARGS) --target "$(DOCKER_TARGET)" \
	  $(MODULE_CONTEXT_ARGS) \
	  --build-arg DEPENDENCY_DOCKER_REGISTRY="$${DEPENDENCY_DOCKER_REGISTRY:-docker.io}" \
	  --build-arg PIP_INDEX_URL="$${PIP_INDEX_URL:-https://pypi.org/simple}" \
	  --build-arg PIP_TRUSTED_HOST="$${PIP_TRUSTED_HOST:-}" \
	  --build-arg UV_INDEX_URL="$${UV_INDEX_URL:-https://pypi.org/simple}" \
	  --build-arg GIT_CONFIG_COUNT="$${GIT_CONFIG_COUNT:-0}" \
	  --build-arg GIT_CONFIG_KEY_0="$${GIT_CONFIG_KEY_0:-}" \
	  --build-arg GIT_CONFIG_VALUE_0="$${GIT_CONFIG_VALUE_0:-}" \
	  --build-arg GIT_CONFIG_KEY_1="$${GIT_CONFIG_KEY_1:-}" \
	  --build-arg GIT_CONFIG_VALUE_1="$${GIT_CONFIG_VALUE_1:-}" \
	  --build-arg DEPENDENCY_GITHUB_RAW_URL="$${DEPENDENCY_GITHUB_RAW_URL:-https://github.com}" \
	  --build-arg DEPENDENCY_APT_DEBIAN_URL="$${DEPENDENCY_APT_DEBIAN_URL:-}" \
	  --build-arg DEPENDENCY_APT_DEBIAN_SECURITY_URL="$${DEPENDENCY_APT_DEBIAN_SECURITY_URL:-}" \
	  -t "automationservice-python:local" .

docker-build-dev: ## Build the source-mounted standalone development image
	@$(MAKE) docker-build DOCKER_TARGET="$(DOCKER_DEV_TARGET)"
	@docker tag "automationservice-python:local" \
	  "automationservice-python-development:local"

docker-up: docker-build ## Start this service through Docker Compose
	@docker compose -f "$(STANDALONE_COMPOSE)" up -d --no-build

docker-up-dev: docker-build-dev ## Start this service with its source directory mounted
	@docker compose -f "$(STANDALONE_COMPOSE)" -f docker-compose.dev.generated.yml up -d --no-build

debug: docker-build-dev ## Start debugpy on host port $(DEBUG_PORT), container port 2345
	@DEBUG=1 docker compose -f "$(STANDALONE_COMPOSE)" -f docker-compose.dev.generated.yml \
		up -d --no-build --force-recreate

docker-down: ## Stop this service
	@docker compose -f "$(STANDALONE_COMPOSE)" down

docker-down-dev: ## Stop the source-mounted standalone service
	@docker compose -f "$(STANDALONE_COMPOSE)" -f docker-compose.dev.generated.yml down

docker-clean: docker-down ## Stop the service and remove volumes
	@docker compose -f "$(STANDALONE_COMPOSE)" down --volumes --remove-orphans

help: ## Show this help
	@grep -hE '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
	  sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-24s %s\n", $$1, $$2}'