"""Code generated by servicegen. DO NOT EDIT."""

from dataclasses import dataclass
from typing import Any, Final

from pyservicelib_gorundebug.api.models.data_connector_implementation import (
    DataConnectorImplementation,
)
from pyservicelib_gorundebug.api.models.call_semantics import CallSemantics
from pyservicelib_gorundebug.api.models.data_connector_type import (
    DataConnectorType,
)
from pyservicelib_gorundebug.api.models.data_type import DataType
from pyservicelib_gorundebug.api.models.environment import Environment
from pyservicelib_gorundebug.api.models.grpc_method_type import GrpcMethodType
from pyservicelib_gorundebug.api.models.http_method_type import HTTPMethodType
from pyservicelib_gorundebug.api.models.join_storage_type import JoinStorageType
from pyservicelib_gorundebug.api.models.join_type import JoinType
from pyservicelib_gorundebug.api.models.log_level import LogLevel
from pyservicelib_gorundebug.api.models.process_pattern import ProcessPattern
from pyservicelib_gorundebug.api.models.programming_language import (
    ProgrammingLanguage,
)
from pyservicelib_gorundebug.api.models.transformation_type import (
    TransformationType,
)
from pyservicelib_gorundebug.api.models.type_definition_format import (
    TypeDefinitionFormat,
)
from pyservicelib_gorundebug.runtime.config.config import (
    DataConnectorConfig,
    EndpointConfig,
    LinkConfig,
    PoolConfig,
    ProjectSettings,
    ServiceAppConfig,
    ServiceConfig,
    StreamConfig,
    TypeConfig,
)
from pyservicelib_gorundebug.runtime.config.dataconnector_types import (
    CustomDataConnectorConfig,
    GrpcDataConnectorConfig,
    HttpDataConnectorConfig,
    KafkaDataConnectorConfig,
)
from pyservicelib_gorundebug.runtime.config.endpoint_types import (
    CustomEndpointConfig,
    GrpcEndpointConfig,
    HttpEndpointConfig,
    KafkaEndpointConfig,
)

from pyservicelib_gorundebug.runtime.config.stream_types import (
    DelayStreamConfig,
    FlatMapStreamConfig,
    InputStreamConfig,
    MapStreamConfig,
    MergeStreamConfig,
    SinkStreamConfig,
    SplitStreamConfig,
)


_DEFAULT_CONFIG: dict[str, Any] = {
    "settings": ProjectSettings(
        moduleVersion="v0.0.1",
        name="Example",
        repoPath="github.com/gorundebug/pyexample",
    ),
    "services": {
        "orderService": ServiceConfig(
            color="#D2E5FF",
            defaultCallSemantics=CallSemantics(2),
            defaultGrpcTimeout=0,
            environment=Environment(""),
            golangVersion="1.25.4",
            grpcHost="0.0.0.0",
            grpcPort=9201,
            httpHost="0.0.0.0",
            httpPort=9091,
            id=2,
            metricsHandler="metrics",
            modulePath="github.com/gorundebug/pyexample-orderservice",
            name="Order Service",
            programmingLanguage=ProgrammingLanguage(3),
            shutdownTimeout=30000,
            statusHandler="status",
        ),
    },
    "streams": {
        "mapOrderItemResultToOrderState": StreamConfig(
            functionDescription="Convert a single OrderItemResult into an OrderState.\nSet OrderID from result.OrderID; set Status=CONFIRMED if result.Reserved==true, otherwise PARTIALLY_CONFIRMED.\nSet ConfirmedItems to a single-element slice containing result.\n",
            functionInitializerGroup="",
            functionModule="",
            functionName="MapOrderItemResultToOrderState",
            functionPackage="",
            id=5,
            idService=2,
            idSource=9,
            name="Map Order Item Result To Order State",
            pipeline="order",
            type=TransformationType(2),
            valueType="OrderState",
            xPos=0,
            yPos=0,
        ),
        "mapToOrderState": StreamConfig(
            functionDescription="Convert an Order that reached the soft deadline into an OrderState.\nSet OrderID from Order.ID; set Status to TIMED_OUT; leave ConfirmedItems nil.\n",
            functionInitializerGroup="",
            functionModule="",
            functionName="MapToOrderState",
            functionPackage="",
            id=6,
            idService=2,
            idSource=11,
            name="Map to Order State",
            pipeline="order",
            type=TransformationType(2),
            valueType="OrderState",
            xPos=-459,
            yPos=76,
        ),
        "mergeResults": StreamConfig(
            id=7,
            idService=2,
            idSource=0,
            idSources=[6, 5],
            name="Merge Results",
            pipeline="order",
            type=TransformationType(10),
            xPos=-178,
            yPos=24,
        ),
        "processOrder": StreamConfig(
            id=8,
            idEndpoint=2,
            idService=2,
            idSource=7,
            name="Process Order",
            pipeline="order",
            type=TransformationType(1),
            valueType="Order",
            xPos=-343,
            yPos=-229,
        ),
        "processOrderItem": StreamConfig(
            id=9,
            idEndpoint=1,
            idService=2,
            idSource=10,
            name="Process Order Item",
            pipeline="order",
            type=TransformationType(13),
            valueType="OrderItemResult",
            xPos=-75,
            yPos=-311,
        ),
        "processOrderItems": StreamConfig(
            functionDescription="Expand an Order into individual OrderItem messages — one sc.Collect call per element of Order.Items.\nCopy Order.ID into each emitted OrderItem.OrderID.\n",
            functionInitializerGroup="",
            functionModule="",
            functionName="ProcessOrderItems",
            functionPackage="",
            id=10,
            idService=2,
            idSource=12,
            name="Process Order Items",
            pipeline="order",
            type=TransformationType(7),
            valueType="OrderItem",
            xPos=-197,
            yPos=-473,
        ),
        "softDeadline": StreamConfig(
            duration=1000,
            functionDescription="Cast stream.GetConfig() to *runtimecfg.DelayStreamConfig and convert cfg.Duration (int, milliseconds) to time.Duration — this is the safety margin.\nIf ctx has no deadline (ctx.Deadline() ok==false), return the margin directly.\nOtherwise compute time.Until(deadline) minus the margin: if the result is negative return 0, otherwise return it.\n",
            functionInitializerGroup="",
            functionModule="",
            functionName="SoftDeadline",
            functionPackage="",
            id=11,
            idService=2,
            idSource=12,
            name="Soft Deadline",
            pipeline="order",
            type=TransformationType(16),
            xPos=-706,
            yPos=-33,
        ),
        "splitPipeline": StreamConfig(
            id=12,
            idService=2,
            idSource=8,
            name="Split Pipeline",
            pipeline="order",
            type=TransformationType(11),
            xPos=-416,
            yPos=-472,
        ),
    },
    "dataConnectors": {
        "inventoryServiceApi": DataConnectorConfig(
            address="dns:///localhost:9202",
            id=1,
            implementation="google/grpc",
            module="inventory_service_api",
            name="Inventory Service API",
            type=DataConnectorType(2),
        ),
        "orderServiceApi": DataConnectorConfig(
            id=2,
            implementation="aiohttp",
            module="order_service_api",
            name="Order Service API",
            type=DataConnectorType(1),
            useDedicatedListener=False,
        ),
    },
    "endpoints": {
        "processOrder": EndpointConfig(
            functionDescription="HTTP source handler for POST /v1/processorder.\n[Handler] holds timeout time.Duration read from config property 'timeout' (milliseconds, default 5000).\n[HandlerState] carries a context cancel function.\n[BeginRequest] attaches context timeout via WithTimeout, stores cancel in handler state.\n[ConsumeMessage] decodes JSON body; validates Items non-empty and all quantities positive (write 400 and return error on failure);\ngenerates order ID as UUID; maps each item to OrderItem (ItemId, SKU, Quantity);\nreads optional CustomerId; builds Order with CreatedAt=now;\nregisters result callback keyed on order ID; emits Order via sc.Collect.\n[Result callback] called once per result (N inventory results + possibly one TIMED_OUT);\ncaptures in its closure: sync.Mutex mu, accumulator []OrderItemResult, responseSent bool;\nlocks mu on each invocation;\nif responseSent return true;\nif Status==TIMED_OUT compute TotalAmount as sum of item.UnitPrice*item.RequestedQty for each accumulated item, write partial response with accumulated items, call Done(), return true;\notherwise append result.ConfirmedItems to accumulator and return false if len(accumulated) < N;\nwhen all N collected compute status (CONFIRMED if all items in accumulator have Reserved==true, else PARTIALLY_CONFIRMED),\ncompute TotalAmount as sum of item.UnitPrice * item.RequestedQty for each item in accumulator,\nwrite JSON response, call Done(), return true.\n[GetMessageID] returns OrderState.OrderID.\n[EndRequest] cancels context.\n[Private helper] converts OrderState to ProcessOrderResponse mapping all fields including optional ConfirmedItems slice.\n",
            functionInitializerGroup="",
            functionName="ProcessOrder",
            functionPackage="",
            httpMethodType=HTTPMethodType("POST"),
            id=2,
            idDataConnector=2,
            name="Process Order",
            path="/v1/processorder",
            publicFunction=False,
        ),
        "processOrderItem": EndpointConfig(
            functionDescription="Outgoing unary gRPC call to the Inventory Service.\n[ConsumeMessage] map OrderItem → ProcessOrderItemRequest (OrderID, ItemID, SKU, Quantity); call sender.Send(req).\n[HandleResponse] map ProcessOrderItemResponse → OrderItemResult:\ncopy OrderID, ItemID, AvailableQty, Reserved, Status, UnitPrice from response; push downstream via sc.Collect.\n[EndRequest] log the outcome.\n",
            functionInitializerGroup="",
            functionName="ProcessOrderItem",
            functionPackage="",
            grpcMethodType=GrpcMethodType(1),
            id=1,
            idDataConnector=1,
            methodName="ProcessOrderItem",
            name="Process Order Item",
            publicFunction=False,
        ),
    },
    "pools": {},
    "links": {
        "splitPipelineToSoftDeadline": LinkConfig(
            callSemantics=CallSemantics(5),
            var_from=12,
            to=11,
        ),
    },
    "types": {
        "order": TypeConfig(
            definitionFormat=TypeDefinitionFormat(1),
            description="E-commerce order submitted by a customer. Fields: ID string, CustomerID string, Items []OrderItem, CreatedAt time.Time.",
            name="Order",
            package="",
            publicType=False,
            transferByValue=False,
            type=DataType.struct,
        ),
        "orderItem": TypeConfig(
            definitionFormat=TypeDefinitionFormat(1),
            description="A single line item within an order. Fields: OrderID string, ItemID string, SKU string, Quantity int.",
            module="model",
            name="OrderItem",
            package="",
            publicType=False,
            transferByValue=False,
            type=DataType.struct,
        ),
        "orderItemResult": TypeConfig(
            definitionFormat=TypeDefinitionFormat(1),
            description="Inventory reservation result for a single order item. Fields: OrderID string, ItemID string, SKU string, RequestedQty int, AvailableQty int, Reserved bool, Status string (CONFIRMED / OUT_OF_STOCK), UnitPrice float64.",
            module="model",
            name="OrderItemResult",
            package="",
            publicType=False,
            transferByValue=False,
            type=DataType.struct,
        ),
        "orderState": TypeConfig(
            definitionFormat=TypeDefinitionFormat(1),
            description="Processing result of an order. Fields: OrderID string, Status string (CONFIRMED — all items reserved; PARTIALLY_CONFIRMED — some items out of stock; TIMED_OUT — order timed out), ConfirmedItems []OrderItemResult, TotalAmount float64, ProcessedAt time.Time.",
            name="OrderState",
            package="",
            publicType=False,
            transferByValue=False,
            type=DataType.struct,
        ),
    },
}


class ServiceIds:
    ORDER_SERVICE: Final[int] = 2


class StreamIds:
    MAP_ORDER_ITEM_RESULT_TO_ORDER_STATE: Final[int] = 5
    MAP_TO_ORDER_STATE: Final[int] = 6
    MERGE_RESULTS: Final[int] = 7
    PROCESS_ORDER: Final[int] = 8
    PROCESS_ORDER_ITEM: Final[int] = 9
    PROCESS_ORDER_ITEMS: Final[int] = 10
    SOFT_DEADLINE: Final[int] = 11
    SPLIT_PIPELINE: Final[int] = 12


class EndpointIds:
    PROCESS_ORDER: Final[int] = 2
    PROCESS_ORDER_ITEM: Final[int] = 1


class DataConnectorIds:
    INVENTORY_SERVICE_API: Final[int] = 1
    ORDER_SERVICE_API: Final[int] = 2


@dataclass(frozen=True, slots=True)
class Streams:
    map_order_item_result_to_order_state: MapStreamConfig
    map_to_order_state: MapStreamConfig
    merge_results: MergeStreamConfig
    process_order: InputStreamConfig
    process_order_item: SinkStreamConfig
    process_order_items: FlatMapStreamConfig
    soft_deadline: DelayStreamConfig
    split_pipeline: SplitStreamConfig


@dataclass(frozen=True, slots=True)
class Endpoints:
    process_order: HttpEndpointConfig
    process_order_item: GrpcEndpointConfig


@dataclass(frozen=True, slots=True)
class DataConnectors:
    inventory_service_api: GrpcDataConnectorConfig
    order_service_api: HttpDataConnectorConfig


@dataclass(frozen=True, slots=True)
class Services:
    order_service: ServiceConfig


@dataclass(frozen=True, slots=True)
class Pools:
    pass


@dataclass(frozen=True, slots=True)
class NamedConfig:
    streams: Streams
    endpoints: Endpoints
    data_connectors: DataConnectors
    services: Services
    pools: Pools


class GeneratedConfig(ServiceAppConfig):
    """Generated typed view over the runtime graph configuration."""

    @classmethod
    def _load_config(cls, obj: dict[str, Any]) -> dict[str, Any]:
        def values(name: str) -> list[dict[str, Any]]:
            section = normalized.get(name, {})
            if isinstance(section, dict):
                return list(section.values())
            if isinstance(section, list):
                return section
            raise TypeError(f"config section '{name}' must be a mapping or list")

        defaults = _dump_default_config(_DEFAULT_CONFIG)
        normalized = _deep_merge(defaults, obj)
        for name in ("services", "streams", "links", "types", "pools", "endpoints"):
            normalized[name] = values(name)
        normalized["dataConnectors"] = values("dataConnectors")
        return super()._load_config(normalized)

    @property
    def named(self) -> NamedConfig:
        return NamedConfig(
            streams=Streams(
                map_order_item_result_to_order_state=MapStreamConfig(
                    self.get_stream_config_by_id(StreamIds.MAP_ORDER_ITEM_RESULT_TO_ORDER_STATE)
                ),
                map_to_order_state=MapStreamConfig(
                    self.get_stream_config_by_id(StreamIds.MAP_TO_ORDER_STATE)
                ),
                merge_results=MergeStreamConfig(
                    self.get_stream_config_by_id(StreamIds.MERGE_RESULTS)
                ),
                process_order=InputStreamConfig(
                    self.get_stream_config_by_id(StreamIds.PROCESS_ORDER)
                ),
                process_order_item=SinkStreamConfig(
                    self.get_stream_config_by_id(StreamIds.PROCESS_ORDER_ITEM)
                ),
                process_order_items=FlatMapStreamConfig(
                    self.get_stream_config_by_id(StreamIds.PROCESS_ORDER_ITEMS)
                ),
                soft_deadline=DelayStreamConfig(
                    self.get_stream_config_by_id(StreamIds.SOFT_DEADLINE)
                ),
                split_pipeline=SplitStreamConfig(
                    self.get_stream_config_by_id(StreamIds.SPLIT_PIPELINE)
                ),
            ),
            endpoints=Endpoints(
                process_order=_http_endpoint(
                    self.get_endpoint_config_by_id(EndpointIds.PROCESS_ORDER)
                ),
                process_order_item=_grpc_endpoint(
                    self.get_endpoint_config_by_id(EndpointIds.PROCESS_ORDER_ITEM)
                ),
            ),
            data_connectors=DataConnectors(
                inventory_service_api=_grpc_data_connector(
                    self.get_data_connector_by_id(
                        DataConnectorIds.INVENTORY_SERVICE_API
                    )
                ),
                order_service_api=_http_data_connector(
                    self.get_data_connector_by_id(
                        DataConnectorIds.ORDER_SERVICE_API
                    )
                ),
            ),
            services=Services(
                order_service=self.get_service_config_by_id(
                    ServiceIds.ORDER_SERVICE
                ),
            ),
            pools=Pools(
            ),
        )


def _implementation(config: DataConnectorConfig) -> DataConnectorImplementation:
    if config.implementation is None:
        raise ValueError(f"data connector '{config.name}' has no implementation")
    return DataConnectorImplementation(config.implementation)


def _http_data_connector(config: DataConnectorConfig) -> HttpDataConnectorConfig:
    return HttpDataConnectorConfig(
        id=config.id,
        name=config.name,
        implementation=_implementation(config),
        host=config.host,
        port=config.port,
        module=config.module,
        use_dedicated_listener=config.use_dedicated_listener or False,
        properties=config.properties,
    )


def _grpc_data_connector(config: DataConnectorConfig) -> GrpcDataConnectorConfig:
    return GrpcDataConnectorConfig(
        id=config.id,
        name=config.name,
        implementation=_implementation(config),
        address=config.address,
        module=config.module,
        properties=config.properties,
    )


def _kafka_data_connector(config: DataConnectorConfig) -> KafkaDataConnectorConfig:
    return KafkaDataConnectorConfig(
        id=config.id,
        name=config.name,
        implementation=_implementation(config),
        brokers=config.brokers,
        version=config.version,
        dial_timeout=config.dial_timeout or 0.0,
        use_partitioner=config.use_partitioner or False,
        async_=config.async_ or False,
        properties=config.properties,
    )


def _custom_data_connector(config: DataConnectorConfig) -> CustomDataConnectorConfig:
    return CustomDataConnectorConfig(
        id=config.id,
        name=config.name,
        implementation=_implementation(config),
        properties=config.properties,
    )


def _http_endpoint(config: EndpointConfig) -> HttpEndpointConfig:
    return HttpEndpointConfig(
        id=config.id,
        name=config.name,
        id_data_connector=config.id_data_connector,
        http_method_type=config.http_method_type,
        path=config.path,
        function_name=config.function_name,
        function_package=config.function_package,
        public_function=config.public_function or False,
        function_description=config.function_description,
        function_initializer_group=config.function_initializer_group,
        function_module=config.function_module,
        properties=config.properties,
    )


def _grpc_endpoint(config: EndpointConfig) -> GrpcEndpointConfig:
    return GrpcEndpointConfig(
        id=config.id,
        name=config.name,
        id_data_connector=config.id_data_connector,
        grpc_method_type=config.grpc_method_type,
        method_name=config.method_name,
        function_name=config.function_name,
        function_package=config.function_package,
        public_function=config.public_function or False,
        function_description=config.function_description,
        function_initializer_group=config.function_initializer_group,
        function_module=config.function_module,
        properties=config.properties,
    )


def _kafka_endpoint(config: EndpointConfig) -> KafkaEndpointConfig:
    return KafkaEndpointConfig(
        id=config.id,
        name=config.name,
        id_data_connector=config.id_data_connector,
        topic=config.topic,
        consumer_group=config.consumer_group,
        create_topic=config.create_topic or False,
        partitions=config.partitions or 0,
        replication_factor=config.replication_factor or 0,
        function_name=config.function_name,
        function_package=config.function_package,
        public_function=config.public_function or False,
        function_description=config.function_description,
        function_initializer_group=config.function_initializer_group,
        function_module=config.function_module,
        properties=config.properties,
    )


def _custom_endpoint(config: EndpointConfig) -> CustomEndpointConfig:
    return CustomEndpointConfig(
        id=config.id,
        name=config.name,
        id_data_connector=config.id_data_connector,
        function_name=config.function_name,
        function_package=config.function_package,
        public_function=config.public_function or False,
        function_description=config.function_description,
        function_initializer_group=config.function_initializer_group,
        function_module=config.function_module,
        properties=config.properties,
    )


def _require_pool(config: PoolConfig | None, name: str) -> PoolConfig:
    if config is None:
        raise KeyError(f"pool '{name}' is missing from service config")
    return config


def _deep_merge(
    defaults: dict[str, Any],
    overrides: dict[str, Any],
) -> dict[str, Any]:
    result = dict(defaults)
    for key, override in overrides.items():
        current = result.get(key)
        if isinstance(current, dict) and isinstance(override, dict):
            result[key] = _deep_merge(current, override)
        else:
            result[key] = override
    return result


def _dump_default_config(value: Any) -> Any:
    if hasattr(value, "model_dump"):
        return value.model_dump(by_alias=True, exclude_none=True)
    if isinstance(value, dict):
        return {
            key: _dump_default_config(child)
            for key, child in value.items()
        }
    if isinstance(value, list):
        return [_dump_default_config(child) for child in value]
    return value