services:
  analyticsservice:
    image: analyticsservice-python:latest
    restart: unless-stopped
    environment:
      - DEBUG=${DEBUG:-0}
      - ANALYTICS_SERVICE_HTTP_PORT
      - ANALYTICS_SERVICE_GRPC_PORT
    ports:
      - "${ANALYTICS_SERVICE_HTTP_PORT:-9093}:${ANALYTICS_SERVICE_HTTP_PORT:-9093}"
      - "${ANALYTICS_SERVICE_GRPC_PORT:-9203}:${ANALYTICS_SERVICE_GRPC_PORT:-9203}"
      - "2345:2345"