"""Code generated by servicegen. DO NOT EDIT.

Replay a Temporal Event History against this service's static Workflows.
"""

from __future__ import annotations

import argparse
import asyncio
from pathlib import Path

from temporalio.client import WorkflowHistory
from temporalio.worker import Replayer

from pyservicelib_gorundebug.datasource.temporal.context_propagation import (
    TemporalContextPropagationInterceptor,
)

from .internal.app.temporal_workflows_generated import TEMPORAL_WORKFLOWS


async def replay(history_path: Path, workflow_id: str) -> None:
    history = WorkflowHistory.from_json(workflow_id, history_path.read_text())
    replayer = Replayer(
        workflows=TEMPORAL_WORKFLOWS,
        interceptors=[TemporalContextPropagationInterceptor(None)],
    )
    await replayer.replay_workflow(history)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("history", type=Path)
    parser.add_argument("--workflow-id", default="servicegen-replay")
    args = parser.parse_args()
    asyncio.run(replay(args.history, args.workflow_id))


if __name__ == "__main__":
    main()