services:
  inventoryservice:
    image: inventoryservice-python:latest
    restart: unless-stopped
    environment:
      - DEBUG=${DEBUG:-0}
    ports:
      - "9092:9092"
      - "9202:9202"
      - "2345:2345"