# Code generated by servicegen. DO NOT EDIT.

.DEFAULT_GOAL := build
SERVICEGEN_DOCKER_TARGET := runtime
SERVICEGEN_DOCKER_DEV_TARGET := development
STANDALONE_COMPOSE := $(if $(wildcard docker-compose.yml),docker-compose.yml,docker-compose.generated.yml)
SERVICEGEN_GITHUB_RAW_URL ?= https://github.com
SERVICEGEN_DOWNLOAD_MIRROR_ENV := $(or $(wildcard $(abspath ./dependency-download-env.generated.sh)),$(wildcard $(abspath ../dependency-download-env.generated.sh)),/bin/sh)
SHELL := $(SERVICEGEN_DOWNLOAD_MIRROR_ENV)
.SHELLFLAGS := -c
export

ifneq ($(strip $(SERVICEGEN_DEPENDENCY_PROXY_DIR)),)
SERVICEGEN_DEPENDENCY_PROXY_HOST ?= localhost
SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST ?= host.docker.internal
SERVICEGEN_DEPENDENCY_PROXY_PORT ?= 18081
SERVICEGEN_DEPENDENCY_PROXY_DOCKER_ARGS := --add-host host.docker.internal:host-gateway
export PIP_INDEX_URL := http://$(SERVICEGEN_DEPENDENCY_PROXY_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/pypi-proxy/simple
export PIP_TRUSTED_HOST := $(SERVICEGEN_DEPENDENCY_PROXY_HOST)
export UV_INDEX_URL := http://$(SERVICEGEN_DEPENDENCY_PROXY_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/pypi-proxy/simple
export SERVICEGEN_GITHUB_RAW_URL := http://$(SERVICEGEN_DEPENDENCY_PROXY_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/github-raw
docker-build docker-up docker-build-dev docker-up-dev: export PIP_INDEX_URL := http://$(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/pypi-proxy/simple
docker-build docker-up docker-build-dev docker-up-dev: export PIP_TRUSTED_HOST := $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST)
docker-build docker-up docker-build-dev docker-up-dev: export UV_INDEX_URL := http://$(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/pypi-proxy/simple
docker-build docker-up docker-build-dev docker-up-dev: export SERVICEGEN_GITHUB_RAW_URL := http://$(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/github-raw
docker-build docker-up docker-build-dev docker-up-dev: export SERVICEGEN_APT_DEBIAN_URL := http://$(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/apt-debian
docker-build docker-up docker-build-dev docker-up-dev: export SERVICEGEN_APT_DEBIAN_SECURITY_URL := http://$(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/apt-debian-security
endif

.PHONY: init build test lint fmt clean docker-build docker-build-dev docker-up docker-up-dev \
	docker-down docker-down-dev docker-clean help

init: ## Create the environment and install service dependencies
	@./scripts/fetch-dependencies.generated.sh
	@uv sync --all-extras

build: init ## Build the service wheel
	@uv build

test: init ## Run the service tests
	@uv run pytest tests

lint: init ## Run mypy and Ruff checks
	@uv run mypy --package "inventory_service"
	@uv run ruff check --force-exclude --exclude generated \
		--exclude '*generated.py' src tests

fmt: init ## Format and auto-fix Python sources
	@uv run ruff check --fix --force-exclude --exclude generated \
		--exclude '*generated.py' src tests
	@uv run ruff format --force-exclude --exclude generated \
		--exclude '*generated.py' src tests

clean: ## Remove Python build and cache artifacts
	@rm -rf .venv dist build .mypy_cache .pytest_cache .ruff_cache
	@find . -type d -name __pycache__ -prune -exec rm -rf {} +

docker-build: ## Build the standalone service image
	@set -e; \
	args=""; \
	if [ -n "$${GITHUB_TOKEN:-}" ]; then \
	  args="$$args --secret id=github_token,env=GITHUB_TOKEN"; \
	fi; \
	if [ -n "$${GITLAB_TOKEN:-}" ]; then \
	  args="$$args --secret id=gitlab_token,env=GITLAB_TOKEN"; \
	fi; \
	docker build $$args $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_ARGS) --target "$(SERVICEGEN_DOCKER_TARGET)" \
	  --build-arg PIP_INDEX_URL="$${PIP_INDEX_URL:-https://pypi.org/simple}" \
	  --build-arg PIP_TRUSTED_HOST="$${PIP_TRUSTED_HOST:-}" \
	  --build-arg UV_INDEX_URL="$${UV_INDEX_URL:-https://pypi.org/simple}" \
	  --build-arg SERVICEGEN_GITHUB_RAW_URL="$${SERVICEGEN_GITHUB_RAW_URL:-https://github.com}" \
	  --build-arg SERVICEGEN_APT_DEBIAN_URL="$${SERVICEGEN_APT_DEBIAN_URL:-}" \
	  --build-arg SERVICEGEN_APT_DEBIAN_SECURITY_URL="$${SERVICEGEN_APT_DEBIAN_SECURITY_URL:-}" \
	  -t "inventoryservice-python:latest" .

docker-build-dev: ## Build the source-mounted standalone development image
	@$(MAKE) docker-build SERVICEGEN_DOCKER_TARGET="$(SERVICEGEN_DOCKER_DEV_TARGET)"
	@docker tag "inventoryservice-python:latest" \
	  "inventoryservice-python-development:latest"

docker-up: docker-build ## Start this service through Docker Compose
	@docker compose -f "$(STANDALONE_COMPOSE)" up -d --no-build

docker-up-dev: docker-build-dev ## Start this service with its source directory mounted
	@docker compose -f "$(STANDALONE_COMPOSE)" -f docker-compose.dev.generated.yml up -d --no-build

docker-down: ## Stop this service
	@docker compose -f "$(STANDALONE_COMPOSE)" down

docker-down-dev: ## Stop the source-mounted standalone service
	@docker compose -f "$(STANDALONE_COMPOSE)" -f docker-compose.dev.generated.yml down

docker-clean: docker-down ## Stop the service and remove volumes
	@docker compose -f "$(STANDALONE_COMPOSE)" down --volumes --remove-orphans

help: ## Show this help
	@grep -hE '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
	  sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-24s %s\n", $$1, $$2}'