services:
  orderservice:
    image: orderservice-python:local
    restart: unless-stopped
    environment:
      - DEBUG=${DEBUG:-0}
      - ORDER_SERVICE_HTTP_PORT
      - ORDER_SERVICE_GRPC_PORT
    ports:
      - "${ORDER_SERVICE_HOST_HTTP_PORT:-9091}:${ORDER_SERVICE_HTTP_PORT:-9091}"
      - "${ORDER_SERVICE_HOST_GRPC_PORT:-9201}:${ORDER_SERVICE_GRPC_PORT:-9201}"