# Code generated by servicegen. DO NOT EDIT.

.DEFAULT_GOAL := build

.PHONY: init build test lint fmt clean docker-build docker-up docker-down \
	docker-clean help

init: ## Create the environment and install service dependencies
	@./scripts/fetch-dependencies.generated.sh
	@uv sync --all-extras

build: init ## Build the service wheel
	@uv build

test: init ## Run the service tests
	@uv run pytest tests

lint: init ## Run mypy and Ruff checks
	@uv run mypy --package "order_service"
	@uv run ruff check --force-exclude --exclude generated \
		--exclude '*generated.py' src tests

fmt: init ## Format and auto-fix Python sources
	@uv run ruff check --fix --force-exclude --exclude generated \
		--exclude '*generated.py' src tests
	@uv run ruff format --force-exclude --exclude generated \
		--exclude '*generated.py' src tests

clean: ## Remove Python build and cache artifacts
	@rm -rf .venv dist build .mypy_cache .pytest_cache .ruff_cache
	@find . -type d -name __pycache__ -prune -exec rm -rf {} +

docker-build: ## Build the standalone service image
	@set -e; \
	args=""; \
	if [ -n "$${GITHUB_TOKEN:-}" ]; then \
	  args="$$args --secret id=github_token,env=GITHUB_TOKEN"; \
	fi; \
	if [ -n "$${GITLAB_TOKEN:-}" ]; then \
	  args="$$args --secret id=gitlab_token,env=GITLAB_TOKEN"; \
	fi; \
	docker build $$args -t "orderservice-python:latest" .

docker-up: docker-build ## Start this service through Docker Compose
	@docker compose up -d --no-build

docker-down: ## Stop this service
	@docker compose down

docker-clean: docker-down ## Stop the service and remove volumes
	@docker compose down --volumes --remove-orphans

help: ## Show this help
	@grep -hE '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
	  sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-24s %s\n", $$1, $$2}'