"""Code generated by servicegen. DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Awaitable, Callable

from pyservicelib_gorundebug import transformation
from pyservicelib_gorundebug.runtime.context.context import Context
from pyservicelib_gorundebug.runtime.environment import ServiceEnvironment
from pyservicelib_gorundebug.runtime.config.endpoint_types import GrpcEndpointConfig, HttpEndpointConfig, KafkaEndpointConfig
from pyservicelib_gorundebug.runtime.config.stream_types import DelayStreamConfig, FlatMapStreamConfig, MapStreamConfig
from ..functions import (
    OrderProcessedEndpointSink,
    make_order_processed_endpoint_sink,
    ProcessOrderItemSink,
    make_process_order_item_sink,
    ProcessOrderSource,
    make_process_order_source,
    MapOrderItemResultToOrderState,
    make_map_order_item_result_to_order_state,
    MapToOrderProcessed,
    make_map_to_order_processed,
    MapToOrderState,
    make_map_to_order_state,
    ProcessOrderItems,
    make_process_order_items,
    SoftDeadline,
    make_soft_deadline,
)
from model.models.order_item import (
    OrderItem,
)
from model.models.order_item_result import (
    OrderItemResult,
)
from model.models.order_processed import (
    OrderProcessed,
)
from order_service.models.order import (
    Order,
)
from order_service.models.order_state import (
    OrderState,
)


@dataclass
class OrderPipelineMakers:
    order_processed_endpoint_sink: Callable[[Context, ServiceEnvironment, KafkaEndpointConfig], Awaitable[OrderProcessedEndpointSink]] = make_order_processed_endpoint_sink
    process_order_item_sink: Callable[[Context, ServiceEnvironment, GrpcEndpointConfig], Awaitable[ProcessOrderItemSink]] = make_process_order_item_sink
    process_order_source: Callable[[Context, ServiceEnvironment, HttpEndpointConfig], Awaitable[ProcessOrderSource]] = make_process_order_source
    map_order_item_result_to_order_state: Callable[[Context, ServiceEnvironment, MapStreamConfig], Awaitable[MapOrderItemResultToOrderState]] = make_map_order_item_result_to_order_state
    map_to_order_processed: Callable[[Context, ServiceEnvironment, MapStreamConfig], Awaitable[MapToOrderProcessed]] = make_map_to_order_processed
    map_to_order_state: Callable[[Context, ServiceEnvironment, MapStreamConfig], Awaitable[MapToOrderState]] = make_map_to_order_state
    process_order_items: Callable[[Context, ServiceEnvironment, FlatMapStreamConfig], Awaitable[ProcessOrderItems]] = make_process_order_items
    soft_deadline: Callable[[Context, ServiceEnvironment, DelayStreamConfig], Awaitable[SoftDeadline]] = make_soft_deadline


@dataclass
class OrderPipelineFunctions:
    order_processed_endpoint_sink: OrderProcessedEndpointSink
    process_order_item_sink: ProcessOrderItemSink
    process_order_source: ProcessOrderSource
    map_order_item_result_to_order_state: MapOrderItemResultToOrderState
    map_to_order_processed: MapToOrderProcessed
    map_to_order_state: MapToOrderState
    process_order_items: ProcessOrderItems
    soft_deadline: SoftDeadline


@dataclass
class OrderPipelineStreams:
    process_order: Any = None
    split_pipeline: Any = None
    process_order_items: Any = None
    process_order_item: Any = None
    process_order_item_error: Any = None
    map_order_item_result_to_order_state: Any = None
    soft_deadline: Any = None
    map_to_order_state: Any = None
    merge_results: Any = None
    split_order_result: Any = None
    map_to_order_processed: Any = None
    publish_order_processed: Any = None


def init_order_streams(service: Any, named: Any) -> None:
    init_order_process_order_stream(service, named)
    init_order_split_pipeline_stream(service, named)
    init_order_process_order_items_stream(service, named)
    init_order_process_order_item_stream(service, named)
    init_order_map_order_item_result_to_order_state_stream(service, named)
    init_order_soft_deadline_stream(service, named)
    init_order_map_to_order_state_stream(service, named)
    init_order_merge_results_stream(service, named)
    init_order_split_order_result_stream(service, named)
    init_order_map_to_order_processed_stream(service, named)
    init_order_publish_order_processed_stream(service, named)
    pass


def post_init_order_streams(service: Any) -> None:
    post_init_order_process_order_stream(service)
    pass
def init_order_process_order_stream(service: Any, named: Any) -> None:
    service._service_streams.process_order = transformation.Input[Order, OrderState, Exception](named.streams.process_order, service)
def init_order_split_pipeline_stream(service: Any, named: Any) -> None:
    service._service_streams.split_pipeline = transformation.Split[Order](named.streams.split_pipeline, service._service_streams.process_order)
def init_order_process_order_items_stream(service: Any, named: Any) -> None:
    service._service_streams.process_order_items = transformation.FlatMap[Order, OrderItem](named.streams.process_order_items, service._service_streams.split_pipeline.add_stream(), service.functions.process_order_items)
def init_order_process_order_item_stream(service: Any, named: Any) -> None:
    service._service_streams.process_order_item = transformation.SinkWithResult[OrderItem, OrderItemResult, OrderState](named.streams.process_order_item, service._service_streams.process_order_items)
    service._service_streams.process_order_item_error = service._service_streams.process_order_item.error_stream
def init_order_map_order_item_result_to_order_state_stream(service: Any, named: Any) -> None:
    service._service_streams.map_order_item_result_to_order_state = transformation.Map[OrderItemResult, OrderState](named.streams.map_order_item_result_to_order_state, service._service_streams.process_order_item, service.functions.map_order_item_result_to_order_state)
def init_order_soft_deadline_stream(service: Any, named: Any) -> None:
    service._service_streams.soft_deadline = transformation.Delay[Order](named.streams.soft_deadline, service._service_streams.split_pipeline.add_stream(), service.functions.soft_deadline)
def init_order_map_to_order_state_stream(service: Any, named: Any) -> None:
    service._service_streams.map_to_order_state = transformation.Map[Order, OrderState](named.streams.map_to_order_state, service._service_streams.soft_deadline, service.functions.map_to_order_state)
def init_order_merge_results_stream(service: Any, named: Any) -> None:
    service._service_streams.merge_results = transformation.Merge[OrderState](named.streams.merge_results, service._service_streams.map_to_order_state, service._service_streams.map_order_item_result_to_order_state, service._service_streams.process_order_item_error)
def init_order_split_order_result_stream(service: Any, named: Any) -> None:
    service._service_streams.split_order_result = transformation.Split[OrderState](named.streams.split_order_result, service._service_streams.merge_results)
def init_order_map_to_order_processed_stream(service: Any, named: Any) -> None:
    service._service_streams.map_to_order_processed = transformation.Map[OrderState, OrderProcessed](named.streams.map_to_order_processed, service._service_streams.split_order_result.add_stream(), service.functions.map_to_order_processed)
def init_order_publish_order_processed_stream(service: Any, named: Any) -> None:
    service._service_streams.publish_order_processed = transformation.Sink[OrderProcessed, Exception](named.streams.publish_order_processed, service._service_streams.map_to_order_processed)
def post_init_order_process_order_stream(service: Any) -> None:
    service._service_streams.process_order.set_source(service._service_streams.split_order_result.add_stream())