"""Code generated by servicegen. DO NOT EDIT."""

from collections.abc import Callable
from dataclasses import dataclass
from datetime import timedelta
from typing import Any, Optional
import grpc

from pyservicelib_gorundebug.runtime.context.context import Context
from pyservicelib_gorundebug.runtime.serviceapp import (
    ServiceApp,
    run_shutdown_operations,
)
from pyservicelib_gorundebug.runtime.serde import DataclassJsonSerde, Serializer
from pyservicelib_gorundebug import transformation
from pyservicelib_gorundebug.datasink.grpc import grpcds as grpc_sink
from pyservicelib_gorundebug.datasource.http import aiohttpds as http_source
import inventory_service_api.generated.proto.inventoryserviceapi.inventoryserviceapi.generated_pb2_grpc as inventory_service_api_grpc_api

from ..config import Config
from model.models.order_item import (
    OrderItem,
)
from model.models.order_item_result import (
    OrderItemResult,
)
from order_service.models.order import (
    Order,
)
from order_service.models.order_state import (
    OrderState,
)
from ..functions import (
    MapOrderItemResultToOrderState,
    MapToOrderState,
    ProcessOrder,
    ProcessOrderItem,
    ProcessOrderItems,
    SoftDeadline,
)


@dataclass(slots=True)
class ServiceStreams:
    process_order: Any = None
    split_pipeline: Any = None
    process_order_items: Any = None
    process_order_item: Any = None
    process_order_item_error: Any = None
    map_order_item_result_to_order_state: Any = None
    soft_deadline: Any = None
    map_to_order_state: Any = None
    merge_results: Any = None


class GeneratedService(ServiceApp):
    """Generated lifecycle and graph bootstrap for Order Service."""

    def __init__(self) -> None:
        super().__init__()
        self._makers: dict[str, Callable[[], Any]] = {
            "map_order_item_result_to_order_state": MapOrderItemResultToOrderState,
            "map_to_order_state": MapToOrderState,
            "process_order": ProcessOrder,
            "process_order_item": ProcessOrderItem,
            "process_order_items": ProcessOrderItems,
            "soft_deadline": SoftDeadline,
        }
        self._functions: dict[str, Any] = {}
        self._service_streams = ServiceStreams()
        self._transport_consumers: list[Any] = []
        self._grpc_channels: dict[str, grpc.aio.Channel] = {}

    @property
    def makers(self) -> dict[str, Callable[[], Any]]:
        return self._makers

    @property
    def functions(self) -> dict[str, Any]:
        return self._functions

    def get_serde(self, type_name: str) -> Optional[Serializer]:
        if type_name == "Order":
            return DataclassJsonSerde("Order", Order)
        if type_name == "OrderItem":
            return DataclassJsonSerde("OrderItem", OrderItem)
        if type_name == "OrderItemResult":
            return DataclassJsonSerde("OrderItemResult", OrderItemResult)
        if type_name == "OrderState":
            return DataclassJsonSerde("OrderState", OrderState)
        return None

    async def initialize_functions(self, ctx: Context) -> None:
        """Apply user maker overrides, construct functions, then configure them."""

        await self.custom_makers_init(ctx)
        self._functions = {
            name: maker()
            for name, maker in self._makers.items()
        }
        await self.custom_functions_init(ctx)

    async def build_stream_graph(self, ctx: Context) -> None:
        """Construct the configured stream graph with Go-compatible semantics."""

        await self.initialize_functions(ctx)
        cfg = self.config
        if not isinstance(cfg, Config):
            raise TypeError(
                "Order Service requires order_service.internal.config.Config"
            )
        named = cfg.named
        self._service_streams.process_order = transformation.Input[Order, OrderState, Exception](named.streams.process_order, self)
        self._service_streams.split_pipeline = transformation.Split[Order](named.streams.split_pipeline, self._service_streams.process_order)
        self._service_streams.process_order_items = transformation.FlatMap[Order, OrderItem](named.streams.process_order_items, self._service_streams.split_pipeline.add_stream(), self._functions["process_order_items"])
        self._service_streams.process_order_item = transformation.SinkWithResult[OrderItem, OrderItemResult, OrderState](named.streams.process_order_item, self._service_streams.process_order_items)
        self._service_streams.process_order_item_error = self._service_streams.process_order_item.error_stream
        self._service_streams.map_order_item_result_to_order_state = transformation.Map[OrderItemResult, OrderState](named.streams.map_order_item_result_to_order_state, self._service_streams.process_order_item, self._functions["map_order_item_result_to_order_state"])
        self._service_streams.soft_deadline = transformation.Delay[Order](named.streams.soft_deadline, self._service_streams.split_pipeline.add_stream(), self._functions["soft_deadline"])
        self._service_streams.map_to_order_state = transformation.Map[Order, OrderState](named.streams.map_to_order_state, self._service_streams.soft_deadline, self._functions["map_to_order_state"])
        self._service_streams.merge_results = transformation.Merge[OrderState](named.streams.merge_results, self._service_streams.map_to_order_state, self._service_streams.map_order_item_result_to_order_state, self._service_streams.process_order_item_error)
        self._service_streams.process_order.set_source(self._service_streams.merge_results)

    def bind_transports(self) -> None:
        """Bind configured endpoints to the already constructed streams."""

        cfg = self.config
        if not isinstance(cfg, Config):
            raise TypeError(
                "Order Service requires order_service.internal.config.Config"
            )
        named = cfg.named
        self._transport_consumers = []
        self._grpc_channels = {}
        process_order_consumer = http_source.make_net_http_endpoint_consumer(self._service_streams.process_order, self._functions["process_order"])
        self._transport_consumers.append(process_order_consumer)
        inventory_service_api_grpc_channel = grpc.aio.insecure_channel(_required(named.data_connectors.inventory_service_api.address, "Inventory Service API connector address"))
        self._grpc_channels["inventory_service_api"] = inventory_service_api_grpc_channel
        inventory_service_api_grpc_stub = inventory_service_api_grpc_api.InventoryServiceApiStub(inventory_service_api_grpc_channel)  # type: ignore[no-untyped-call]
        process_order_item_consumer = grpc_sink.make_grpc_no_streaming_endpoint_consumer(self._service_streams.process_order_item, self._functions["process_order_item"], inventory_service_api_grpc_stub.ProcessOrderItem)
        self._transport_consumers.append(process_order_item_consumer)

    async def build_runtime(self, ctx: Context) -> None:
        await self.build_stream_graph(ctx)
        self.bind_transports()

    async def start_service(self, ctx: Context) -> None:
        await self.build_runtime(ctx)
        await self.on_start(ctx)
        await self.start(ctx)

    async def stop_service(self, ctx: Context) -> None:
        ctx = ctx.bounded(
            timedelta(milliseconds=self.service_config.shutdown_timeout)
        )

        async def close_grpc_channels() -> None:
            channels = list(self._grpc_channels.values())
            self._grpc_channels = {}
            for channel in channels:
                await channel.close(grace=None)

        await run_shutdown_operations(
            self.log,
            ctx,
            [
                ("user_on_stop", self.on_stop(ctx)),
                ("service_runtime", self.stop(ctx)),
                ("grpc_channels", close_grpc_channels()),
            ],
        )

    async def custom_makers_init(self, ctx: Context) -> None:
        del ctx

    async def custom_functions_init(self, ctx: Context) -> None:
        del ctx

    async def on_start(self, ctx: Context) -> None:
        del ctx

    async def on_stop(self, ctx: Context) -> None:
        del ctx
def _required[T](value: T | None, label: str) -> T:
    if value is None:
        raise ValueError(f"{label} is required")
    return value