"""Code generated by servicegen. DO NOT EDIT."""

from collections.abc import Callable
from datetime import timedelta
from typing import Any
import grpc

from pyservicelib_gorundebug.runtime.context.context import Context
from pyservicelib_gorundebug.runtime.serviceapp import (
    ServiceApp,
    run_shutdown_operations,
)
from pyservicelib_gorundebug import transformation
from pyservicelib_gorundebug.datasink.grpc import grpcds as grpc_sink
from pyservicelib_gorundebug.datasource.http import aiohttpds as http_source
import inventory_service_api.generated.proto.inventoryserviceapi.inventoryserviceapi.generated_pb2_grpc as grpc_api_1

from ..config import Config
from model.models.order_item import (
    OrderItem,
)
from model.models.order_item_result import (
    OrderItemResult,
)
from order_service.models.order import (
    Order,
)
from order_service.models.order_state import (
    OrderState,
)
from ..functions import (
    MapOrderItemResultToOrderState,
    MapToOrderState,
    ProcessOrder,
    ProcessOrderItem,
    ProcessOrderItems,
    SoftDeadline,
)


class GeneratedService(ServiceApp):
    """Generated lifecycle and graph bootstrap for Order Service."""

    def __init__(self) -> None:
        super().__init__()
        self._makers: dict[str, Callable[[], Any]] = {
            "map_order_item_result_to_order_state": MapOrderItemResultToOrderState,
            "map_to_order_state": MapToOrderState,
            "process_order": ProcessOrder,
            "process_order_item": ProcessOrderItem,
            "process_order_items": ProcessOrderItems,
            "soft_deadline": SoftDeadline,
        }
        self._functions: dict[str, Any] = {}
        self._streams: dict[int, Any] = {}
        self._transport_consumers: list[Any] = []
        self._grpc_channels: dict[int, grpc.aio.Channel] = {}

    @property
    def makers(self) -> dict[str, Callable[[], Any]]:
        return self._makers

    @property
    def functions(self) -> dict[str, Any]:
        return self._functions

    @property
    def streams(self) -> dict[int, Any]:
        return self._streams

    async def initialize_functions(self, ctx: Context) -> None:
        """Apply user maker overrides, construct functions, then configure them."""

        await self.custom_makers_init(ctx)
        self._functions = {
            name: maker()
            for name, maker in self._makers.items()
        }
        await self.custom_functions_init(ctx)

    async def build_stream_graph(self, ctx: Context) -> None:
        """Construct the configured stream graph with Go-compatible semantics."""

        await self.initialize_functions(ctx)
        cfg = self.config
        if not isinstance(cfg, Config):
            raise TypeError(
                "Order Service requires order_service.internal.config.Config"
            )
        named = cfg.named
        self._streams = {}
        stream_8 = transformation.Input[Order, OrderState, Exception](named.streams.process_order, self)
        self._streams[8] = stream_8
        stream_12 = transformation.Split[Order](named.streams.split_pipeline, stream_8)
        self._streams[12] = stream_12
        stream_10 = transformation.FlatMap[Order, OrderItem](named.streams.process_order_items, stream_12.add_stream(), self._functions["process_order_items"])
        self._streams[10] = stream_10
        stream_9 = transformation.SinkWithResult[OrderItem, OrderItemResult, Exception](named.streams.process_order_item, stream_10)
        self._streams[9] = stream_9
        stream_5 = transformation.Map[OrderItemResult, OrderState](named.streams.map_order_item_result_to_order_state, stream_9, self._functions["map_order_item_result_to_order_state"])
        self._streams[5] = stream_5
        stream_11 = transformation.Delay[Order](named.streams.soft_deadline, stream_12.add_stream(), self._functions["soft_deadline"])
        self._streams[11] = stream_11
        stream_6 = transformation.Map[Order, OrderState](named.streams.map_to_order_state, stream_11, self._functions["map_to_order_state"])
        self._streams[6] = stream_6
        stream_7 = transformation.Merge[OrderState](named.streams.merge_results, stream_6, stream_5)
        self._streams[7] = stream_7
        stream_8.set_source(stream_7)

    def bind_transports(self) -> None:
        """Bind configured endpoints to the already constructed streams."""

        cfg = self.config
        if not isinstance(cfg, Config):
            raise TypeError(
                "Order Service requires order_service.internal.config.Config"
            )
        named = cfg.named
        self._transport_consumers = []
        self._grpc_channels = {}
        consumer_8 = http_source.make_net_http_endpoint_consumer(self._streams[8], self._functions["process_order"])
        self._transport_consumers.append(consumer_8)
        grpc_channel_1 = grpc.aio.insecure_channel(_required(named.data_connectors.inventory_service_api.address, "Inventory Service API connector address"))
        self._grpc_channels[1] = grpc_channel_1
        grpc_stub_1 = grpc_api_1.InventoryServiceApiStub(grpc_channel_1)  # type: ignore[no-untyped-call]
        consumer_9 = grpc_sink.make_grpc_no_streaming_endpoint_consumer(self._streams[9], self._functions["process_order_item"], grpc_stub_1.ProcessOrderItem)
        self._transport_consumers.append(consumer_9)

    async def build_runtime(self, ctx: Context) -> None:
        await self.build_stream_graph(ctx)
        self.bind_transports()

    async def start_service(self, ctx: Context) -> None:
        await self.build_runtime(ctx)
        await self.on_start(ctx)
        await self.start(ctx)

    async def stop_service(self, ctx: Context) -> None:
        ctx = ctx.bounded(
            timedelta(milliseconds=self.service_config.shutdown_timeout)
        )

        async def close_grpc_channels() -> None:
            channels = list(self._grpc_channels.values())
            self._grpc_channels = {}
            for channel in channels:
                await channel.close(grace=None)

        await run_shutdown_operations(
            self.log,
            ctx,
            [
                ("user_on_stop", self.on_stop(ctx)),
                ("service_runtime", self.stop(ctx)),
                ("grpc_channels", close_grpc_channels()),
            ],
        )

    async def custom_makers_init(self, ctx: Context) -> None:
        del ctx

    async def custom_functions_init(self, ctx: Context) -> None:
        del ctx

    async def on_start(self, ctx: Context) -> None:
        del ctx

    async def on_stop(self, ctx: Context) -> None:
        del ctx
def _required[T](value: T | None, label: str) -> T:
    if value is None:
        raise ValueError(f"{label} is required")
    return value