"""Code generated by servicegen. DO NOT EDIT."""

from __future__ import annotations


from dataclasses import dataclass
from typing import Any
from pyservicelib_gorundebug import transformation
from ..config import Config
from .functions_generated import ServiceFunctions
from model.models.order_item import (
    OrderItem,
)
from model.models.order_item_result import (
    OrderItemResult,
)
from model.models.order_processed import (
    OrderProcessed,
)
from order_service.models.order import (
    Order,
)
from order_service.models.order_state import (
    OrderState,
)


@dataclass(slots=True)
class ServiceStreams:
    process_order: Any = None
    split_pipeline: Any = None
    process_order_items: Any = None
    process_order_item: Any = None
    process_order_item_error: Any = None
    map_order_item_result_to_order_state: Any = None
    soft_deadline: Any = None
    map_to_order_state: Any = None
    merge_results: Any = None
    split_order_result: Any = None
    map_to_order_processed: Any = None
    publish_order_processed: Any = None

    def init_streams(self, config: Config, environment: Any, functions: ServiceFunctions) -> None:
        named = config.named
        self.process_order = transformation.Input[Order, OrderState, Exception](named.streams.process_order, environment)
        self.split_pipeline = transformation.Split[Order](named.streams.split_pipeline, self.process_order)
        self.process_order_items = transformation.FlatMap[Order, OrderItem](named.streams.process_order_items, self.split_pipeline.add_stream(), functions.process_order_items)
        self.process_order_item = transformation.SinkWithResult[OrderItem, OrderItemResult, OrderState](named.streams.process_order_item, self.process_order_items)
        self.process_order_item_error = self.process_order_item.error_stream
        self.map_order_item_result_to_order_state = transformation.Map[OrderItemResult, OrderState](named.streams.map_order_item_result_to_order_state, self.process_order_item, functions.map_order_item_result_to_order_state)
        self.soft_deadline = transformation.Delay[Order](named.streams.soft_deadline, self.split_pipeline.add_stream(), functions.soft_deadline)
        self.map_to_order_state = transformation.Map[Order, OrderState](named.streams.map_to_order_state, self.soft_deadline, functions.map_to_order_state)
        self.merge_results = transformation.Merge[OrderState](named.streams.merge_results, self.map_to_order_state, self.map_order_item_result_to_order_state, self.process_order_item_error)
        self.split_order_result = transformation.Split[OrderState](named.streams.split_order_result, self.merge_results)
        self.map_to_order_processed = transformation.Map[OrderState, OrderProcessed](named.streams.map_to_order_processed, self.split_order_result.add_stream(), functions.map_to_order_processed)
        self.publish_order_processed = transformation.Sink[OrderProcessed, Exception](named.streams.publish_order_processed, self.map_to_order_processed)


    def build(self) -> None:
        self.process_order.set_source(self.split_order_result.add_stream())

        pass