"""Initial native domain model scaffold generated by servicegen."""

from dataclasses import dataclass


# Automation job payload and result.
@dataclass(slots=True)
class String:
    """Generated domain type. Add schema fields to the service specification."""

    pass