"""Code generated by servicegen. DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any
from pyservicelib_gorundebug.runtime.context.context import Context
from ..config import Config
from pyservicelib_gorundebug.datasource import cron as cron_source
from pyservicelib_gorundebug.datasource import temporal as temporal_source
from pyservicelib_gorundebug.datasink import temporal as temporal_sink
from .temporal_workflows_generated import (
    FanOutWorkflowJobTemporalWorkflow,
    WorkflowJobTemporalWorkflow,
    TemporalWorkflowScheduleTemporalWorkflow,
)


@dataclass
class ServiceEndpoints:
    consumers: list[Any] = field(default_factory=list)

    async def bind(self, ctx: Context, service: Any) -> None:
        """Bind configured endpoints to the already constructed streams."""

        cfg = service.config
        if not isinstance(cfg, Config):
            raise TypeError(
                "Automation Service requires automation_service.internal.config.Config"
            )
        self.consumers = []
        call_fan_out_activity_a_consumer = temporal_sink.make_direct_endpoint_consumer_with_result(service._service_streams.call_fan_out_activity_a)
        self.consumers.append(call_fan_out_activity_a_consumer)
        call_fan_out_activity_b_consumer = temporal_sink.make_direct_endpoint_consumer_with_result(service._service_streams.call_fan_out_activity_b)
        self.consumers.append(call_fan_out_activity_b_consumer)
        call_fan_out_activity_c_consumer = temporal_sink.make_direct_endpoint_consumer_with_result(service._service_streams.call_fan_out_activity_c)
        self.consumers.append(call_fan_out_activity_c_consumer)
        call_sequential_activity_a_consumer = temporal_sink.make_direct_endpoint_consumer_with_result(service._service_streams.call_sequential_activity_a)
        self.consumers.append(call_sequential_activity_a_consumer)
        call_sequential_activity_b_consumer = temporal_sink.make_direct_endpoint_consumer_with_result(service._service_streams.call_sequential_activity_b)
        self.consumers.append(call_sequential_activity_b_consumer)
        consume_activity_job_consumer = temporal_source.make_direct_endpoint_consumer_with_handler(service._service_streams.consume_activity_job, service.functions.activity_job_endpoint_source)
        self.consumers.append(consume_activity_job_consumer)
        consume_fan_out_activity_a_consumer = temporal_source.make_direct_endpoint_consumer_with_handler(service._service_streams.consume_fan_out_activity_a, service.functions.fanout_activity_a_endpoint_source)
        self.consumers.append(consume_fan_out_activity_a_consumer)
        consume_fan_out_activity_b_consumer = temporal_source.make_direct_endpoint_consumer_with_handler(service._service_streams.consume_fan_out_activity_b, service.functions.fanout_activity_b_endpoint_source)
        self.consumers.append(consume_fan_out_activity_b_consumer)
        consume_fan_out_activity_c_consumer = temporal_source.make_direct_endpoint_consumer_with_handler(service._service_streams.consume_fan_out_activity_c, service.functions.fanout_activity_c_endpoint_source)
        self.consumers.append(consume_fan_out_activity_c_consumer)
        consume_fan_out_workflow_job_consumer = temporal_source.make_direct_endpoint_consumer_with_handler(service._service_streams.consume_fan_out_workflow_job, service.functions.fanout_workflow_job_endpoint_source, workflow_class=FanOutWorkflowJobTemporalWorkflow)
        self.consumers.append(consume_fan_out_workflow_job_consumer)
        consume_sequential_activity_a_consumer = temporal_source.make_direct_endpoint_consumer_with_handler(service._service_streams.consume_sequential_activity_a, service.functions.sequential_activity_a_endpoint_source)
        self.consumers.append(consume_sequential_activity_a_consumer)
        consume_sequential_activity_b_consumer = temporal_source.make_direct_endpoint_consumer_with_handler(service._service_streams.consume_sequential_activity_b, service.functions.sequential_activity_b_endpoint_source)
        self.consumers.append(consume_sequential_activity_b_consumer)
        consume_workflow_job_consumer = temporal_source.make_direct_endpoint_consumer_with_handler(service._service_streams.consume_workflow_job, service.functions.workflow_job_endpoint_source, workflow_class=WorkflowJobTemporalWorkflow)
        self.consumers.append(consume_workflow_job_consumer)
        local_schedule_consumer = cron_source.APSchedulerEndpointConsumer(service._service_streams.local_schedule, service.functions.local_schedule_source)
        self.consumers.append(local_schedule_consumer)
        submit_activity_job_consumer = temporal_sink.make_direct_endpoint_consumer_with_result(service._service_streams.submit_activity_job)
        self.consumers.append(submit_activity_job_consumer)
        submit_fan_out_workflow_job_consumer = temporal_sink.make_direct_endpoint_consumer(service._service_streams.submit_fan_out_workflow_job)
        self.consumers.append(submit_fan_out_workflow_job_consumer)
        submit_workflow_job_consumer = temporal_sink.make_direct_endpoint_consumer_with_result(service._service_streams.submit_workflow_job)
        self.consumers.append(submit_workflow_job_consumer)
        temporal_activity_schedule_consumer = temporal_source.make_schedule_endpoint_consumer(service._service_streams.temporal_activity_schedule, service.functions.temporal_activity_schedule_source)
        self.consumers.append(temporal_activity_schedule_consumer)
        temporal_workflow_schedule_consumer = temporal_source.make_schedule_endpoint_consumer(service._service_streams.temporal_workflow_schedule, service.functions.temporal_workflow_schedule_source, workflow_class=TemporalWorkflowScheduleTemporalWorkflow)
        self.consumers.append(temporal_workflow_schedule_consumer)