"""Code generated by servicegen. DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Awaitable, Callable

from pyservicelib_gorundebug import transformation
from pyservicelib_gorundebug.runtime.context.context import Context
from pyservicelib_gorundebug.runtime.environment import ServiceEnvironment
from pyservicelib_gorundebug.runtime.config.endpoint_types import CronEndpointConfig, TemporalEndpointConfig
from pyservicelib_gorundebug.runtime.config.stream_types import DelayStreamConfig, MapStreamConfig
from ..functions import (
    ActivityJobEndpointSink,
    make_activity_job_endpoint_sink,
    ActivityJobEndpointSource,
    make_activity_job_endpoint_source,
    FanoutActivityAEndpointSink,
    make_fanout_activity_a_endpoint_sink,
    FanoutActivityAEndpointSource,
    make_fanout_activity_a_endpoint_source,
    FanoutActivityBEndpointSink,
    make_fanout_activity_b_endpoint_sink,
    FanoutActivityBEndpointSource,
    make_fanout_activity_b_endpoint_source,
    FanoutActivityCEndpointSink,
    make_fanout_activity_c_endpoint_sink,
    FanoutActivityCEndpointSource,
    make_fanout_activity_c_endpoint_source,
    SequentialActivityAEndpointSink,
    make_sequential_activity_a_endpoint_sink,
    SequentialActivityAEndpointSource,
    make_sequential_activity_a_endpoint_source,
    SequentialActivityBEndpointSink,
    make_sequential_activity_b_endpoint_sink,
    SequentialActivityBEndpointSource,
    make_sequential_activity_b_endpoint_source,
    TemporalActivityScheduleSource,
    make_temporal_activity_schedule_source,
    ActivityPause,
    make_activity_pause,
    ObserveActivityResult,
    make_observe_activity_result,
    ObserveFanoutActivityB,
    make_observe_fanout_activity_b,
    ObserveFanoutActivityC,
    make_observe_fanout_activity_c,
    ObserveWorkflowResult,
    make_observe_workflow_result,
    ProcessActivityJob,
    make_process_activity_job,
    ProcessFanoutActivityA,
    make_process_fanout_activity_a,
    ProcessFanoutActivityB,
    make_process_fanout_activity_b,
    ProcessFanoutActivityC,
    make_process_fanout_activity_c,
    ProcessScheduledActivity,
    make_process_scheduled_activity,
    ProcessScheduledWorkflow,
    make_process_scheduled_workflow,
    ProcessSequentialActivityA,
    make_process_sequential_activity_a,
    ProcessSequentialActivityB,
    make_process_sequential_activity_b,
    ProcessWorkflowJob,
    make_process_workflow_job,
    ScheduledActivityPause,
    make_scheduled_activity_pause,
    ScheduledWorkflowPause,
    make_scheduled_workflow_pause,
    WorkflowPause,
    make_workflow_pause,
    LocalScheduleSource,
    make_local_schedule_source,
    FanoutWorkflowJobEndpointSink,
    make_fanout_workflow_job_endpoint_sink,
    FanoutWorkflowJobEndpointSource,
    make_fanout_workflow_job_endpoint_source,
    TemporalWorkflowScheduleSource,
    make_temporal_workflow_schedule_source,
    WorkflowJobEndpointSink,
    make_workflow_job_endpoint_sink,
    WorkflowJobEndpointSource,
    make_workflow_job_endpoint_source,
)
from model.models.automation_job_generated import (
    AutomationJob,
)


@dataclass
class AutomationPipelineMakers:
    activity_job_endpoint_sink: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], Awaitable[ActivityJobEndpointSink]] = make_activity_job_endpoint_sink
    activity_job_endpoint_source: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], Awaitable[ActivityJobEndpointSource]] = make_activity_job_endpoint_source
    fanout_activity_a_endpoint_sink: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], Awaitable[FanoutActivityAEndpointSink]] = make_fanout_activity_a_endpoint_sink
    fanout_activity_a_endpoint_source: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], Awaitable[FanoutActivityAEndpointSource]] = make_fanout_activity_a_endpoint_source
    fanout_activity_b_endpoint_sink: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], Awaitable[FanoutActivityBEndpointSink]] = make_fanout_activity_b_endpoint_sink
    fanout_activity_b_endpoint_source: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], Awaitable[FanoutActivityBEndpointSource]] = make_fanout_activity_b_endpoint_source
    fanout_activity_c_endpoint_sink: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], Awaitable[FanoutActivityCEndpointSink]] = make_fanout_activity_c_endpoint_sink
    fanout_activity_c_endpoint_source: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], Awaitable[FanoutActivityCEndpointSource]] = make_fanout_activity_c_endpoint_source
    sequential_activity_a_endpoint_sink: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], Awaitable[SequentialActivityAEndpointSink]] = make_sequential_activity_a_endpoint_sink
    sequential_activity_a_endpoint_source: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], Awaitable[SequentialActivityAEndpointSource]] = make_sequential_activity_a_endpoint_source
    sequential_activity_b_endpoint_sink: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], Awaitable[SequentialActivityBEndpointSink]] = make_sequential_activity_b_endpoint_sink
    sequential_activity_b_endpoint_source: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], Awaitable[SequentialActivityBEndpointSource]] = make_sequential_activity_b_endpoint_source
    temporal_activity_schedule_source: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], Awaitable[TemporalActivityScheduleSource]] = make_temporal_activity_schedule_source
    activity_pause: Callable[[Context, ServiceEnvironment, DelayStreamConfig], Awaitable[ActivityPause]] = make_activity_pause
    observe_activity_result: Callable[[Context, ServiceEnvironment, MapStreamConfig], Awaitable[ObserveActivityResult]] = make_observe_activity_result
    observe_fanout_activity_b: Callable[[Context, ServiceEnvironment, MapStreamConfig], Awaitable[ObserveFanoutActivityB]] = make_observe_fanout_activity_b
    observe_fanout_activity_c: Callable[[Context, ServiceEnvironment, MapStreamConfig], Awaitable[ObserveFanoutActivityC]] = make_observe_fanout_activity_c
    observe_workflow_result: Callable[[Context, ServiceEnvironment, MapStreamConfig], Awaitable[ObserveWorkflowResult]] = make_observe_workflow_result
    process_activity_job: Callable[[Context, ServiceEnvironment, MapStreamConfig], Awaitable[ProcessActivityJob]] = make_process_activity_job
    process_fanout_activity_a: Callable[[Context, ServiceEnvironment, MapStreamConfig], Awaitable[ProcessFanoutActivityA]] = make_process_fanout_activity_a
    process_fanout_activity_b: Callable[[Context, ServiceEnvironment, MapStreamConfig], Awaitable[ProcessFanoutActivityB]] = make_process_fanout_activity_b
    process_fanout_activity_c: Callable[[Context, ServiceEnvironment, MapStreamConfig], Awaitable[ProcessFanoutActivityC]] = make_process_fanout_activity_c
    process_scheduled_activity: Callable[[Context, ServiceEnvironment, MapStreamConfig], Awaitable[ProcessScheduledActivity]] = make_process_scheduled_activity
    process_scheduled_workflow: Callable[[Context, ServiceEnvironment, MapStreamConfig], Awaitable[ProcessScheduledWorkflow]] = make_process_scheduled_workflow
    process_sequential_activity_a: Callable[[Context, ServiceEnvironment, MapStreamConfig], Awaitable[ProcessSequentialActivityA]] = make_process_sequential_activity_a
    process_sequential_activity_b: Callable[[Context, ServiceEnvironment, MapStreamConfig], Awaitable[ProcessSequentialActivityB]] = make_process_sequential_activity_b
    process_workflow_job: Callable[[Context, ServiceEnvironment, MapStreamConfig], Awaitable[ProcessWorkflowJob]] = make_process_workflow_job
    scheduled_activity_pause: Callable[[Context, ServiceEnvironment, DelayStreamConfig], Awaitable[ScheduledActivityPause]] = make_scheduled_activity_pause
    scheduled_workflow_pause: Callable[[Context, ServiceEnvironment, DelayStreamConfig], Awaitable[ScheduledWorkflowPause]] = make_scheduled_workflow_pause
    workflow_pause: Callable[[Context, ServiceEnvironment, DelayStreamConfig], Awaitable[WorkflowPause]] = make_workflow_pause
    local_schedule_source: Callable[[Context, ServiceEnvironment, CronEndpointConfig], Awaitable[LocalScheduleSource]] = make_local_schedule_source
    fanout_workflow_job_endpoint_sink: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], Awaitable[FanoutWorkflowJobEndpointSink]] = make_fanout_workflow_job_endpoint_sink
    fanout_workflow_job_endpoint_source: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], Awaitable[FanoutWorkflowJobEndpointSource]] = make_fanout_workflow_job_endpoint_source
    temporal_workflow_schedule_source: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], Awaitable[TemporalWorkflowScheduleSource]] = make_temporal_workflow_schedule_source
    workflow_job_endpoint_sink: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], Awaitable[WorkflowJobEndpointSink]] = make_workflow_job_endpoint_sink
    workflow_job_endpoint_source: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], Awaitable[WorkflowJobEndpointSource]] = make_workflow_job_endpoint_source


@dataclass
class AutomationPipelineFunctions:
    activity_job_endpoint_sink: ActivityJobEndpointSink
    activity_job_endpoint_source: ActivityJobEndpointSource
    fanout_activity_a_endpoint_sink: FanoutActivityAEndpointSink
    fanout_activity_a_endpoint_source: FanoutActivityAEndpointSource
    fanout_activity_b_endpoint_sink: FanoutActivityBEndpointSink
    fanout_activity_b_endpoint_source: FanoutActivityBEndpointSource
    fanout_activity_c_endpoint_sink: FanoutActivityCEndpointSink
    fanout_activity_c_endpoint_source: FanoutActivityCEndpointSource
    sequential_activity_a_endpoint_sink: SequentialActivityAEndpointSink
    sequential_activity_a_endpoint_source: SequentialActivityAEndpointSource
    sequential_activity_b_endpoint_sink: SequentialActivityBEndpointSink
    sequential_activity_b_endpoint_source: SequentialActivityBEndpointSource
    temporal_activity_schedule_source: TemporalActivityScheduleSource
    activity_pause: ActivityPause
    observe_activity_result: ObserveActivityResult
    observe_fanout_activity_b: ObserveFanoutActivityB
    observe_fanout_activity_c: ObserveFanoutActivityC
    observe_workflow_result: ObserveWorkflowResult
    process_activity_job: ProcessActivityJob
    process_fanout_activity_a: ProcessFanoutActivityA
    process_fanout_activity_b: ProcessFanoutActivityB
    process_fanout_activity_c: ProcessFanoutActivityC
    process_scheduled_activity: ProcessScheduledActivity
    process_scheduled_workflow: ProcessScheduledWorkflow
    process_sequential_activity_a: ProcessSequentialActivityA
    process_sequential_activity_b: ProcessSequentialActivityB
    process_workflow_job: ProcessWorkflowJob
    scheduled_activity_pause: ScheduledActivityPause
    scheduled_workflow_pause: ScheduledWorkflowPause
    workflow_pause: WorkflowPause
    local_schedule_source: LocalScheduleSource
    fanout_workflow_job_endpoint_sink: FanoutWorkflowJobEndpointSink
    fanout_workflow_job_endpoint_source: FanoutWorkflowJobEndpointSource
    temporal_workflow_schedule_source: TemporalWorkflowScheduleSource
    workflow_job_endpoint_sink: WorkflowJobEndpointSink
    workflow_job_endpoint_source: WorkflowJobEndpointSource


@dataclass
class AutomationPipelineStreams:
    consume_activity_job: Any = None
    activity_pause: Any = None
    consume_fan_out_workflow_job: Any = None
    call_fan_out_activity_a: Any = None
    split_activity_a_result: Any = None
    call_fan_out_activity_b: Any = None
    call_fan_out_activity_c: Any = None
    consume_workflow_job: Any = None
    workflow_pause: Any = None
    call_sequential_activity_a: Any = None
    call_sequential_activity_b: Any = None
    consume_fan_out_activity_a: Any = None
    consume_fan_out_activity_b: Any = None
    consume_fan_out_activity_c: Any = None
    consume_sequential_activity_a: Any = None
    consume_sequential_activity_b: Any = None
    local_schedule: Any = None
    split_on_demand_jobs: Any = None
    submit_activity_job: Any = None
    observe_activity_result: Any = None
    observe_fan_out_activity_b: Any = None
    observe_fan_out_activity_c: Any = None
    submit_workflow_job: Any = None
    observe_workflow_result: Any = None
    process_activity_job: Any = None
    process_fan_out_activity_a: Any = None
    process_fan_out_activity_b: Any = None
    process_fan_out_activity_c: Any = None
    temporal_activity_schedule: Any = None
    scheduled_activity_pause: Any = None
    process_scheduled_activity: Any = None
    temporal_workflow_schedule: Any = None
    scheduled_workflow_pause: Any = None
    process_scheduled_workflow: Any = None
    process_sequential_activity_a: Any = None
    process_sequential_activity_b: Any = None
    process_workflow_job: Any = None
    submit_fan_out_workflow_job: Any = None


def init_automation_streams(service: Any, named: Any) -> None:
    init_automation_consume_activity_job_stream(service, named)
    init_automation_activity_pause_stream(service, named)
    init_automation_consume_fan_out_workflow_job_stream(service, named)
    init_automation_call_fan_out_activity_a_stream(service, named)
    init_automation_split_activity_a_result_stream(service, named)
    init_automation_call_fan_out_activity_b_stream(service, named)
    init_automation_call_fan_out_activity_c_stream(service, named)
    init_automation_consume_workflow_job_stream(service, named)
    init_automation_workflow_pause_stream(service, named)
    init_automation_call_sequential_activity_a_stream(service, named)
    init_automation_call_sequential_activity_b_stream(service, named)
    init_automation_consume_fan_out_activity_a_stream(service, named)
    init_automation_consume_fan_out_activity_b_stream(service, named)
    init_automation_consume_fan_out_activity_c_stream(service, named)
    init_automation_consume_sequential_activity_a_stream(service, named)
    init_automation_consume_sequential_activity_b_stream(service, named)
    init_automation_local_schedule_stream(service, named)
    init_automation_split_on_demand_jobs_stream(service, named)
    init_automation_submit_activity_job_stream(service, named)
    init_automation_observe_activity_result_stream(service, named)
    init_automation_observe_fan_out_activity_b_stream(service, named)
    init_automation_observe_fan_out_activity_c_stream(service, named)
    init_automation_submit_workflow_job_stream(service, named)
    init_automation_observe_workflow_result_stream(service, named)
    init_automation_process_activity_job_stream(service, named)
    init_automation_process_fan_out_activity_a_stream(service, named)
    init_automation_process_fan_out_activity_b_stream(service, named)
    init_automation_process_fan_out_activity_c_stream(service, named)
    init_automation_temporal_activity_schedule_stream(service, named)
    init_automation_scheduled_activity_pause_stream(service, named)
    init_automation_process_scheduled_activity_stream(service, named)
    init_automation_temporal_workflow_schedule_stream(service, named)
    init_automation_scheduled_workflow_pause_stream(service, named)
    init_automation_process_scheduled_workflow_stream(service, named)
    init_automation_process_sequential_activity_a_stream(service, named)
    init_automation_process_sequential_activity_b_stream(service, named)
    init_automation_process_workflow_job_stream(service, named)
    init_automation_submit_fan_out_workflow_job_stream(service, named)
    pass


def post_init_automation_streams(service: Any) -> None:
    post_init_automation_consume_activity_job_stream(service)
    post_init_automation_consume_workflow_job_stream(service)
    post_init_automation_consume_fan_out_activity_a_stream(service)
    post_init_automation_consume_fan_out_activity_b_stream(service)
    post_init_automation_consume_fan_out_activity_c_stream(service)
    post_init_automation_consume_sequential_activity_a_stream(service)
    post_init_automation_consume_sequential_activity_b_stream(service)
    post_init_automation_temporal_activity_schedule_stream(service)
    post_init_automation_temporal_workflow_schedule_stream(service)
    pass
def init_automation_consume_activity_job_stream(service: Any, named: Any) -> None:
    service._service_streams.consume_activity_job = transformation.Input[str, str, Exception](named.streams.consume_activity_job, service)
def init_automation_activity_pause_stream(service: Any, named: Any) -> None:
    service._service_streams.activity_pause = transformation.Delay[str](named.streams.activity_pause, service._service_streams.consume_activity_job, service.functions.activity_pause)
def init_automation_consume_fan_out_workflow_job_stream(service: Any, named: Any) -> None:
    service._service_streams.consume_fan_out_workflow_job = transformation.Input[str, object, Exception](named.streams.consume_fan_out_workflow_job, service)
def init_automation_call_fan_out_activity_a_stream(service: Any, named: Any) -> None:
    service._service_streams.call_fan_out_activity_a = transformation.SinkWithResult[str, str, Exception](named.streams.call_fan_out_activity_a, service._service_streams.consume_fan_out_workflow_job)
def init_automation_split_activity_a_result_stream(service: Any, named: Any) -> None:
    service._service_streams.split_activity_a_result = transformation.Split[str](named.streams.split_activity_a_result, service._service_streams.call_fan_out_activity_a)
def init_automation_call_fan_out_activity_b_stream(service: Any, named: Any) -> None:
    service._service_streams.call_fan_out_activity_b = transformation.SinkWithResult[str, str, Exception](named.streams.call_fan_out_activity_b, service._service_streams.split_activity_a_result.add_stream())
def init_automation_call_fan_out_activity_c_stream(service: Any, named: Any) -> None:
    service._service_streams.call_fan_out_activity_c = transformation.SinkWithResult[str, str, Exception](named.streams.call_fan_out_activity_c, service._service_streams.split_activity_a_result.add_stream())
def init_automation_consume_workflow_job_stream(service: Any, named: Any) -> None:
    service._service_streams.consume_workflow_job = transformation.Input[str, str, Exception](named.streams.consume_workflow_job, service)
def init_automation_workflow_pause_stream(service: Any, named: Any) -> None:
    service._service_streams.workflow_pause = transformation.Delay[str](named.streams.workflow_pause, service._service_streams.consume_workflow_job, service.functions.workflow_pause)
def init_automation_call_sequential_activity_a_stream(service: Any, named: Any) -> None:
    service._service_streams.call_sequential_activity_a = transformation.SinkWithResult[str, str, Exception](named.streams.call_sequential_activity_a, service._service_streams.workflow_pause)
def init_automation_call_sequential_activity_b_stream(service: Any, named: Any) -> None:
    service._service_streams.call_sequential_activity_b = transformation.SinkWithResult[str, str, Exception](named.streams.call_sequential_activity_b, service._service_streams.call_sequential_activity_a)
def init_automation_consume_fan_out_activity_a_stream(service: Any, named: Any) -> None:
    service._service_streams.consume_fan_out_activity_a = transformation.Input[str, str, Exception](named.streams.consume_fan_out_activity_a, service)
def init_automation_consume_fan_out_activity_b_stream(service: Any, named: Any) -> None:
    service._service_streams.consume_fan_out_activity_b = transformation.Input[str, str, Exception](named.streams.consume_fan_out_activity_b, service)
def init_automation_consume_fan_out_activity_c_stream(service: Any, named: Any) -> None:
    service._service_streams.consume_fan_out_activity_c = transformation.Input[str, str, Exception](named.streams.consume_fan_out_activity_c, service)
def init_automation_consume_sequential_activity_a_stream(service: Any, named: Any) -> None:
    service._service_streams.consume_sequential_activity_a = transformation.Input[str, str, Exception](named.streams.consume_sequential_activity_a, service)
def init_automation_consume_sequential_activity_b_stream(service: Any, named: Any) -> None:
    service._service_streams.consume_sequential_activity_b = transformation.Input[str, str, Exception](named.streams.consume_sequential_activity_b, service)
def init_automation_local_schedule_stream(service: Any, named: Any) -> None:
    service._service_streams.local_schedule = transformation.Input[str, object, Exception](named.streams.local_schedule, service)
def init_automation_split_on_demand_jobs_stream(service: Any, named: Any) -> None:
    service._service_streams.split_on_demand_jobs = transformation.Split[str](named.streams.split_on_demand_jobs, service._service_streams.local_schedule)
def init_automation_submit_activity_job_stream(service: Any, named: Any) -> None:
    service._service_streams.submit_activity_job = transformation.SinkWithResult[str, str, Exception](named.streams.submit_activity_job, service._service_streams.split_on_demand_jobs.add_stream())
def init_automation_observe_activity_result_stream(service: Any, named: Any) -> None:
    service._service_streams.observe_activity_result = transformation.Map[str, str](named.streams.observe_activity_result, service._service_streams.submit_activity_job, service.functions.observe_activity_result)
def init_automation_observe_fan_out_activity_b_stream(service: Any, named: Any) -> None:
    service._service_streams.observe_fan_out_activity_b = transformation.Map[str, str](named.streams.observe_fan_out_activity_b, service._service_streams.call_fan_out_activity_b, service.functions.observe_fanout_activity_b)
def init_automation_observe_fan_out_activity_c_stream(service: Any, named: Any) -> None:
    service._service_streams.observe_fan_out_activity_c = transformation.Map[str, str](named.streams.observe_fan_out_activity_c, service._service_streams.call_fan_out_activity_c, service.functions.observe_fanout_activity_c)
def init_automation_submit_workflow_job_stream(service: Any, named: Any) -> None:
    service._service_streams.submit_workflow_job = transformation.SinkWithResult[str, str, Exception](named.streams.submit_workflow_job, service._service_streams.split_on_demand_jobs.add_stream())
def init_automation_observe_workflow_result_stream(service: Any, named: Any) -> None:
    service._service_streams.observe_workflow_result = transformation.Map[str, str](named.streams.observe_workflow_result, service._service_streams.submit_workflow_job, service.functions.observe_workflow_result)
def init_automation_process_activity_job_stream(service: Any, named: Any) -> None:
    service._service_streams.process_activity_job = transformation.Map[str, str](named.streams.process_activity_job, service._service_streams.activity_pause, service.functions.process_activity_job)
def init_automation_process_fan_out_activity_a_stream(service: Any, named: Any) -> None:
    service._service_streams.process_fan_out_activity_a = transformation.Map[str, str](named.streams.process_fan_out_activity_a, service._service_streams.consume_fan_out_activity_a, service.functions.process_fanout_activity_a)
def init_automation_process_fan_out_activity_b_stream(service: Any, named: Any) -> None:
    service._service_streams.process_fan_out_activity_b = transformation.Map[str, str](named.streams.process_fan_out_activity_b, service._service_streams.consume_fan_out_activity_b, service.functions.process_fanout_activity_b)
def init_automation_process_fan_out_activity_c_stream(service: Any, named: Any) -> None:
    service._service_streams.process_fan_out_activity_c = transformation.Map[str, str](named.streams.process_fan_out_activity_c, service._service_streams.consume_fan_out_activity_c, service.functions.process_fanout_activity_c)
def init_automation_temporal_activity_schedule_stream(service: Any, named: Any) -> None:
    service._service_streams.temporal_activity_schedule = transformation.Input[str, str, Exception](named.streams.temporal_activity_schedule, service)
def init_automation_scheduled_activity_pause_stream(service: Any, named: Any) -> None:
    service._service_streams.scheduled_activity_pause = transformation.Delay[str](named.streams.scheduled_activity_pause, service._service_streams.temporal_activity_schedule, service.functions.scheduled_activity_pause)
def init_automation_process_scheduled_activity_stream(service: Any, named: Any) -> None:
    service._service_streams.process_scheduled_activity = transformation.Map[str, str](named.streams.process_scheduled_activity, service._service_streams.scheduled_activity_pause, service.functions.process_scheduled_activity)
def init_automation_temporal_workflow_schedule_stream(service: Any, named: Any) -> None:
    service._service_streams.temporal_workflow_schedule = transformation.Input[str, str, Exception](named.streams.temporal_workflow_schedule, service)
def init_automation_scheduled_workflow_pause_stream(service: Any, named: Any) -> None:
    service._service_streams.scheduled_workflow_pause = transformation.Delay[str](named.streams.scheduled_workflow_pause, service._service_streams.temporal_workflow_schedule, service.functions.scheduled_workflow_pause)
def init_automation_process_scheduled_workflow_stream(service: Any, named: Any) -> None:
    service._service_streams.process_scheduled_workflow = transformation.Map[str, str](named.streams.process_scheduled_workflow, service._service_streams.scheduled_workflow_pause, service.functions.process_scheduled_workflow)
def init_automation_process_sequential_activity_a_stream(service: Any, named: Any) -> None:
    service._service_streams.process_sequential_activity_a = transformation.Map[str, str](named.streams.process_sequential_activity_a, service._service_streams.consume_sequential_activity_a, service.functions.process_sequential_activity_a)
def init_automation_process_sequential_activity_b_stream(service: Any, named: Any) -> None:
    service._service_streams.process_sequential_activity_b = transformation.Map[str, str](named.streams.process_sequential_activity_b, service._service_streams.consume_sequential_activity_b, service.functions.process_sequential_activity_b)
def init_automation_process_workflow_job_stream(service: Any, named: Any) -> None:
    service._service_streams.process_workflow_job = transformation.Map[str, str](named.streams.process_workflow_job, service._service_streams.call_sequential_activity_b, service.functions.process_workflow_job)
def init_automation_submit_fan_out_workflow_job_stream(service: Any, named: Any) -> None:
    service._service_streams.submit_fan_out_workflow_job = transformation.Sink[str, Exception](named.streams.submit_fan_out_workflow_job, service._service_streams.split_on_demand_jobs.add_stream())
def post_init_automation_consume_activity_job_stream(service: Any) -> None:
    service._service_streams.consume_activity_job.set_source(service._service_streams.process_activity_job)
def post_init_automation_consume_workflow_job_stream(service: Any) -> None:
    service._service_streams.consume_workflow_job.set_source(service._service_streams.process_workflow_job)
def post_init_automation_consume_fan_out_activity_a_stream(service: Any) -> None:
    service._service_streams.consume_fan_out_activity_a.set_source(service._service_streams.process_fan_out_activity_a)
def post_init_automation_consume_fan_out_activity_b_stream(service: Any) -> None:
    service._service_streams.consume_fan_out_activity_b.set_source(service._service_streams.process_fan_out_activity_b)
def post_init_automation_consume_fan_out_activity_c_stream(service: Any) -> None:
    service._service_streams.consume_fan_out_activity_c.set_source(service._service_streams.process_fan_out_activity_c)
def post_init_automation_consume_sequential_activity_a_stream(service: Any) -> None:
    service._service_streams.consume_sequential_activity_a.set_source(service._service_streams.process_sequential_activity_a)
def post_init_automation_consume_sequential_activity_b_stream(service: Any) -> None:
    service._service_streams.consume_sequential_activity_b.set_source(service._service_streams.process_sequential_activity_b)
def post_init_automation_temporal_activity_schedule_stream(service: Any) -> None:
    service._service_streams.temporal_activity_schedule.set_source(service._service_streams.process_scheduled_activity)
def post_init_automation_temporal_workflow_schedule_stream(service: Any) -> None:
    service._service_streams.temporal_workflow_schedule.set_source(service._service_streams.process_scheduled_workflow)