"""Code generated by servicegen. DO NOT EDIT."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from datetime import timedelta
from typing import Any, Optional

from pyservicelib_gorundebug.runtime.context.context import Context
from pyservicelib_gorundebug.runtime.serviceapp import (
    ServiceApp,
    run_shutdown_operations,
)
from pyservicelib_gorundebug.runtime.serde import DataclassJsonSerde, Serializer
from pyservicelib_gorundebug.runtime.schedule import ScheduleTrigger
from pyservicelib_gorundebug import transformation
from pyservicelib_gorundebug.datasource import cron as cron_source
from pyservicelib_gorundebug.datasource import temporal as temporal_source
from pyservicelib_gorundebug.datasink import temporal as temporal_sink
from pyservicelib_gorundebug.runtime.temporal import make_connector as make_temporal_connector

from ..config import Config
from pyservicelib_gorundebug.runtime.environment import ServiceEnvironment
from pyservicelib_gorundebug.runtime.config.stream_types import MapStreamConfig
from pyservicelib_gorundebug.runtime.config.stream_types import MapStreamConfig
from pyservicelib_gorundebug.runtime.config.stream_types import MapStreamConfig
from automation_service.models.string import (
    String,
)
from pyservicelib_gorundebug.runtime.schedule import (
    ScheduleTrigger,
)
from ..functions import (
    LocalJob,
    make_local_job,
    ProcessDurableJob,
    make_process_durable_job,
    TemporalJob,
    make_temporal_job,
)


@dataclass(slots=True)
class ServiceStreams:
    consume_durable_job: Any = None
    local_schedule: Any = None
    make_local_job: Any = None
    temporal_schedule: Any = None
    make_temporal_job: Any = None
    merge_job_submissions: Any = None
    process_durable_job: Any = None
    submit_durable_job: Any = None

@dataclass(slots=True)
class ServiceMakers:
    local_job: Callable[[Context, ServiceEnvironment, MapStreamConfig], LocalJob] = (
        lambda ctx, environment, config: make_local_job(
            ctx, environment, config
        )
    )
    process_durable_job: Callable[[Context, ServiceEnvironment, MapStreamConfig], ProcessDurableJob] = (
        lambda ctx, environment, config: make_process_durable_job(
            ctx, environment, config
        )
    )
    temporal_job: Callable[[Context, ServiceEnvironment, MapStreamConfig], TemporalJob] = (
        lambda ctx, environment, config: make_temporal_job(
            ctx, environment, config
        )
    )


@dataclass(slots=True)
class ServiceFunctions:
    local_job: LocalJob
    process_durable_job: ProcessDurableJob
    temporal_job: TemporalJob


class GeneratedService(ServiceApp):
    """Generated lifecycle and graph bootstrap for Automation Service."""

    def __init__(self) -> None:
        super().__init__()
        self._makers = ServiceMakers()
        self._functions: ServiceFunctions | None = None
        self._service_streams = ServiceStreams()
        self._transport_consumers: list[Any] = []

    @property
    def makers(self) -> ServiceMakers:
        return self._makers

    @property
    def functions(self) -> ServiceFunctions:
        if self._functions is None:
            raise RuntimeError("service functions are not initialized")
        return self._functions

    def get_serde(self, type_name: str) -> Optional[Serializer]:
        if type_name == "ScheduleTrigger":
            return DataclassJsonSerde("ScheduleTrigger", ScheduleTrigger)
        return None

    async def initialize_functions(self, ctx: Context) -> None:
        """Apply user maker overrides, construct functions, then configure them."""

        await self.custom_makers_init(ctx)
        cfg = self.config
        if not isinstance(cfg, Config):
            raise TypeError(
                "Automation Service requires automation_service.internal.config.Config"
            )
        named = cfg.named
        self._functions = ServiceFunctions(
            local_job=self._makers.local_job(
                ctx, self, named.streams.make_local_job
            ),
            process_durable_job=self._makers.process_durable_job(
                ctx, self, named.streams.process_durable_job
            ),
            temporal_job=self._makers.temporal_job(
                ctx, self, named.streams.make_temporal_job
            ),
        )
        await self.custom_functions_init(ctx)

    async def build_stream_graph(self, ctx: Context) -> None:
        """Construct the configured stream graph with Go-compatible semantics."""

        await self.initialize_functions(ctx)
        cfg = self.config
        if not isinstance(cfg, Config):
            raise TypeError(
                "Automation Service requires automation_service.internal.config.Config"
            )
        named = cfg.named
        self._service_streams.consume_durable_job = transformation.Input[str, str, Exception](named.streams.consume_durable_job, self)
        self._service_streams.local_schedule = transformation.Input[ScheduleTrigger, object, Exception](named.streams.local_schedule, self)
        self._service_streams.make_local_job = transformation.Map[ScheduleTrigger, str](named.streams.make_local_job, self._service_streams.local_schedule, self.functions.local_job)
        self._service_streams.temporal_schedule = transformation.Input[ScheduleTrigger, object, Exception](named.streams.temporal_schedule, self)
        self._service_streams.make_temporal_job = transformation.Map[ScheduleTrigger, str](named.streams.make_temporal_job, self._service_streams.temporal_schedule, self.functions.temporal_job)
        self._service_streams.merge_job_submissions = transformation.Merge[str](named.streams.merge_job_submissions, self._service_streams.make_local_job, self._service_streams.make_temporal_job)
        self._service_streams.process_durable_job = transformation.Map[str, str](named.streams.process_durable_job, self._service_streams.consume_durable_job, self.functions.process_durable_job)
        self._service_streams.submit_durable_job = transformation.Sink[str, Exception](named.streams.submit_durable_job, self._service_streams.merge_job_submissions)
        self._service_streams.consume_durable_job.set_source(self._service_streams.process_durable_job)

    def bind_transports(self) -> None:
        """Bind configured endpoints to the already constructed streams."""

        cfg = self.config
        if not isinstance(cfg, Config):
            raise TypeError(
                "Automation Service requires automation_service.internal.config.Config"
            )
        self._transport_consumers = []
        consume_durable_job_consumer = temporal_source.make_direct_endpoint_consumer(self._service_streams.consume_durable_job)
        self._transport_consumers.append(consume_durable_job_consumer)
        local_schedule_consumer = cron_source.APSchedulerEndpointConsumer(self._service_streams.local_schedule)
        self._transport_consumers.append(local_schedule_consumer)
        submit_durable_job_consumer = temporal_sink.make_direct_endpoint_consumer(self._service_streams.submit_durable_job)
        self._transport_consumers.append(submit_durable_job_consumer)
        temporal_schedule_consumer = temporal_source.make_schedule_endpoint_consumer(self._service_streams.temporal_schedule)
        self._transport_consumers.append(temporal_schedule_consumer)
    def initialize_runtime_connectors(self) -> None:
        cfg = self.config
        if not isinstance(cfg, Config):
            raise TypeError(
                "Automation Service requires automation_service.internal.config.Config"
            )
        named = cfg.named
        make_temporal_connector(named.data_connectors.temporal.id, self)

    async def build_runtime(self, ctx: Context) -> None:
        self.initialize_runtime_connectors()
        await self.build_stream_graph(ctx)
        self.bind_transports()

    async def start_service(self, ctx: Context) -> None:
        await self.build_runtime(ctx)
        await self.on_start(ctx)
        await self.start(ctx)

    async def stop_service(self, ctx: Context) -> None:
        ctx = ctx.bounded(
            timedelta(milliseconds=self.service_config.shutdown_timeout)
        )

        await run_shutdown_operations(
            self.log,
            ctx,
            [
                ("user_on_stop", self.on_stop(ctx)),
                ("service_runtime", self.stop(ctx)),
            ],
        )

    async def custom_makers_init(self, ctx: Context) -> None:
        del ctx

    async def custom_functions_init(self, ctx: Context) -> None:
        del ctx

    async def on_start(self, ctx: Context) -> None:
        del ctx

    async def on_stop(self, ctx: Context) -> None:
        del ctx