"""Code generated by servicegen. DO NOT EDIT."""

from __future__ import annotations

from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from pyservicelib_gorundebug.runtime.context.context import Context
from pyservicelib_gorundebug.runtime.environment import ServiceEnvironment
from ..functions import (
    ActivityJobEndpointSink,
    make_activity_job_endpoint_sink,
    ActivityJobEndpointSource,
    make_activity_job_endpoint_source,
    FanoutActivityAEndpointSink,
    make_fanout_activity_a_endpoint_sink,
    FanoutActivityAEndpointSource,
    make_fanout_activity_a_endpoint_source,
    FanoutActivityBEndpointSink,
    make_fanout_activity_b_endpoint_sink,
    FanoutActivityBEndpointSource,
    make_fanout_activity_b_endpoint_source,
    FanoutActivityCEndpointSink,
    make_fanout_activity_c_endpoint_sink,
    FanoutActivityCEndpointSource,
    make_fanout_activity_c_endpoint_source,
    SequentialActivityAEndpointSink,
    make_sequential_activity_a_endpoint_sink,
    SequentialActivityAEndpointSource,
    make_sequential_activity_a_endpoint_source,
    SequentialActivityBEndpointSink,
    make_sequential_activity_b_endpoint_sink,
    SequentialActivityBEndpointSource,
    make_sequential_activity_b_endpoint_source,
    TemporalActivityScheduleSource,
    make_temporal_activity_schedule_source,
    ActivityPause,
    make_activity_pause,
    ObserveActivityResult,
    make_observe_activity_result,
    ObserveFanoutActivityB,
    make_observe_fanout_activity_b,
    ObserveFanoutActivityC,
    make_observe_fanout_activity_c,
    ObserveWorkflowResult,
    make_observe_workflow_result,
    ProcessActivityJob,
    make_process_activity_job,
    ProcessFanoutActivityA,
    make_process_fanout_activity_a,
    ProcessFanoutActivityB,
    make_process_fanout_activity_b,
    ProcessFanoutActivityC,
    make_process_fanout_activity_c,
    ProcessScheduledActivity,
    make_process_scheduled_activity,
    ProcessScheduledWorkflow,
    make_process_scheduled_workflow,
    ProcessSequentialActivityA,
    make_process_sequential_activity_a,
    ProcessSequentialActivityB,
    make_process_sequential_activity_b,
    ProcessWorkflowJob,
    make_process_workflow_job,
    ScheduledActivityPause,
    make_scheduled_activity_pause,
    ScheduledWorkflowPause,
    make_scheduled_workflow_pause,
    WorkflowPause,
    make_workflow_pause,
    LocalScheduleSource,
    make_local_schedule_source,
    FanoutWorkflowJobEndpointSink,
    make_fanout_workflow_job_endpoint_sink,
    FanoutWorkflowJobEndpointSource,
    make_fanout_workflow_job_endpoint_source,
    TemporalWorkflowScheduleSource,
    make_temporal_workflow_schedule_source,
    WorkflowJobEndpointSink,
    make_workflow_job_endpoint_sink,
    WorkflowJobEndpointSource,
    make_workflow_job_endpoint_source,
)


@dataclass(slots=True)
class ServiceMakers:
    activity_job_endpoint_sink: Callable[[Context, ServiceEnvironment], Awaitable[ActivityJobEndpointSink]] = make_activity_job_endpoint_sink
    activity_job_endpoint_source: Callable[[Context, ServiceEnvironment], Awaitable[ActivityJobEndpointSource]] = make_activity_job_endpoint_source
    fanout_activity_a_endpoint_sink: Callable[[Context, ServiceEnvironment], Awaitable[FanoutActivityAEndpointSink]] = make_fanout_activity_a_endpoint_sink
    fanout_activity_a_endpoint_source: Callable[[Context, ServiceEnvironment], Awaitable[FanoutActivityAEndpointSource]] = make_fanout_activity_a_endpoint_source
    fanout_activity_b_endpoint_sink: Callable[[Context, ServiceEnvironment], Awaitable[FanoutActivityBEndpointSink]] = make_fanout_activity_b_endpoint_sink
    fanout_activity_b_endpoint_source: Callable[[Context, ServiceEnvironment], Awaitable[FanoutActivityBEndpointSource]] = make_fanout_activity_b_endpoint_source
    fanout_activity_c_endpoint_sink: Callable[[Context, ServiceEnvironment], Awaitable[FanoutActivityCEndpointSink]] = make_fanout_activity_c_endpoint_sink
    fanout_activity_c_endpoint_source: Callable[[Context, ServiceEnvironment], Awaitable[FanoutActivityCEndpointSource]] = make_fanout_activity_c_endpoint_source
    sequential_activity_a_endpoint_sink: Callable[[Context, ServiceEnvironment], Awaitable[SequentialActivityAEndpointSink]] = make_sequential_activity_a_endpoint_sink
    sequential_activity_a_endpoint_source: Callable[[Context, ServiceEnvironment], Awaitable[SequentialActivityAEndpointSource]] = make_sequential_activity_a_endpoint_source
    sequential_activity_b_endpoint_sink: Callable[[Context, ServiceEnvironment], Awaitable[SequentialActivityBEndpointSink]] = make_sequential_activity_b_endpoint_sink
    sequential_activity_b_endpoint_source: Callable[[Context, ServiceEnvironment], Awaitable[SequentialActivityBEndpointSource]] = make_sequential_activity_b_endpoint_source
    temporal_activity_schedule_source: Callable[[Context, ServiceEnvironment], Awaitable[TemporalActivityScheduleSource]] = make_temporal_activity_schedule_source
    activity_pause: Callable[[Context, ServiceEnvironment], Awaitable[ActivityPause]] = make_activity_pause
    observe_activity_result: Callable[[Context, ServiceEnvironment], Awaitable[ObserveActivityResult]] = make_observe_activity_result
    observe_fanout_activity_b: Callable[[Context, ServiceEnvironment], Awaitable[ObserveFanoutActivityB]] = make_observe_fanout_activity_b
    observe_fanout_activity_c: Callable[[Context, ServiceEnvironment], Awaitable[ObserveFanoutActivityC]] = make_observe_fanout_activity_c
    observe_workflow_result: Callable[[Context, ServiceEnvironment], Awaitable[ObserveWorkflowResult]] = make_observe_workflow_result
    process_activity_job: Callable[[Context, ServiceEnvironment], Awaitable[ProcessActivityJob]] = make_process_activity_job
    process_fanout_activity_a: Callable[[Context, ServiceEnvironment], Awaitable[ProcessFanoutActivityA]] = make_process_fanout_activity_a
    process_fanout_activity_b: Callable[[Context, ServiceEnvironment], Awaitable[ProcessFanoutActivityB]] = make_process_fanout_activity_b
    process_fanout_activity_c: Callable[[Context, ServiceEnvironment], Awaitable[ProcessFanoutActivityC]] = make_process_fanout_activity_c
    process_scheduled_activity: Callable[[Context, ServiceEnvironment], Awaitable[ProcessScheduledActivity]] = make_process_scheduled_activity
    process_scheduled_workflow: Callable[[Context, ServiceEnvironment], Awaitable[ProcessScheduledWorkflow]] = make_process_scheduled_workflow
    process_sequential_activity_a: Callable[[Context, ServiceEnvironment], Awaitable[ProcessSequentialActivityA]] = make_process_sequential_activity_a
    process_sequential_activity_b: Callable[[Context, ServiceEnvironment], Awaitable[ProcessSequentialActivityB]] = make_process_sequential_activity_b
    process_workflow_job: Callable[[Context, ServiceEnvironment], Awaitable[ProcessWorkflowJob]] = make_process_workflow_job
    scheduled_activity_pause: Callable[[Context, ServiceEnvironment], Awaitable[ScheduledActivityPause]] = make_scheduled_activity_pause
    scheduled_workflow_pause: Callable[[Context, ServiceEnvironment], Awaitable[ScheduledWorkflowPause]] = make_scheduled_workflow_pause
    workflow_pause: Callable[[Context, ServiceEnvironment], Awaitable[WorkflowPause]] = make_workflow_pause
    local_schedule_source: Callable[[Context, ServiceEnvironment], Awaitable[LocalScheduleSource]] = make_local_schedule_source
    fanout_workflow_job_endpoint_sink: Callable[[Context, ServiceEnvironment], Awaitable[FanoutWorkflowJobEndpointSink]] = make_fanout_workflow_job_endpoint_sink
    fanout_workflow_job_endpoint_source: Callable[[Context, ServiceEnvironment], Awaitable[FanoutWorkflowJobEndpointSource]] = make_fanout_workflow_job_endpoint_source
    temporal_workflow_schedule_source: Callable[[Context, ServiceEnvironment], Awaitable[TemporalWorkflowScheduleSource]] = make_temporal_workflow_schedule_source
    workflow_job_endpoint_sink: Callable[[Context, ServiceEnvironment], Awaitable[WorkflowJobEndpointSink]] = make_workflow_job_endpoint_sink
    workflow_job_endpoint_source: Callable[[Context, ServiceEnvironment], Awaitable[WorkflowJobEndpointSource]] = make_workflow_job_endpoint_source