"""Code generated by servicegen. DO NOT EDIT.

Workflow-isolate-safe construction of the ordinary service graph.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

from pyservicelib_gorundebug import transformation
from pyservicelib_gorundebug.runtime.context.context import Context
from pyservicelib_gorundebug.runtime.environment import ServiceEnvironment
from pyservicelib_gorundebug.runtime.serde import DataclassJsonSerde

from ..config import Config
from pyservicelib_gorundebug.runtime.config.endpoint_types import CronEndpointConfig, TemporalEndpointConfig
from pyservicelib_gorundebug.runtime.config.stream_types import DelayStreamConfig, MapStreamConfig
from model.models.automation_job_generated import (
    AutomationJob,
)
from ..functions import (
    ActivityJobEndpointSink,
    make_activity_job_endpoint_sink,
    ActivityJobEndpointSource,
    make_activity_job_endpoint_source,
    FanoutActivityAEndpointSink,
    make_fanout_activity_a_endpoint_sink,
    FanoutActivityAEndpointSource,
    make_fanout_activity_a_endpoint_source,
    FanoutActivityBEndpointSink,
    make_fanout_activity_b_endpoint_sink,
    FanoutActivityBEndpointSource,
    make_fanout_activity_b_endpoint_source,
    FanoutActivityCEndpointSink,
    make_fanout_activity_c_endpoint_sink,
    FanoutActivityCEndpointSource,
    make_fanout_activity_c_endpoint_source,
    SequentialActivityAEndpointSink,
    make_sequential_activity_a_endpoint_sink,
    SequentialActivityAEndpointSource,
    make_sequential_activity_a_endpoint_source,
    SequentialActivityBEndpointSink,
    make_sequential_activity_b_endpoint_sink,
    SequentialActivityBEndpointSource,
    make_sequential_activity_b_endpoint_source,
    TemporalActivityScheduleSource,
    make_temporal_activity_schedule_source,
    ActivityPause,
    make_activity_pause,
    ObserveActivityResult,
    make_observe_activity_result,
    ObserveFanoutActivityB,
    make_observe_fanout_activity_b,
    ObserveFanoutActivityC,
    make_observe_fanout_activity_c,
    ObserveWorkflowResult,
    make_observe_workflow_result,
    ProcessActivityJob,
    make_process_activity_job,
    ProcessFanoutActivityA,
    make_process_fanout_activity_a,
    ProcessFanoutActivityB,
    make_process_fanout_activity_b,
    ProcessFanoutActivityC,
    make_process_fanout_activity_c,
    ProcessScheduledActivity,
    make_process_scheduled_activity,
    ProcessScheduledWorkflow,
    make_process_scheduled_workflow,
    ProcessSequentialActivityA,
    make_process_sequential_activity_a,
    ProcessSequentialActivityB,
    make_process_sequential_activity_b,
    ProcessWorkflowJob,
    make_process_workflow_job,
    ScheduledActivityPause,
    make_scheduled_activity_pause,
    ScheduledWorkflowPause,
    make_scheduled_workflow_pause,
    WorkflowPause,
    make_workflow_pause,
    LocalScheduleSource,
    make_local_schedule_source,
    FanoutWorkflowJobEndpointSink,
    make_fanout_workflow_job_endpoint_sink,
    FanoutWorkflowJobEndpointSource,
    make_fanout_workflow_job_endpoint_source,
    TemporalWorkflowScheduleSource,
    make_temporal_workflow_schedule_source,
    WorkflowJobEndpointSink,
    make_workflow_job_endpoint_sink,
    WorkflowJobEndpointSource,
    make_workflow_job_endpoint_source,
)


@dataclass(slots=True)
class ServiceStreams:
    consume_activity_job: Any = None
    activity_pause: Any = None
    consume_fan_out_workflow_job: Any = None
    call_fan_out_activity_a: Any = None
    split_activity_a_result: Any = None
    call_fan_out_activity_b: Any = None
    call_fan_out_activity_c: Any = None
    consume_workflow_job: Any = None
    workflow_pause: Any = None
    call_sequential_activity_a: Any = None
    call_sequential_activity_b: Any = None
    consume_fan_out_activity_a: Any = None
    consume_fan_out_activity_b: Any = None
    consume_fan_out_activity_c: Any = None
    consume_sequential_activity_a: Any = None
    consume_sequential_activity_b: Any = None
    local_schedule: Any = None
    split_on_demand_jobs: Any = None
    submit_activity_job: Any = None
    observe_activity_result: Any = None
    observe_fan_out_activity_b: Any = None
    observe_fan_out_activity_c: Any = None
    submit_workflow_job: Any = None
    observe_workflow_result: Any = None
    process_activity_job: Any = None
    process_fan_out_activity_a: Any = None
    process_fan_out_activity_b: Any = None
    process_fan_out_activity_c: Any = None
    temporal_activity_schedule: Any = None
    scheduled_activity_pause: Any = None
    process_scheduled_activity: Any = None
    temporal_workflow_schedule: Any = None
    scheduled_workflow_pause: Any = None
    process_scheduled_workflow: Any = None
    process_sequential_activity_a: Any = None
    process_sequential_activity_b: Any = None
    process_workflow_job: Any = None
    submit_fan_out_workflow_job: Any = None


@dataclass(slots=True)
class ServiceMakers:
    activity_job_endpoint_sink: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], ActivityJobEndpointSink] = (
        lambda ctx, environment, config: make_activity_job_endpoint_sink(
            ctx, environment, config
        )
    )
    activity_job_endpoint_source: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], ActivityJobEndpointSource] = (
        lambda ctx, environment, config: make_activity_job_endpoint_source(
            ctx, environment, config
        )
    )
    fanout_activity_a_endpoint_sink: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], FanoutActivityAEndpointSink] = (
        lambda ctx, environment, config: make_fanout_activity_a_endpoint_sink(
            ctx, environment, config
        )
    )
    fanout_activity_a_endpoint_source: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], FanoutActivityAEndpointSource] = (
        lambda ctx, environment, config: make_fanout_activity_a_endpoint_source(
            ctx, environment, config
        )
    )
    fanout_activity_b_endpoint_sink: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], FanoutActivityBEndpointSink] = (
        lambda ctx, environment, config: make_fanout_activity_b_endpoint_sink(
            ctx, environment, config
        )
    )
    fanout_activity_b_endpoint_source: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], FanoutActivityBEndpointSource] = (
        lambda ctx, environment, config: make_fanout_activity_b_endpoint_source(
            ctx, environment, config
        )
    )
    fanout_activity_c_endpoint_sink: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], FanoutActivityCEndpointSink] = (
        lambda ctx, environment, config: make_fanout_activity_c_endpoint_sink(
            ctx, environment, config
        )
    )
    fanout_activity_c_endpoint_source: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], FanoutActivityCEndpointSource] = (
        lambda ctx, environment, config: make_fanout_activity_c_endpoint_source(
            ctx, environment, config
        )
    )
    sequential_activity_a_endpoint_sink: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], SequentialActivityAEndpointSink] = (
        lambda ctx, environment, config: make_sequential_activity_a_endpoint_sink(
            ctx, environment, config
        )
    )
    sequential_activity_a_endpoint_source: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], SequentialActivityAEndpointSource] = (
        lambda ctx, environment, config: make_sequential_activity_a_endpoint_source(
            ctx, environment, config
        )
    )
    sequential_activity_b_endpoint_sink: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], SequentialActivityBEndpointSink] = (
        lambda ctx, environment, config: make_sequential_activity_b_endpoint_sink(
            ctx, environment, config
        )
    )
    sequential_activity_b_endpoint_source: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], SequentialActivityBEndpointSource] = (
        lambda ctx, environment, config: make_sequential_activity_b_endpoint_source(
            ctx, environment, config
        )
    )
    temporal_activity_schedule_source: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], TemporalActivityScheduleSource] = (
        lambda ctx, environment, config: make_temporal_activity_schedule_source(
            ctx, environment, config
        )
    )
    activity_pause: Callable[[Context, ServiceEnvironment, DelayStreamConfig], ActivityPause] = (
        lambda ctx, environment, config: make_activity_pause(
            ctx, environment, config
        )
    )
    observe_activity_result: Callable[[Context, ServiceEnvironment, MapStreamConfig], ObserveActivityResult] = (
        lambda ctx, environment, config: make_observe_activity_result(
            ctx, environment, config
        )
    )
    observe_fanout_activity_b: Callable[[Context, ServiceEnvironment, MapStreamConfig], ObserveFanoutActivityB] = (
        lambda ctx, environment, config: make_observe_fanout_activity_b(
            ctx, environment, config
        )
    )
    observe_fanout_activity_c: Callable[[Context, ServiceEnvironment, MapStreamConfig], ObserveFanoutActivityC] = (
        lambda ctx, environment, config: make_observe_fanout_activity_c(
            ctx, environment, config
        )
    )
    observe_workflow_result: Callable[[Context, ServiceEnvironment, MapStreamConfig], ObserveWorkflowResult] = (
        lambda ctx, environment, config: make_observe_workflow_result(
            ctx, environment, config
        )
    )
    process_activity_job: Callable[[Context, ServiceEnvironment, MapStreamConfig], ProcessActivityJob] = (
        lambda ctx, environment, config: make_process_activity_job(
            ctx, environment, config
        )
    )
    process_fanout_activity_a: Callable[[Context, ServiceEnvironment, MapStreamConfig], ProcessFanoutActivityA] = (
        lambda ctx, environment, config: make_process_fanout_activity_a(
            ctx, environment, config
        )
    )
    process_fanout_activity_b: Callable[[Context, ServiceEnvironment, MapStreamConfig], ProcessFanoutActivityB] = (
        lambda ctx, environment, config: make_process_fanout_activity_b(
            ctx, environment, config
        )
    )
    process_fanout_activity_c: Callable[[Context, ServiceEnvironment, MapStreamConfig], ProcessFanoutActivityC] = (
        lambda ctx, environment, config: make_process_fanout_activity_c(
            ctx, environment, config
        )
    )
    process_scheduled_activity: Callable[[Context, ServiceEnvironment, MapStreamConfig], ProcessScheduledActivity] = (
        lambda ctx, environment, config: make_process_scheduled_activity(
            ctx, environment, config
        )
    )
    process_scheduled_workflow: Callable[[Context, ServiceEnvironment, MapStreamConfig], ProcessScheduledWorkflow] = (
        lambda ctx, environment, config: make_process_scheduled_workflow(
            ctx, environment, config
        )
    )
    process_sequential_activity_a: Callable[[Context, ServiceEnvironment, MapStreamConfig], ProcessSequentialActivityA] = (
        lambda ctx, environment, config: make_process_sequential_activity_a(
            ctx, environment, config
        )
    )
    process_sequential_activity_b: Callable[[Context, ServiceEnvironment, MapStreamConfig], ProcessSequentialActivityB] = (
        lambda ctx, environment, config: make_process_sequential_activity_b(
            ctx, environment, config
        )
    )
    process_workflow_job: Callable[[Context, ServiceEnvironment, MapStreamConfig], ProcessWorkflowJob] = (
        lambda ctx, environment, config: make_process_workflow_job(
            ctx, environment, config
        )
    )
    scheduled_activity_pause: Callable[[Context, ServiceEnvironment, DelayStreamConfig], ScheduledActivityPause] = (
        lambda ctx, environment, config: make_scheduled_activity_pause(
            ctx, environment, config
        )
    )
    scheduled_workflow_pause: Callable[[Context, ServiceEnvironment, DelayStreamConfig], ScheduledWorkflowPause] = (
        lambda ctx, environment, config: make_scheduled_workflow_pause(
            ctx, environment, config
        )
    )
    workflow_pause: Callable[[Context, ServiceEnvironment, DelayStreamConfig], WorkflowPause] = (
        lambda ctx, environment, config: make_workflow_pause(
            ctx, environment, config
        )
    )
    local_schedule_source: Callable[[Context, ServiceEnvironment, CronEndpointConfig], LocalScheduleSource] = (
        lambda ctx, environment, config: make_local_schedule_source(
            ctx, environment, config
        )
    )
    fanout_workflow_job_endpoint_sink: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], FanoutWorkflowJobEndpointSink] = (
        lambda ctx, environment, config: make_fanout_workflow_job_endpoint_sink(
            ctx, environment, config
        )
    )
    fanout_workflow_job_endpoint_source: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], FanoutWorkflowJobEndpointSource] = (
        lambda ctx, environment, config: make_fanout_workflow_job_endpoint_source(
            ctx, environment, config
        )
    )
    temporal_workflow_schedule_source: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], TemporalWorkflowScheduleSource] = (
        lambda ctx, environment, config: make_temporal_workflow_schedule_source(
            ctx, environment, config
        )
    )
    workflow_job_endpoint_sink: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], WorkflowJobEndpointSink] = (
        lambda ctx, environment, config: make_workflow_job_endpoint_sink(
            ctx, environment, config
        )
    )
    workflow_job_endpoint_source: Callable[[Context, ServiceEnvironment, TemporalEndpointConfig], WorkflowJobEndpointSource] = (
        lambda ctx, environment, config: make_workflow_job_endpoint_source(
            ctx, environment, config
        )
    )


@dataclass(slots=True)
class ServiceFunctions:
    activity_job_endpoint_sink: ActivityJobEndpointSink
    activity_job_endpoint_source: ActivityJobEndpointSource
    fanout_activity_a_endpoint_sink: FanoutActivityAEndpointSink
    fanout_activity_a_endpoint_source: FanoutActivityAEndpointSource
    fanout_activity_b_endpoint_sink: FanoutActivityBEndpointSink
    fanout_activity_b_endpoint_source: FanoutActivityBEndpointSource
    fanout_activity_c_endpoint_sink: FanoutActivityCEndpointSink
    fanout_activity_c_endpoint_source: FanoutActivityCEndpointSource
    sequential_activity_a_endpoint_sink: SequentialActivityAEndpointSink
    sequential_activity_a_endpoint_source: SequentialActivityAEndpointSource
    sequential_activity_b_endpoint_sink: SequentialActivityBEndpointSink
    sequential_activity_b_endpoint_source: SequentialActivityBEndpointSource
    temporal_activity_schedule_source: TemporalActivityScheduleSource
    activity_pause: ActivityPause
    observe_activity_result: ObserveActivityResult
    observe_fanout_activity_b: ObserveFanoutActivityB
    observe_fanout_activity_c: ObserveFanoutActivityC
    observe_workflow_result: ObserveWorkflowResult
    process_activity_job: ProcessActivityJob
    process_fanout_activity_a: ProcessFanoutActivityA
    process_fanout_activity_b: ProcessFanoutActivityB
    process_fanout_activity_c: ProcessFanoutActivityC
    process_scheduled_activity: ProcessScheduledActivity
    process_scheduled_workflow: ProcessScheduledWorkflow
    process_sequential_activity_a: ProcessSequentialActivityA
    process_sequential_activity_b: ProcessSequentialActivityB
    process_workflow_job: ProcessWorkflowJob
    scheduled_activity_pause: ScheduledActivityPause
    scheduled_workflow_pause: ScheduledWorkflowPause
    workflow_pause: WorkflowPause
    local_schedule_source: LocalScheduleSource
    fanout_workflow_job_endpoint_sink: FanoutWorkflowJobEndpointSink
    fanout_workflow_job_endpoint_source: FanoutWorkflowJobEndpointSource
    temporal_workflow_schedule_source: TemporalWorkflowScheduleSource
    workflow_job_endpoint_sink: WorkflowJobEndpointSink
    workflow_job_endpoint_source: WorkflowJobEndpointSource


def register_generated_serdes(environment: Any) -> None:
    del environment


def default_makers() -> ServiceMakers:
    return ServiceMakers()


def init_functions(
    ctx: Context,
    config: Config,
    environment: ServiceEnvironment,
    makers: ServiceMakers,
) -> ServiceFunctions:
    named = config.named
    return ServiceFunctions(
        activity_job_endpoint_sink=makers.activity_job_endpoint_sink(
            ctx, environment, named.endpoints.activity_job
        ),
        activity_job_endpoint_source=makers.activity_job_endpoint_source(
            ctx, environment, named.endpoints.activity_job
        ),
        fanout_activity_a_endpoint_sink=makers.fanout_activity_a_endpoint_sink(
            ctx, environment, named.endpoints.fan_out_activity_a
        ),
        fanout_activity_a_endpoint_source=makers.fanout_activity_a_endpoint_source(
            ctx, environment, named.endpoints.fan_out_activity_a
        ),
        fanout_activity_b_endpoint_sink=makers.fanout_activity_b_endpoint_sink(
            ctx, environment, named.endpoints.fan_out_activity_b
        ),
        fanout_activity_b_endpoint_source=makers.fanout_activity_b_endpoint_source(
            ctx, environment, named.endpoints.fan_out_activity_b
        ),
        fanout_activity_c_endpoint_sink=makers.fanout_activity_c_endpoint_sink(
            ctx, environment, named.endpoints.fan_out_activity_c
        ),
        fanout_activity_c_endpoint_source=makers.fanout_activity_c_endpoint_source(
            ctx, environment, named.endpoints.fan_out_activity_c
        ),
        sequential_activity_a_endpoint_sink=makers.sequential_activity_a_endpoint_sink(
            ctx, environment, named.endpoints.sequential_activity_a
        ),
        sequential_activity_a_endpoint_source=makers.sequential_activity_a_endpoint_source(
            ctx, environment, named.endpoints.sequential_activity_a
        ),
        sequential_activity_b_endpoint_sink=makers.sequential_activity_b_endpoint_sink(
            ctx, environment, named.endpoints.sequential_activity_b
        ),
        sequential_activity_b_endpoint_source=makers.sequential_activity_b_endpoint_source(
            ctx, environment, named.endpoints.sequential_activity_b
        ),
        temporal_activity_schedule_source=makers.temporal_activity_schedule_source(
            ctx, environment, named.endpoints.temporal_activity_schedule
        ),
        activity_pause=makers.activity_pause(
            ctx, environment, named.streams.activity_pause
        ),
        observe_activity_result=makers.observe_activity_result(
            ctx, environment, named.streams.observe_activity_result
        ),
        observe_fanout_activity_b=makers.observe_fanout_activity_b(
            ctx, environment, named.streams.observe_fan_out_activity_b
        ),
        observe_fanout_activity_c=makers.observe_fanout_activity_c(
            ctx, environment, named.streams.observe_fan_out_activity_c
        ),
        observe_workflow_result=makers.observe_workflow_result(
            ctx, environment, named.streams.observe_workflow_result
        ),
        process_activity_job=makers.process_activity_job(
            ctx, environment, named.streams.process_activity_job
        ),
        process_fanout_activity_a=makers.process_fanout_activity_a(
            ctx, environment, named.streams.process_fan_out_activity_a
        ),
        process_fanout_activity_b=makers.process_fanout_activity_b(
            ctx, environment, named.streams.process_fan_out_activity_b
        ),
        process_fanout_activity_c=makers.process_fanout_activity_c(
            ctx, environment, named.streams.process_fan_out_activity_c
        ),
        process_scheduled_activity=makers.process_scheduled_activity(
            ctx, environment, named.streams.process_scheduled_activity
        ),
        process_scheduled_workflow=makers.process_scheduled_workflow(
            ctx, environment, named.streams.process_scheduled_workflow
        ),
        process_sequential_activity_a=makers.process_sequential_activity_a(
            ctx, environment, named.streams.process_sequential_activity_a
        ),
        process_sequential_activity_b=makers.process_sequential_activity_b(
            ctx, environment, named.streams.process_sequential_activity_b
        ),
        process_workflow_job=makers.process_workflow_job(
            ctx, environment, named.streams.process_workflow_job
        ),
        scheduled_activity_pause=makers.scheduled_activity_pause(
            ctx, environment, named.streams.scheduled_activity_pause
        ),
        scheduled_workflow_pause=makers.scheduled_workflow_pause(
            ctx, environment, named.streams.scheduled_workflow_pause
        ),
        workflow_pause=makers.workflow_pause(
            ctx, environment, named.streams.workflow_pause
        ),
        local_schedule_source=makers.local_schedule_source(
            ctx, environment, named.endpoints.local_schedule
        ),
        fanout_workflow_job_endpoint_sink=makers.fanout_workflow_job_endpoint_sink(
            ctx, environment, named.endpoints.fan_out_workflow_job
        ),
        fanout_workflow_job_endpoint_source=makers.fanout_workflow_job_endpoint_source(
            ctx, environment, named.endpoints.fan_out_workflow_job
        ),
        temporal_workflow_schedule_source=makers.temporal_workflow_schedule_source(
            ctx, environment, named.endpoints.temporal_workflow_schedule
        ),
        workflow_job_endpoint_sink=makers.workflow_job_endpoint_sink(
            ctx, environment, named.endpoints.workflow_job
        ),
        workflow_job_endpoint_source=makers.workflow_job_endpoint_source(
            ctx, environment, named.endpoints.workflow_job
        ),
    )


def init_streams(
    config: Config,
    environment: Any,
    functions: ServiceFunctions,
) -> ServiceStreams:
    named = config.named
    streams = ServiceStreams()
    streams.consume_activity_job = transformation.Input[str, str, Exception](named.streams.consume_activity_job, environment)
    streams.activity_pause = transformation.Delay[str](named.streams.activity_pause, streams.consume_activity_job, functions.activity_pause)
    streams.consume_fan_out_workflow_job = transformation.Input[str, object, Exception](named.streams.consume_fan_out_workflow_job, environment)
    streams.call_fan_out_activity_a = transformation.SinkWithResult[str, str, Exception](named.streams.call_fan_out_activity_a, streams.consume_fan_out_workflow_job)
    streams.split_activity_a_result = transformation.Split[str](named.streams.split_activity_a_result, streams.call_fan_out_activity_a)
    streams.call_fan_out_activity_b = transformation.SinkWithResult[str, str, Exception](named.streams.call_fan_out_activity_b, streams.split_activity_a_result.add_stream())
    streams.call_fan_out_activity_c = transformation.SinkWithResult[str, str, Exception](named.streams.call_fan_out_activity_c, streams.split_activity_a_result.add_stream())
    streams.consume_workflow_job = transformation.Input[str, str, Exception](named.streams.consume_workflow_job, environment)
    streams.workflow_pause = transformation.Delay[str](named.streams.workflow_pause, streams.consume_workflow_job, functions.workflow_pause)
    streams.call_sequential_activity_a = transformation.SinkWithResult[str, str, Exception](named.streams.call_sequential_activity_a, streams.workflow_pause)
    streams.call_sequential_activity_b = transformation.SinkWithResult[str, str, Exception](named.streams.call_sequential_activity_b, streams.call_sequential_activity_a)
    streams.consume_fan_out_activity_a = transformation.Input[str, str, Exception](named.streams.consume_fan_out_activity_a, environment)
    streams.consume_fan_out_activity_b = transformation.Input[str, str, Exception](named.streams.consume_fan_out_activity_b, environment)
    streams.consume_fan_out_activity_c = transformation.Input[str, str, Exception](named.streams.consume_fan_out_activity_c, environment)
    streams.consume_sequential_activity_a = transformation.Input[str, str, Exception](named.streams.consume_sequential_activity_a, environment)
    streams.consume_sequential_activity_b = transformation.Input[str, str, Exception](named.streams.consume_sequential_activity_b, environment)
    streams.local_schedule = transformation.Input[str, object, Exception](named.streams.local_schedule, environment)
    streams.split_on_demand_jobs = transformation.Split[str](named.streams.split_on_demand_jobs, streams.local_schedule)
    streams.submit_activity_job = transformation.SinkWithResult[str, str, Exception](named.streams.submit_activity_job, streams.split_on_demand_jobs.add_stream())
    streams.observe_activity_result = transformation.Map[str, str](named.streams.observe_activity_result, streams.submit_activity_job, functions.observe_activity_result)
    streams.observe_fan_out_activity_b = transformation.Map[str, str](named.streams.observe_fan_out_activity_b, streams.call_fan_out_activity_b, functions.observe_fanout_activity_b)
    streams.observe_fan_out_activity_c = transformation.Map[str, str](named.streams.observe_fan_out_activity_c, streams.call_fan_out_activity_c, functions.observe_fanout_activity_c)
    streams.submit_workflow_job = transformation.SinkWithResult[str, str, Exception](named.streams.submit_workflow_job, streams.split_on_demand_jobs.add_stream())
    streams.observe_workflow_result = transformation.Map[str, str](named.streams.observe_workflow_result, streams.submit_workflow_job, functions.observe_workflow_result)
    streams.process_activity_job = transformation.Map[str, str](named.streams.process_activity_job, streams.activity_pause, functions.process_activity_job)
    streams.process_fan_out_activity_a = transformation.Map[str, str](named.streams.process_fan_out_activity_a, streams.consume_fan_out_activity_a, functions.process_fanout_activity_a)
    streams.process_fan_out_activity_b = transformation.Map[str, str](named.streams.process_fan_out_activity_b, streams.consume_fan_out_activity_b, functions.process_fanout_activity_b)
    streams.process_fan_out_activity_c = transformation.Map[str, str](named.streams.process_fan_out_activity_c, streams.consume_fan_out_activity_c, functions.process_fanout_activity_c)
    streams.temporal_activity_schedule = transformation.Input[str, str, Exception](named.streams.temporal_activity_schedule, environment)
    streams.scheduled_activity_pause = transformation.Delay[str](named.streams.scheduled_activity_pause, streams.temporal_activity_schedule, functions.scheduled_activity_pause)
    streams.process_scheduled_activity = transformation.Map[str, str](named.streams.process_scheduled_activity, streams.scheduled_activity_pause, functions.process_scheduled_activity)
    streams.temporal_workflow_schedule = transformation.Input[str, str, Exception](named.streams.temporal_workflow_schedule, environment)
    streams.scheduled_workflow_pause = transformation.Delay[str](named.streams.scheduled_workflow_pause, streams.temporal_workflow_schedule, functions.scheduled_workflow_pause)
    streams.process_scheduled_workflow = transformation.Map[str, str](named.streams.process_scheduled_workflow, streams.scheduled_workflow_pause, functions.process_scheduled_workflow)
    streams.process_sequential_activity_a = transformation.Map[str, str](named.streams.process_sequential_activity_a, streams.consume_sequential_activity_a, functions.process_sequential_activity_a)
    streams.process_sequential_activity_b = transformation.Map[str, str](named.streams.process_sequential_activity_b, streams.consume_sequential_activity_b, functions.process_sequential_activity_b)
    streams.process_workflow_job = transformation.Map[str, str](named.streams.process_workflow_job, streams.call_sequential_activity_b, functions.process_workflow_job)
    streams.submit_fan_out_workflow_job = transformation.Sink[str, Exception](named.streams.submit_fan_out_workflow_job, streams.split_on_demand_jobs.add_stream())
    streams.consume_activity_job.set_source(streams.process_activity_job)
    streams.consume_workflow_job.set_source(streams.process_workflow_job)
    streams.consume_fan_out_activity_a.set_source(streams.process_fan_out_activity_a)
    streams.consume_fan_out_activity_b.set_source(streams.process_fan_out_activity_b)
    streams.consume_fan_out_activity_c.set_source(streams.process_fan_out_activity_c)
    streams.consume_sequential_activity_a.set_source(streams.process_sequential_activity_a)
    streams.consume_sequential_activity_b.set_source(streams.process_sequential_activity_b)
    streams.temporal_activity_schedule.set_source(streams.process_scheduled_activity)
    streams.temporal_workflow_schedule.set_source(streams.process_scheduled_workflow)
    return streams