dataConnectors:
  inventoryServiceApi:
    address: $inventoryServiceApiAddress
services:
  orderService:
    environment: $orderServiceEnvironment
    grpcHost: $orderServiceGrpcHost
    grpcPort: $orderServiceGrpcPort
    httpHost: $orderServiceHttpHost
    httpPort: $orderServiceHttpPort
