"""Code generated by servicegen. DO NOT EDIT."""

from __future__ import annotations

from collections.abc import Awaitable
from typing import Any, cast
from .makers_generated import _MakerGroup


class ServiceConnectors:
    def maker_calls(self, group: _MakerGroup, service: Any) -> list[tuple[str, Awaitable[Any]]]:
        named = service.config.named
        return [
        ]

    def bind(self, infrastructure: dict[str, list[Any]], service: Any) -> None:
        pass

    def init_connectors(self, service: Any) -> None:
        del service