"""Code generated by servicegen. DO NOT EDIT."""

from __future__ import annotations

import asyncio
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from typing import Any, Protocol, Self, cast
from pyservicelib_gorundebug.runtime.context.context import Context
from pyservicelib_gorundebug.runtime.environment import ServiceEnvironment
from ..functions import (
    CountOrderProcessed,
    AnalyticsScheduleSource,
    AdvanceCycleAnalytics,
    CompleteCycleAnalytics,
    ContinueCycleAnalytics,
    AnalyticsOrdersSource,
    AnalyticsPaymentsSource,
    AnalyticsShipmentsSource,
    CycleAnalyticsInputSource,
    CycleAnalyticsResultSink,
    HighValueAnalyticsSink,
    JoinedAnalyticsSink,
    OrderProcessedEndpointSource,
    StandardAnalyticsSink,
    SubstreamAnalyticsInputSource,
    SubstreamAnalyticsResultSink,
    JoinOrderPaymentAnalytics,
    KeyOrdersForJoin,
    KeyPaymentsForJoin,
    KeyOrdersForMultiJoin,
    KeyPaymentsForMultiJoin,
    KeyShipmentsForMultiJoin,
    MultiJoinAnalyticsEvents,
    RouteAnalyticsResult,
    BuildSubstreamAnalyticsResult,
    InvokeAnalyticsSubstream,
)


class FunctionMakers(Protocol):
    @property
    def count_order_processed(self) -> Callable[[Context, ServiceEnvironment], Awaitable[CountOrderProcessed]]: ...
    @property
    def analytics_schedule_source(self) -> Callable[[Context, ServiceEnvironment], Awaitable[AnalyticsScheduleSource]]: ...
    @property
    def advance_cycle_analytics(self) -> Callable[[Context, ServiceEnvironment], Awaitable[AdvanceCycleAnalytics]]: ...
    @property
    def complete_cycle_analytics(self) -> Callable[[Context, ServiceEnvironment], Awaitable[CompleteCycleAnalytics]]: ...
    @property
    def continue_cycle_analytics(self) -> Callable[[Context, ServiceEnvironment], Awaitable[ContinueCycleAnalytics]]: ...
    @property
    def analytics_orders_source(self) -> Callable[[Context, ServiceEnvironment], Awaitable[AnalyticsOrdersSource]]: ...
    @property
    def analytics_payments_source(self) -> Callable[[Context, ServiceEnvironment], Awaitable[AnalyticsPaymentsSource]]: ...
    @property
    def analytics_shipments_source(self) -> Callable[[Context, ServiceEnvironment], Awaitable[AnalyticsShipmentsSource]]: ...
    @property
    def cycle_analytics_input_source(self) -> Callable[[Context, ServiceEnvironment], Awaitable[CycleAnalyticsInputSource]]: ...
    @property
    def cycle_analytics_result_sink(self) -> Callable[[Context, ServiceEnvironment], Awaitable[CycleAnalyticsResultSink]]: ...
    @property
    def high_value_analytics_sink(self) -> Callable[[Context, ServiceEnvironment], Awaitable[HighValueAnalyticsSink]]: ...
    @property
    def joined_analytics_sink(self) -> Callable[[Context, ServiceEnvironment], Awaitable[JoinedAnalyticsSink]]: ...
    @property
    def order_processed_endpoint_source(self) -> Callable[[Context, ServiceEnvironment], Awaitable[OrderProcessedEndpointSource]]: ...
    @property
    def standard_analytics_sink(self) -> Callable[[Context, ServiceEnvironment], Awaitable[StandardAnalyticsSink]]: ...
    @property
    def substream_analytics_input_source(self) -> Callable[[Context, ServiceEnvironment], Awaitable[SubstreamAnalyticsInputSource]]: ...
    @property
    def substream_analytics_result_sink(self) -> Callable[[Context, ServiceEnvironment], Awaitable[SubstreamAnalyticsResultSink]]: ...
    @property
    def join_order_payment_analytics(self) -> Callable[[Context, ServiceEnvironment], Awaitable[JoinOrderPaymentAnalytics]]: ...
    @property
    def key_orders_for_join(self) -> Callable[[Context, ServiceEnvironment], Awaitable[KeyOrdersForJoin]]: ...
    @property
    def key_payments_for_join(self) -> Callable[[Context, ServiceEnvironment], Awaitable[KeyPaymentsForJoin]]: ...
    @property
    def key_orders_for_multi_join(self) -> Callable[[Context, ServiceEnvironment], Awaitable[KeyOrdersForMultiJoin]]: ...
    @property
    def key_payments_for_multi_join(self) -> Callable[[Context, ServiceEnvironment], Awaitable[KeyPaymentsForMultiJoin]]: ...
    @property
    def key_shipments_for_multi_join(self) -> Callable[[Context, ServiceEnvironment], Awaitable[KeyShipmentsForMultiJoin]]: ...
    @property
    def multi_join_analytics_events(self) -> Callable[[Context, ServiceEnvironment], Awaitable[MultiJoinAnalyticsEvents]]: ...
    @property
    def route_analytics_result(self) -> Callable[[Context, ServiceEnvironment], Awaitable[RouteAnalyticsResult]]: ...
    @property
    def build_substream_analytics_result(self) -> Callable[[Context, ServiceEnvironment], Awaitable[BuildSubstreamAnalyticsResult]]: ...
    @property
    def invoke_analytics_substream(self) -> Callable[[Context, ServiceEnvironment], Awaitable[InvokeAnalyticsSubstream]]: ...


@dataclass
class ServiceFunctions:
    count_order_processed: CountOrderProcessed
    analytics_schedule_source: AnalyticsScheduleSource
    advance_cycle_analytics: AdvanceCycleAnalytics
    complete_cycle_analytics: CompleteCycleAnalytics
    continue_cycle_analytics: ContinueCycleAnalytics
    analytics_orders_source: AnalyticsOrdersSource
    analytics_payments_source: AnalyticsPaymentsSource
    analytics_shipments_source: AnalyticsShipmentsSource
    cycle_analytics_input_source: CycleAnalyticsInputSource
    cycle_analytics_result_sink: CycleAnalyticsResultSink
    high_value_analytics_sink: HighValueAnalyticsSink
    joined_analytics_sink: JoinedAnalyticsSink
    order_processed_endpoint_source: OrderProcessedEndpointSource
    standard_analytics_sink: StandardAnalyticsSink
    substream_analytics_input_source: SubstreamAnalyticsInputSource
    substream_analytics_result_sink: SubstreamAnalyticsResultSink
    join_order_payment_analytics: JoinOrderPaymentAnalytics
    key_orders_for_join: KeyOrdersForJoin
    key_payments_for_join: KeyPaymentsForJoin
    key_orders_for_multi_join: KeyOrdersForMultiJoin
    key_payments_for_multi_join: KeyPaymentsForMultiJoin
    key_shipments_for_multi_join: KeyShipmentsForMultiJoin
    multi_join_analytics_events: MultiJoinAnalyticsEvents
    route_analytics_result: RouteAnalyticsResult
    build_substream_analytics_result: BuildSubstreamAnalyticsResult
    invoke_analytics_substream: InvokeAnalyticsSubstream

    @classmethod
    async def init_functions(cls, ctx: Context, environment: ServiceEnvironment, makers: FunctionMakers) -> Self:
        functions: dict[str, Any] = {}
        first_error_0: BaseException | None = None
        maker_context_0 = ctx.child()
    
        async def invoke_0(maker: Callable[[], Awaitable[Any]]) -> Any:
            nonlocal first_error_0
            try:
                return await maker()
            except BaseException as error:
                if first_error_0 is None:
                    first_error_0 = error
                    maker_context_0.cancel()
                raise
    
        maker_calls_0: list[tuple[str, Awaitable[Any]]] = [
            ("count_order_processed", invoke_0(lambda: makers.count_order_processed(maker_context_0, environment))),
            ("analytics_schedule_source", invoke_0(lambda: makers.analytics_schedule_source(maker_context_0, environment))),
            ("advance_cycle_analytics", invoke_0(lambda: makers.advance_cycle_analytics(maker_context_0, environment))),
            ("complete_cycle_analytics", invoke_0(lambda: makers.complete_cycle_analytics(maker_context_0, environment))),
            ("continue_cycle_analytics", invoke_0(lambda: makers.continue_cycle_analytics(maker_context_0, environment))),
            ("analytics_orders_source", invoke_0(lambda: makers.analytics_orders_source(maker_context_0, environment))),
            ("analytics_payments_source", invoke_0(lambda: makers.analytics_payments_source(maker_context_0, environment))),
            ("analytics_shipments_source", invoke_0(lambda: makers.analytics_shipments_source(maker_context_0, environment))),
            ("cycle_analytics_input_source", invoke_0(lambda: makers.cycle_analytics_input_source(maker_context_0, environment))),
            ("cycle_analytics_result_sink", invoke_0(lambda: makers.cycle_analytics_result_sink(maker_context_0, environment))),
            ("high_value_analytics_sink", invoke_0(lambda: makers.high_value_analytics_sink(maker_context_0, environment))),
            ("joined_analytics_sink", invoke_0(lambda: makers.joined_analytics_sink(maker_context_0, environment))),
            ("order_processed_endpoint_source", invoke_0(lambda: makers.order_processed_endpoint_source(maker_context_0, environment))),
            ("standard_analytics_sink", invoke_0(lambda: makers.standard_analytics_sink(maker_context_0, environment))),
            ("substream_analytics_input_source", invoke_0(lambda: makers.substream_analytics_input_source(maker_context_0, environment))),
            ("substream_analytics_result_sink", invoke_0(lambda: makers.substream_analytics_result_sink(maker_context_0, environment))),
            ("join_order_payment_analytics", invoke_0(lambda: makers.join_order_payment_analytics(maker_context_0, environment))),
            ("key_orders_for_join", invoke_0(lambda: makers.key_orders_for_join(maker_context_0, environment))),
            ("key_payments_for_join", invoke_0(lambda: makers.key_payments_for_join(maker_context_0, environment))),
            ("key_orders_for_multi_join", invoke_0(lambda: makers.key_orders_for_multi_join(maker_context_0, environment))),
            ("key_payments_for_multi_join", invoke_0(lambda: makers.key_payments_for_multi_join(maker_context_0, environment))),
            ("key_shipments_for_multi_join", invoke_0(lambda: makers.key_shipments_for_multi_join(maker_context_0, environment))),
            ("multi_join_analytics_events", invoke_0(lambda: makers.multi_join_analytics_events(maker_context_0, environment))),
            ("route_analytics_result", invoke_0(lambda: makers.route_analytics_result(maker_context_0, environment))),
            ("build_substream_analytics_result", invoke_0(lambda: makers.build_substream_analytics_result(maker_context_0, environment))),
            ("invoke_analytics_substream", invoke_0(lambda: makers.invoke_analytics_substream(maker_context_0, environment))),
        ]
        group_results_0 = await asyncio.gather(
            *(call for _, call in maker_calls_0), return_exceptions=True,
        )
        maker_context_0.cancel()
        if first_error_0 is not None:
            raise first_error_0
        for (name, _), value in zip(maker_calls_0, group_results_0):
            functions[name] = value
        return cls(
            count_order_processed=cast(CountOrderProcessed, functions["count_order_processed"]),
            analytics_schedule_source=cast(AnalyticsScheduleSource, functions["analytics_schedule_source"]),
            advance_cycle_analytics=cast(AdvanceCycleAnalytics, functions["advance_cycle_analytics"]),
            complete_cycle_analytics=cast(CompleteCycleAnalytics, functions["complete_cycle_analytics"]),
            continue_cycle_analytics=cast(ContinueCycleAnalytics, functions["continue_cycle_analytics"]),
            analytics_orders_source=cast(AnalyticsOrdersSource, functions["analytics_orders_source"]),
            analytics_payments_source=cast(AnalyticsPaymentsSource, functions["analytics_payments_source"]),
            analytics_shipments_source=cast(AnalyticsShipmentsSource, functions["analytics_shipments_source"]),
            cycle_analytics_input_source=cast(CycleAnalyticsInputSource, functions["cycle_analytics_input_source"]),
            cycle_analytics_result_sink=cast(CycleAnalyticsResultSink, functions["cycle_analytics_result_sink"]),
            high_value_analytics_sink=cast(HighValueAnalyticsSink, functions["high_value_analytics_sink"]),
            joined_analytics_sink=cast(JoinedAnalyticsSink, functions["joined_analytics_sink"]),
            order_processed_endpoint_source=cast(OrderProcessedEndpointSource, functions["order_processed_endpoint_source"]),
            standard_analytics_sink=cast(StandardAnalyticsSink, functions["standard_analytics_sink"]),
            substream_analytics_input_source=cast(SubstreamAnalyticsInputSource, functions["substream_analytics_input_source"]),
            substream_analytics_result_sink=cast(SubstreamAnalyticsResultSink, functions["substream_analytics_result_sink"]),
            join_order_payment_analytics=cast(JoinOrderPaymentAnalytics, functions["join_order_payment_analytics"]),
            key_orders_for_join=cast(KeyOrdersForJoin, functions["key_orders_for_join"]),
            key_payments_for_join=cast(KeyPaymentsForJoin, functions["key_payments_for_join"]),
            key_orders_for_multi_join=cast(KeyOrdersForMultiJoin, functions["key_orders_for_multi_join"]),
            key_payments_for_multi_join=cast(KeyPaymentsForMultiJoin, functions["key_payments_for_multi_join"]),
            key_shipments_for_multi_join=cast(KeyShipmentsForMultiJoin, functions["key_shipments_for_multi_join"]),
            multi_join_analytics_events=cast(MultiJoinAnalyticsEvents, functions["multi_join_analytics_events"]),
            route_analytics_result=cast(RouteAnalyticsResult, functions["route_analytics_result"]),
            build_substream_analytics_result=cast(BuildSubstreamAnalyticsResult, functions["build_substream_analytics_result"]),
            invoke_analytics_substream=cast(InvokeAnalyticsSubstream, functions["invoke_analytics_substream"]),
        )