"""Code generated by servicegen. DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Awaitable, Callable

from pyservicelib_gorundebug import transformation
from pyservicelib_gorundebug.runtime.context.context import Context
from pyservicelib_gorundebug.runtime.environment import ServiceEnvironment
from pyservicelib_gorundebug.runtime.config.endpoint_types import CustomEndpointConfig
from pyservicelib_gorundebug.runtime.config.stream_types import FilterStreamConfig, MapStreamConfig
from ..functions import (
    AdvanceCycleAnalytics,
    make_advance_cycle_analytics,
    CompleteCycleAnalytics,
    make_complete_cycle_analytics,
    ContinueCycleAnalytics,
    make_continue_cycle_analytics,
    CycleAnalyticsInputSource,
    make_cycle_analytics_input_source,
    CycleAnalyticsResultSink,
    make_cycle_analytics_result_sink,
)
from analytics_service.models.analytics_event import (
    AnalyticsEvent,
)
from analytics_service.models.analytics_key_generated import (
    AnalyticsKey,
)
from analytics_service.models.analytics_result import (
    AnalyticsResult,
)
from model.models.automation_job_generated import (
    AutomationJob,
)
from model.models.order_processed import (
    OrderProcessed,
)


@dataclass
class CycleAnalyticsPipelineMakers:
    advance_cycle_analytics: Callable[[Context, ServiceEnvironment, MapStreamConfig], Awaitable[AdvanceCycleAnalytics]] = make_advance_cycle_analytics
    complete_cycle_analytics: Callable[[Context, ServiceEnvironment, FilterStreamConfig], Awaitable[CompleteCycleAnalytics]] = make_complete_cycle_analytics
    continue_cycle_analytics: Callable[[Context, ServiceEnvironment, FilterStreamConfig], Awaitable[ContinueCycleAnalytics]] = make_continue_cycle_analytics
    cycle_analytics_input_source: Callable[[Context, ServiceEnvironment, CustomEndpointConfig], Awaitable[CycleAnalyticsInputSource]] = make_cycle_analytics_input_source
    cycle_analytics_result_sink: Callable[[Context, ServiceEnvironment, CustomEndpointConfig], Awaitable[CycleAnalyticsResultSink]] = make_cycle_analytics_result_sink


@dataclass
class CycleAnalyticsPipelineFunctions:
    advance_cycle_analytics: AdvanceCycleAnalytics
    complete_cycle_analytics: CompleteCycleAnalytics
    continue_cycle_analytics: ContinueCycleAnalytics
    cycle_analytics_input_source: CycleAnalyticsInputSource
    cycle_analytics_result_sink: CycleAnalyticsResultSink


@dataclass
class CycleAnalyticsPipelineStreams:
    cycle_analytics_link: Any = None
    cycle_analytics_input: Any = None
    merge_cycle_analytics: Any = None
    advance_cycle_analytics: Any = None
    split_cycle_analytics: Any = None
    complete_cycle_analytics: Any = None
    continue_cycle_analytics: Any = None
    write_cycle_analytics: Any = None


def init_cycle_analytics_streams(service: Any, named: Any) -> None:
    init_cycle_analytics_cycle_analytics_link_stream(service, named)
    init_cycle_analytics_cycle_analytics_input_stream(service, named)
    init_cycle_analytics_merge_cycle_analytics_stream(service, named)
    init_cycle_analytics_advance_cycle_analytics_stream(service, named)
    init_cycle_analytics_split_cycle_analytics_stream(service, named)
    init_cycle_analytics_complete_cycle_analytics_stream(service, named)
    init_cycle_analytics_continue_cycle_analytics_stream(service, named)
    init_cycle_analytics_write_cycle_analytics_stream(service, named)
    pass


def post_init_cycle_analytics_streams(service: Any) -> None:
    post_init_cycle_analytics_cycle_analytics_link_stream(service)
    pass
def init_cycle_analytics_cycle_analytics_link_stream(service: Any, named: Any) -> None:
    service._service_streams.cycle_analytics_link = transformation.Link[AnalyticsEvent](named.streams.cycle_analytics_link, service)
def init_cycle_analytics_cycle_analytics_input_stream(service: Any, named: Any) -> None:
    service._service_streams.cycle_analytics_input = transformation.Input[AnalyticsEvent, object, Exception](named.streams.cycle_analytics_input, service)
def init_cycle_analytics_merge_cycle_analytics_stream(service: Any, named: Any) -> None:
    service._service_streams.merge_cycle_analytics = transformation.Merge[AnalyticsEvent](named.streams.merge_cycle_analytics, service._service_streams.cycle_analytics_input, service._service_streams.cycle_analytics_link)
def init_cycle_analytics_advance_cycle_analytics_stream(service: Any, named: Any) -> None:
    service._service_streams.advance_cycle_analytics = transformation.Map[AnalyticsEvent, AnalyticsEvent](named.streams.advance_cycle_analytics, service._service_streams.merge_cycle_analytics, service.functions.advance_cycle_analytics)
def init_cycle_analytics_split_cycle_analytics_stream(service: Any, named: Any) -> None:
    service._service_streams.split_cycle_analytics = transformation.Split[AnalyticsEvent](named.streams.split_cycle_analytics, service._service_streams.advance_cycle_analytics)
def init_cycle_analytics_complete_cycle_analytics_stream(service: Any, named: Any) -> None:
    service._service_streams.complete_cycle_analytics = transformation.Filter[AnalyticsEvent](named.streams.complete_cycle_analytics, service._service_streams.split_cycle_analytics.add_stream(), service.functions.complete_cycle_analytics)
def init_cycle_analytics_continue_cycle_analytics_stream(service: Any, named: Any) -> None:
    service._service_streams.continue_cycle_analytics = transformation.Filter[AnalyticsEvent](named.streams.continue_cycle_analytics, service._service_streams.split_cycle_analytics.add_stream(), service.functions.continue_cycle_analytics)
def init_cycle_analytics_write_cycle_analytics_stream(service: Any, named: Any) -> None:
    service._service_streams.write_cycle_analytics = transformation.Sink[AnalyticsEvent, Exception](named.streams.write_cycle_analytics, service._service_streams.complete_cycle_analytics)
def post_init_cycle_analytics_cycle_analytics_link_stream(service: Any) -> None:
    service._service_streams.cycle_analytics_link.set_source(service._service_streams.continue_cycle_analytics)