"""Code generated by servicegen. DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Awaitable, Callable

from pyservicelib_gorundebug import transformation
from pyservicelib_gorundebug.runtime.context.context import Context
from pyservicelib_gorundebug.runtime.environment import ServiceEnvironment
from pyservicelib_gorundebug.runtime.config.endpoint_types import CustomEndpointConfig
from pyservicelib_gorundebug.runtime.config.stream_types import MapStreamConfig
from ..functions import (
    SubstreamAnalyticsInputSource,
    make_substream_analytics_input_source,
    SubstreamAnalyticsResultSink,
    make_substream_analytics_result_sink,
    BuildSubstreamAnalyticsResult,
    make_build_substream_analytics_result,
    InvokeAnalyticsSubstream,
    make_invoke_analytics_substream,
)
from analytics_service.models.analytics_event import (
    AnalyticsEvent,
)
from analytics_service.models.analytics_key_generated import (
    AnalyticsKey,
)
from analytics_service.models.analytics_result import (
    AnalyticsResult,
)
from model.models.automation_job_generated import (
    AutomationJob,
)
from model.models.order_processed import (
    OrderProcessed,
)


@dataclass
class SubstreamAnalyticsPipelineMakers:
    substream_analytics_input_source: Callable[[Context, ServiceEnvironment, CustomEndpointConfig], Awaitable[SubstreamAnalyticsInputSource]] = make_substream_analytics_input_source
    substream_analytics_result_sink: Callable[[Context, ServiceEnvironment, CustomEndpointConfig], Awaitable[SubstreamAnalyticsResultSink]] = make_substream_analytics_result_sink
    build_substream_analytics_result: Callable[[Context, ServiceEnvironment, MapStreamConfig], Awaitable[BuildSubstreamAnalyticsResult]] = make_build_substream_analytics_result
    invoke_analytics_substream: Callable[[Context, ServiceEnvironment, MapStreamConfig], Awaitable[InvokeAnalyticsSubstream]] = make_invoke_analytics_substream


@dataclass
class SubstreamAnalyticsPipelineFunctions:
    substream_analytics_input_source: SubstreamAnalyticsInputSource
    substream_analytics_result_sink: SubstreamAnalyticsResultSink
    build_substream_analytics_result: BuildSubstreamAnalyticsResult
    invoke_analytics_substream: InvokeAnalyticsSubstream


@dataclass
class SubstreamAnalyticsPipelineStreams:
    analyze_analytics_substream: transformation.SubStream[AnalyticsEvent, AnalyticsResult] | None = None
    build_substream_analytics_result: Any = None
    substream_analytics_input: Any = None
    invoke_analytics_substream: Any = None
    write_substream_analytics: Any = None


def init_substream_analytics_streams(service: Any, named: Any) -> None:
    init_substream_analytics_analyze_analytics_substream_stream(service, named)
    init_substream_analytics_build_substream_analytics_result_stream(service, named)
    init_substream_analytics_substream_analytics_input_stream(service, named)
    init_substream_analytics_invoke_analytics_substream_stream(service, named)
    init_substream_analytics_write_substream_analytics_stream(service, named)
    pass


def post_init_substream_analytics_streams(service: Any) -> None:
    post_init_substream_analytics_analyze_analytics_substream_stream(service)
    pass
def init_substream_analytics_analyze_analytics_substream_stream(service: Any, named: Any) -> None:
    service._service_streams.analyze_analytics_substream = transformation.SubStream[AnalyticsEvent, AnalyticsResult](named.streams.analyze_analytics_substream, service)
    service._analyze_analytics_substream_substream.target = service._service_streams.analyze_analytics_substream
def init_substream_analytics_build_substream_analytics_result_stream(service: Any, named: Any) -> None:
    service._service_streams.build_substream_analytics_result = transformation.Map[AnalyticsEvent, AnalyticsResult](named.streams.build_substream_analytics_result, service._service_streams.analyze_analytics_substream, service.functions.build_substream_analytics_result)
def init_substream_analytics_substream_analytics_input_stream(service: Any, named: Any) -> None:
    service._service_streams.substream_analytics_input = transformation.Input[AnalyticsEvent, object, Exception](named.streams.substream_analytics_input, service)
def init_substream_analytics_invoke_analytics_substream_stream(service: Any, named: Any) -> None:
    service._service_streams.invoke_analytics_substream = transformation.Map[AnalyticsEvent, AnalyticsResult](named.streams.invoke_analytics_substream, service._service_streams.substream_analytics_input, service.functions.invoke_analytics_substream)
def init_substream_analytics_write_substream_analytics_stream(service: Any, named: Any) -> None:
    service._service_streams.write_substream_analytics = transformation.Sink[AnalyticsResult, Exception](named.streams.write_substream_analytics, service._service_streams.invoke_analytics_substream)
def post_init_substream_analytics_analyze_analytics_substream_stream(service: Any) -> None:
    service._service_streams.analyze_analytics_substream.set_source(service._service_streams.build_substream_analytics_result)