"""Code generated by servicegen. DO NOT EDIT."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Awaitable, Callable

from pyservicelib_gorundebug import transformation
from pyservicelib_gorundebug.runtime.context.context import Context
from pyservicelib_gorundebug.runtime.environment import ServiceEnvironment
from pyservicelib_gorundebug.runtime.config.endpoint_types import CronEndpointConfig, KafkaEndpointConfig
from pyservicelib_gorundebug.runtime.config.stream_types import ProcessStreamConfig
from ..functions import (
    CountOrderProcessed,
    make_count_order_processed,
    AnalyticsScheduleSource,
    make_analytics_schedule_source,
    OrderProcessedEndpointSource,
    make_order_processed_endpoint_source,
)
from analytics_service.models.analytics_event import (
    AnalyticsEvent,
)
from analytics_service.models.analytics_key_generated import (
    AnalyticsKey,
)
from analytics_service.models.analytics_result import (
    AnalyticsResult,
)
from model.models.automation_job_generated import (
    AutomationJob,
)
from model.models.order_processed import (
    OrderProcessed,
)


@dataclass
class AnalyticsPipelineMakers:
    count_order_processed: Callable[[Context, ServiceEnvironment, ProcessStreamConfig], Awaitable[CountOrderProcessed]] = make_count_order_processed
    analytics_schedule_source: Callable[[Context, ServiceEnvironment, CronEndpointConfig], Awaitable[AnalyticsScheduleSource]] = make_analytics_schedule_source
    order_processed_endpoint_source: Callable[[Context, ServiceEnvironment, KafkaEndpointConfig], Awaitable[OrderProcessedEndpointSource]] = make_order_processed_endpoint_source


@dataclass
class AnalyticsPipelineFunctions:
    count_order_processed: CountOrderProcessed
    analytics_schedule_source: AnalyticsScheduleSource
    order_processed_endpoint_source: OrderProcessedEndpointSource


@dataclass
class AnalyticsPipelineStreams:
    analytics_schedule: Any = None
    consume_order_processed: Any = None
    count_order_processed: Any = None


def init_analytics_streams(service: Any, named: Any) -> None:
    init_analytics_analytics_schedule_stream(service, named)
    init_analytics_consume_order_processed_stream(service, named)
    init_analytics_count_order_processed_stream(service, named)
    pass


def post_init_analytics_streams(service: Any) -> None:
    post_init_analytics_consume_order_processed_stream(service)
    pass
def init_analytics_analytics_schedule_stream(service: Any, named: Any) -> None:
    service._service_streams.analytics_schedule = transformation.Input[str, object, Exception](named.streams.analytics_schedule, service)
def init_analytics_consume_order_processed_stream(service: Any, named: Any) -> None:
    service._service_streams.consume_order_processed = transformation.Input[OrderProcessed, OrderProcessed, Exception](named.streams.consume_order_processed, service)
def init_analytics_count_order_processed_stream(service: Any, named: Any) -> None:
    service._service_streams.count_order_processed = transformation.Process[OrderProcessed, OrderProcessed, Exception](named.streams.count_order_processed, service._service_streams.consume_order_processed, service.functions.count_order_processed)
def post_init_analytics_consume_order_processed_stream(service: Any) -> None:
    service._service_streams.consume_order_processed.set_source(service._service_streams.count_order_processed)