# Code generated by servicegen. DO NOT EDIT.

.DEFAULT_GOAL := build

ifneq ($(strip $(SERVICEGEN_DEPENDENCY_PROXY_DIR)),)
SERVICEGEN_DEPENDENCY_PROXY_HOST ?= localhost
SERVICEGEN_DEPENDENCY_PROXY_PORT ?= 18081
export PIP_INDEX_URL := http://$(SERVICEGEN_DEPENDENCY_PROXY_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/pypi-proxy/simple
export PIP_TRUSTED_HOST := $(SERVICEGEN_DEPENDENCY_PROXY_HOST)
export UV_INDEX_URL := http://$(SERVICEGEN_DEPENDENCY_PROXY_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/pypi-proxy/simple
endif

.PHONY: generate build test lint fmt clean help

generate: ## Regenerate protobuf/OpenAPI bindings
	@./generate.generated.sh

build: generate ## Build the Python package wheel
	@uv build

test: generate ## Validate the package
	@uv run python -m compileall -q src

lint: generate ## Run Ruff checks
	@uv run ruff check --force-exclude --exclude generated src

fmt: generate ## Format and auto-fix Python sources
	@uv run ruff check --fix --force-exclude --exclude generated src
	@uv run ruff format --force-exclude --exclude generated src

clean: ## Remove Python build and cache artifacts
	@rm -rf .venv dist build .mypy_cache .pytest_cache .ruff_cache
	@find . -type d -name __pycache__ -prune -exec rm -rf {} +

help: ## Show this help
	@grep -hE '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
	  sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-24s %s\n", $$1, $$2}'